#include <ap_int.h>
#include "spbits.h"
#include "zones.h"





/*
void zones()
{
std::cout<<"ph_raw_w: "<<ph_raw_w<<std::endl;
ap_uint<4> phzvl[5][9];
            phzvl[0][0]=0x8;
std::cout<<"phzvl: "<<phzvl[0][0]<<std::hex<<std::endl;
if(phzvl[0][0] & 0x1)
	std::cout<<" HI"<<std::endl;
else
	std::cout<<"BYE "<<std::endl;

ap_uint<4> ret=0x1;
phzvl[0][0](2,0)=phzvl[0][0](2,0) | ret;
std::cout<<"phzvl after : "<<phzvl[0][0]<<std::hex<<std::endl;


}
*/

using namespace std;





void zones_class::zones_actual(
		 ap_uint<3> phzvl[5][9],
		 ap_uint<ph_hit_w> ph_hit[5][9],
			 ap_uint<ph_raw_w> ph_zone[4][5])
{
#pragma HLS ARRAY_PARTITION variable=phzvl complete dim=0
#pragma HLS ARRAY_PARTITION variable=ph_hit complete dim=0
#pragma HLS ARRAY_PARTITION variable=ph_zone complete dim=0
#pragma HLS ARRAY_PARTITION variable=a_ph_zone complete dim=0
#pragma HLS INTERFACE ap_ctrl_none port=return
#pragma HLS INLINE off
#pragma HLS PIPELINE II=1
	// the hardcoded numbers in the code below come from ph_init_full* files generated by CMSSW
			// they are divided by 32 since pattern detectors are using 7-bit phi.
			// Offset is subtracted from them to account for possible chamber movement
			// CMSSW software has these numbers in ph_init_hard array, so it can generate ph_offsets

			// ph zone 0 stations 1234
	ap_uint<3> a_phzvl[5][9];
	ap_uint<ph_hit_w> a_ph_hit[5][9];
#pragma HLS ARRAY_PARTITION variable=a_phzvl complete dim=0
#pragma HLS ARRAY_PARTITION variable=a_ph_hit complete dim=0
		for(int i=0;i<5;i++){
			for(int j=0;j<9;j++){
				a_phzvl[i][j]=phzvl[i][j];
				a_ph_hit[i][j]=ph_hit[i][j];
			}
		}

	a_ph_zone[0][1] = 0;
	                if (a_phzvl[0][0][0]) a_ph_zone[0][1](2+ph_hit_w10-1 , 2)= a_ph_zone[0][1](2+ph_hit_w10-1 , 2)| a_ph_hit[0][0];
	                if (a_phzvl[0][1][0]) a_ph_zone[0][1]( 20+ph_hit_w10-1,20) = a_ph_zone[0][1](20+ph_hit_w10-1,20) | a_ph_hit[0][1];
	                if (a_phzvl[0][2][0]) a_ph_zone[0][1]( 39+ph_hit_w10-1 , 39) = a_ph_zone[0][1](39+ph_hit_w10-1 , 39) | a_ph_hit[0][2];
	                if (a_phzvl[1][0][0]) a_ph_zone[0][1]( 58+ph_hit_w10-1 , 58) = a_ph_zone[0][1](58+ph_hit_w10-1 , 58) | a_ph_hit[1][0];
	                if (a_phzvl[1][1][0]) a_ph_zone[0][1]( 77+ph_hit_w10-1 , 77) = a_ph_zone[0][1](77+ph_hit_w10-1 , 77) | a_ph_hit[1][1];
	                if (a_phzvl[1][2][0]) a_ph_zone[0][1]( 95+ph_hit_w10-1 , 95) = a_ph_zone[0][1](95+ph_hit_w10-1 , 95) | a_ph_hit[1][2];

	    	        a_ph_zone[0][2] = 0;
	    	                if (a_phzvl[2][0][0]) a_ph_zone[0][2](1+ph_hit_w20 , 1) = a_ph_zone[0][2](1+ph_hit_w20 , 1) | a_ph_hit[2][0];
	    	                if (a_phzvl[2][1][0]) a_ph_zone[0][2]( 39+ph_hit_w20 , 39) =a_ph_zone[0][2](39+ph_hit_w20 , 36) |  a_ph_hit[2][1];
	    	              	if (a_phzvl[2][2][0]) a_ph_zone[0][2]( 76+ph_hit_w20 , 76) =a_ph_zone[0][2](76+ph_hit_w20 , 76) |  a_ph_hit[2][2];

	        a_ph_zone[0][3] = 0;
	                if (a_phzvl[3][0][0]) a_ph_zone[0][3](  1+ph_hit_w20, 1) =a_ph_zone[0][3](1+ph_hit_w20, 1) | a_ph_hit[3][0];
	                if (a_phzvl[3][1][0]) a_ph_zone[0][3](  39+ph_hit_w20, 39) = a_ph_zone[0][3]( 39+ph_hit_w20, 39) | a_ph_hit[3][1];
	                if (a_phzvl[3][2][0]) a_ph_zone[0][3](  76+ph_hit_w20, 76) = a_ph_zone[0][3]( 76+ph_hit_w20, 76) | a_ph_hit[3][2];

	        a_ph_zone[0][4] = 0;
	                if (a_phzvl[4][0][0]) a_ph_zone[0][4]( 1+ph_hit_w20 , 1) = a_ph_zone[0][4](  1+ph_hit_w20 ,1) | a_ph_hit[4][0];

	                if (a_phzvl[4][1][0]) a_ph_zone[0][4]( 39+ph_hit_w20 , 39) =a_ph_zone[0][4](    39+ph_hit_w20 , 39) |  a_ph_hit[4][1];

	                if (a_phzvl[4][2][0]) a_ph_zone[0][4]( 76+ph_hit_w20 , 76) =a_ph_zone[0][4](   76+ph_hit_w20 , 76) |  a_ph_hit[4][2];

	                // ph zone 1 stations 1234
	        //      a_ph_zone[1][1] = a_ph_zone[0][1]; // data taken from the same chambers
	        //      a_ph_zone[1][2] = a_ph_zone[0][2];
	        a_ph_zone[1][1] = 0;
	                if (a_phzvl[0][0][1]) a_ph_zone[1][1](2+ph_hit_w10-1 , 2) = a_ph_zone[1][1](2+ph_hit_w10-1 , 2) | a_ph_hit[0][0];
	                if (a_phzvl[0][1][1]) a_ph_zone[1][1]( 20+ph_hit_w10-1 ,20) =a_ph_zone[1][1](20+ph_hit_w10-1 , 20) |  a_ph_hit[0][1];
	                if (a_phzvl[0][2][1]) a_ph_zone[1][1]( 39+ph_hit_w10-1 , 39) =a_ph_zone[1][1](39+ph_hit_w10-1 , 39) |  a_ph_hit[0][2];
	                if (a_phzvl[1][0][1]) a_ph_zone[1][1]( 58+ph_hit_w10-1 , 58) =a_ph_zone[1][1](58+ph_hit_w10-1 , 58) |  a_ph_hit[1][0];
	                if (a_phzvl[1][1][1]) a_ph_zone[1][1]( 77+ph_hit_w10-1 , 77) =a_ph_zone[1][1](77+ph_hit_w10-1 , 77) |  a_ph_hit[1][1];
	                if (a_phzvl[1][2][1]) a_ph_zone[1][1]( 95+ph_hit_w10-1 , 95) =a_ph_zone[1][1](95+ph_hit_w10-1 , 95) |  a_ph_hit[1][2];

	        a_ph_zone[1][2] = 0;
	                if (a_phzvl[2][0][1]) a_ph_zone[1][2]( 1+ph_hit_w20 , 1) = a_ph_zone[1][2](    1+ph_hit_w20 , 1) | a_ph_hit[2][0];
	                if (a_phzvl[2][1][1]) a_ph_zone[1][2]( 39+ph_hit_w20 , 39) = a_ph_zone[1][2](  39+ph_hit_w20 , 39) | a_ph_hit[2][1];
	                if (a_phzvl[2][2][1]) a_ph_zone[1][2]( 76+ph_hit_w20 , 76) = a_ph_zone[1][2](  76+ph_hit_w20, 76) | a_ph_hit[2][2];


	        a_ph_zone[1][3] = 0;
	                if (a_phzvl[3][3][0]) a_ph_zone[1][3](   2+ph_hit_w10-1 , 2) = a_ph_zone[1][3](   2+ph_hit_w10-1 , 2) | a_ph_hit[3][3];
	                if (a_phzvl[3][4][0]) a_ph_zone[1][3]( 21+ph_hit_w10-1 , 21) = a_ph_zone[1][3](    21+ph_hit_w10-1 , 21) | a_ph_hit[3][4];
	                if (a_phzvl[3][5][0]) a_ph_zone[1][3]( 39+ph_hit_w10-1 , 39) = a_ph_zone[1][3](    39+ph_hit_w10-1 , 39) | a_ph_hit[3][5];
	                if (a_phzvl[3][6][0]) a_ph_zone[1][3]( 58+ph_hit_w10-1 , 58) = a_ph_zone[1][3](    58+ph_hit_w10-1 , 58) | a_ph_hit[3][6];
	                if (a_phzvl[3][7][0]) a_ph_zone[1][3]( 77+ph_hit_w10-1 , 77) = a_ph_zone[1][3](    77+ph_hit_w10-1 , 77) | a_ph_hit[3][7];
	                if (a_phzvl[3][8][0]) a_ph_zone[1][3]( 95+ph_hit_w10-1 , 95) = a_ph_zone[1][3](    95+ph_hit_w10-1 , 95) | a_ph_hit[3][8];

	        a_ph_zone[1][4] = 0;
	                if (a_phzvl[4][3][0]) a_ph_zone[1][4]( 2+ph_hit_w10-1, 2) = a_ph_zone[1][4](   2+ph_hit_w10-1 , 2) | a_ph_hit[4][3];
	                if (a_phzvl[4][4][0]) a_ph_zone[1][4]( 21+ph_hit_w10-1 , 21) = a_ph_zone[1][4](    21+ph_hit_w10-1 , 21) | a_ph_hit[4][4];
	                if (a_phzvl[4][5][0]) a_ph_zone[1][4]( 39+ph_hit_w10-1 , 39) = a_ph_zone[1][4](    39+ph_hit_w10-1 , 39) | a_ph_hit[4][5];
	                if (a_phzvl[4][6][0]) a_ph_zone[1][4]( 58+ph_hit_w10-1, 58) = a_ph_zone[1][4](     58+ph_hit_w10-1 , 58) | a_ph_hit[4][6];
	                if (a_phzvl[4][7][0]) a_ph_zone[1][4]( 77+ph_hit_w10-1, 77) = a_ph_zone[1][4](     77+ph_hit_w10-1 , 77) | a_ph_hit[4][7];
	                if (a_phzvl[4][8][0]) a_ph_zone[1][4]( 95+ph_hit_w10-1 , 95) = a_ph_zone[1][4](    95+ph_hit_w10-1 , 95) | a_ph_hit[4][8];

	                // ph zone 2 stations 1234
	        a_ph_zone[2][1] = 0;
	                if (a_phzvl[0][3][0]) a_ph_zone[2][1](2+ph_hit_w10-1 , 2) =a_ph_zone[2][1](    2+ph_hit_w10-1 , 2) |  a_ph_hit[0][3];
	                for(int j=0;j<5;j++){
	               	                	std::cout<<"1a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;
	               	                	                       	        	}
	                if (a_phzvl[0][4][0]) a_ph_zone[2][1]( 21+ph_hit_w10-1 , 21) =a_ph_zone[2][1](    21+ph_hit_w10-1 , 21) |  a_ph_hit[0][4];
	                for(int j=0;j<5;j++)
	                	               	                	std::cout<<"2a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;

	                if (a_phzvl[0][5][0]) a_ph_zone[2][1]( 39+ph_hit_w10-1,39) =  a_ph_hit[0][5] | a_ph_zone[2][1](   39+ph_hit_w10-1,39) ;
	                for(int j=0;j<5;j++)
	                	               	                	std::cout<<"3a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;

	                if (a_phzvl[1][3][0]) a_ph_zone[2][1]( 58+ph_hit_w10-1 , 58) = a_ph_zone[2][1](   58+ph_hit_w10-1 , 58) | a_ph_hit[1][3];
	                for(int j=0;j<5;j++)
	                	               	                	std::cout<<"4a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;

	                if (a_phzvl[1][4][0]) a_ph_zone[2][1]( 77+ph_hit_w10-1 , 77) = a_ph_zone[2][1](   77+ph_hit_w10-1 , 77) | a_ph_hit[1][4];
	                for(int j=0;j<5;j++)
	                	               	                	std::cout<<"5a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;

	                if (a_phzvl[1][5][0]) a_ph_zone[2][1]( 96+ph_hit_w10-1, 96) = a_ph_zone[2][1](  96+ph_hit_w10-1, 96) | a_ph_hit[1][5];
	                for(int j=0;j<5;j++)
	                	               	                	std::cout<<"6a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;



	        a_ph_zone[2][2] = 0;
	                if (a_phzvl[2][3][0]) a_ph_zone[2][2](   2+ph_hit_w10-1 , 2) = a_ph_zone[2][2](   2+ph_hit_w10-1 , 2) | a_ph_hit[2][3];
	                if (a_phzvl[2][4][0]) a_ph_zone[2][2]( 21+ph_hit_w10-1 , 21) = a_ph_zone[2][2](   21+ph_hit_w10-1 , 21) | a_ph_hit[2][4];
	                if (a_phzvl[2][5][0]) a_ph_zone[2][2]( 39+ph_hit_w10-1 , 39) = a_ph_zone[2][2](   39+ph_hit_w10-1 , 39) | a_ph_hit[2][5];
	                if (a_phzvl[2][6][0]) a_ph_zone[2][2]( 58+ph_hit_w10-1 , 58) = a_ph_zone[2][2](   58+ph_hit_w10-1 , 58) | a_ph_hit[2][6];
	                if (a_phzvl[2][7][0]) a_ph_zone[2][2]( 77+ph_hit_w10-1 , 77) = a_ph_zone[2][2](   77+ph_hit_w10-1 , 77) | a_ph_hit[2][7];
	                if (a_phzvl[2][8][0]) a_ph_zone[2][2]( 95+ph_hit_w10-1 , 95) = a_ph_zone[2][2](   95+ph_hit_w10-1 , 95) | a_ph_hit[2][8];

	        //      a_ph_zone[2][3] = a_ph_zone[1][3]; // data taken from the same chambers
	        //      a_ph_zone[2][4] = a_ph_zone[1][4];
	        a_ph_zone[2][3] = 0;
	                if (a_phzvl[3][3][1]) a_ph_zone[2][3](   2+ph_hit_w10-1 , 2) = a_ph_zone[2][3](   2+ph_hit_w10-1 , 2) | a_ph_hit[3][3];
	                if (a_phzvl[3][4][1]) a_ph_zone[2][3]( 21+ph_hit_w10-1 , 21) = a_ph_zone[2][3](   21+ph_hit_w10-1 , 21) | a_ph_hit[3][4];
	                if (a_phzvl[3][5][1]) a_ph_zone[2][3]( 39+ph_hit_w10-1 , 39) = a_ph_zone[2][3](   39+ph_hit_w10-1 , 39) | a_ph_hit[3][5];
	                if (a_phzvl[3][6][1]) a_ph_zone[2][3]( 58+ph_hit_w10-1 , 58) = a_ph_zone[2][3](   58+ph_hit_w10-1 , 58) | a_ph_hit[3][6];
	                if (a_phzvl[3][7][1]) a_ph_zone[2][3]( 77+ph_hit_w10-1 , 77) = a_ph_zone[2][3](   77+ph_hit_w10-1 , 77) | a_ph_hit[3][7];
	                if (a_phzvl[3][8][1]) a_ph_zone[2][3]( 95+ph_hit_w10-1 , 95) = a_ph_zone[2][3](   95+ph_hit_w10-1 , 95) | a_ph_hit[3][8];

	        a_ph_zone[2][4] = 0;
	                if (a_phzvl[4][3][1]) a_ph_zone[2][4](  1+ph_hit_w10-1, 1) = a_ph_zone[2][4](   1, 1+ph_hit_w10-1) | a_ph_hit[4][3];
	                if (a_phzvl[4][4][1]) a_ph_zone[2][4]( 20+ph_hit_w10-1, 20) = a_ph_zone[2][4](   20+ph_hit_w10-1, 20) | a_ph_hit[4][4];
	                if (a_phzvl[4][5][1]) a_ph_zone[2][4]( 39+ph_hit_w10-1 , 39) = a_ph_zone[2][4](   39+ph_hit_w10-1 , 39) | a_ph_hit[4][5];
	                if (a_phzvl[4][6][1]) a_ph_zone[2][4]( 58+ph_hit_w10-1 , 58) = a_ph_zone[2][4](   58+ph_hit_w10-1 , 58) | a_ph_hit[4][6];
	                if (a_phzvl[4][7][1]) a_ph_zone[2][4]( 76+ph_hit_w10-1, 76) = a_ph_zone[2][4](   76+ph_hit_w10-1, 76) | a_ph_hit[4][7];
	                if (a_phzvl[4][8][1]) a_ph_zone[2][4]( 95+ph_hit_w10-1 , 95) = a_ph_zone[2][4](   95+ph_hit_w10-1 , 95) | a_ph_hit[4][8];

	                // ph zone 3 stations 1234


	                for(int j=0;j<5;j++){
	                	std::cout<<"a_ph_zone["<<2<<"]["<<j<<"]= "<<a_ph_zone[2][j]<<std::hex<<std::endl;
	                	std::cout<<"a_phzvl["<<0<<"]["<<3<<"]= "<<a_phzvl[0][3]<<std::hex<<std::endl;
	                	std::cout<<"a_phzvl["<<0<<"]["<<4<<"]= "<<a_phzvl[0][4]<<std::hex<<std::endl;
	                	std::cout<<"a_phzvl["<<0<<"]["<<5<<"]= "<<a_phzvl[0][5]<<std::hex<<std::endl;
	                	std::cout<<"a_phzvl["<<1<<"]["<<3<<"]= "<<a_phzvl[1][3]<<std::hex<<std::endl;
	                	std::cout<<"a_phzvl["<<1<<"]["<<4<<"]= "<<a_phzvl[1][4]<<std::hex<<std::endl;
	                	std::cout<<"a_phzvl["<<1<<"]["<<5<<"]= "<<a_phzvl[1][5]<<std::hex<<std::endl;


	                	                       	        	}


	        a_ph_zone[3][1] = 0;
	                a_ph_zone[3][1](  4+ph_hit_w10-1, 4) = a_ph_zone[3][1](    4+ph_hit_w10-1, 4) | a_ph_hit[0][6];
	                a_ph_zone[3][1](  23+ph_hit_w10-1, 23) = a_ph_zone[3][1](   23+ph_hit_w10-1, 23) | a_ph_hit[0][7];
	                a_ph_zone[3][1](  42+ph_hit_w10-1, 42) = a_ph_zone[3][1](   42+ph_hit_w10-1, 42) | a_ph_hit[0][8];
	                a_ph_zone[3][1](  61+ph_hit_w10-1, 61) = a_ph_zone[3][1](   61+ph_hit_w10-1, 61) | a_ph_hit[1][6];
	                a_ph_zone[3][1](  79+ph_hit_w10-1, 79) = a_ph_zone[3][1](   79+ph_hit_w10-1, 79) |  a_ph_hit[1][7];
	                a_ph_zone[3][1](  98+ph_hit_w10-1, 98) = a_ph_zone[3][1](   98+ph_hit_w10-1, 98) | a_ph_hit[1][8];

	               /* a_ph_zone[3][1](  98+ph_hit_w10-1, 98)=0x1FFFFF;
	               cout<<"!!!!!!!!!"<<a_ph_zone[3][1](  98+ph_hit_w10-1, 98)<<"     "<<endl;
*/

	        //      a_ph_zone[3][2] = a_ph_zone[2][2]; // data taken from the same chambers
	        //      a_ph_zone[3][3] = a_ph_zone[2][3];
	        a_ph_zone[3][2] = 0;
	                if (a_phzvl[2][3][1]) a_ph_zone[3][2](   2+ph_hit_w10-1 , 2) = a_ph_zone[3][2](   2+ph_hit_w10-1 , 2) | a_ph_hit[2][3];
	                if (a_phzvl[2][4][1]) a_ph_zone[3][2]( 21+ph_hit_w10-1 , 21) = a_ph_zone[3][2](   21+ph_hit_w10-1 , 21) | a_ph_hit[2][4];
	                if (a_phzvl[2][5][1]) a_ph_zone[3][2]( 39+ph_hit_w10-1 , 39) = a_ph_zone[3][2](   39+ph_hit_w10-1 , 39) | a_ph_hit[2][5];
	                if (a_phzvl[2][6][1]) a_ph_zone[3][2]( 58+ph_hit_w10-1 , 58) = a_ph_zone[3][2](   58+ph_hit_w10-1 , 58) | a_ph_hit[2][6];
	                if (a_phzvl[2][7][1]) a_ph_zone[3][2]( 77+ph_hit_w10-1 , 77) = a_ph_zone[3][2](   77+ph_hit_w10-1 , 77) | a_ph_hit[2][7];
	                if (a_phzvl[2][8][1]) a_ph_zone[3][2]( 95+ph_hit_w10-1 , 95) = a_ph_zone[3][2](   95+ph_hit_w10-1 , 95) | a_ph_hit[2][8];

	        a_ph_zone[3][3] = 0;
	                if (a_phzvl[3][3][2]) a_ph_zone[3][3](   2+ph_hit_w10-1 , 2) = a_ph_zone[3][3](   2+ph_hit_w10-1 , 2) | a_ph_hit[3][3];
	                if (a_phzvl[3][4][2]) a_ph_zone[3][3]( 21+ph_hit_w10-1 , 21) = a_ph_zone[3][3](   21+ph_hit_w10-1 , 21) | a_ph_hit[3][4];
	                if (a_phzvl[3][5][2]) a_ph_zone[3][3]( 39+ph_hit_w10-1 , 39) = a_ph_zone[3][3](   39+ph_hit_w10-1 , 39) | a_ph_hit[3][5];
	                if (a_phzvl[3][6][2]) a_ph_zone[3][3]( 58+ph_hit_w10-1 , 58) = a_ph_zone[3][3](   58+ph_hit_w10-1 , 58) | a_ph_hit[3][6];
	                if (a_phzvl[3][7][2]) a_ph_zone[3][3]( 77+ph_hit_w10-1 , 77) = a_ph_zone[3][3](   77+ph_hit_w10-1 , 77) | a_ph_hit[3][7];
	                if (a_phzvl[3][8][2]) a_ph_zone[3][3]( 95+ph_hit_w10-1 , 95) = a_ph_zone[3][3](   95+ph_hit_w10-1 , 95) | a_ph_hit[3][8];

	                a_ph_zone[3][4] = 0; // no st 4 in this zone








	     /*********assign output******/

	        zones_label0:for(int i=0;i<4;i++){
#pragma HLS UNROLL
	        	zones_label1:for(int j=0;j<5;j++){
#pragma HLS UNROLL
	        		ph_zone[i][j]=a_ph_zone[i][j];
	        	}
	        }
}



