// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sp_co_ord_delay (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        phi_0_0_0_V_read,
        phi_0_0_1_V_read,
        phi_0_1_0_V_read,
        phi_0_1_1_V_read,
        phi_0_2_0_V_read,
        phi_0_2_1_V_read,
        phi_0_3_0_V_read,
        phi_0_3_1_V_read,
        phi_0_4_0_V_read,
        phi_0_4_1_V_read,
        phi_0_5_0_V_read,
        phi_0_5_1_V_read,
        phi_0_6_0_V_read,
        phi_0_6_1_V_read,
        phi_0_7_0_V_read,
        phi_0_7_1_V_read,
        phi_0_8_0_V_read,
        phi_0_8_1_V_read,
        phi_1_0_0_V_read,
        phi_1_0_1_V_read,
        phi_1_1_0_V_read,
        phi_1_1_1_V_read,
        phi_1_2_0_V_read,
        phi_1_2_1_V_read,
        phi_1_3_0_V_read,
        phi_1_3_1_V_read,
        phi_1_4_0_V_read,
        phi_1_4_1_V_read,
        phi_1_5_0_V_read,
        phi_1_5_1_V_read,
        phi_1_6_0_V_read,
        phi_1_6_1_V_read,
        phi_1_7_0_V_read,
        phi_1_7_1_V_read,
        phi_1_8_0_V_read,
        phi_1_8_1_V_read,
        phi_2_0_0_V_read,
        phi_2_0_1_V_read,
        phi_2_1_0_V_read,
        phi_2_1_1_V_read,
        phi_2_2_0_V_read,
        phi_2_2_1_V_read,
        phi_2_3_0_V_read,
        phi_2_3_1_V_read,
        phi_2_4_0_V_read,
        phi_2_4_1_V_read,
        phi_2_5_0_V_read,
        phi_2_5_1_V_read,
        phi_2_6_0_V_read,
        phi_2_6_1_V_read,
        phi_2_7_0_V_read,
        phi_2_7_1_V_read,
        phi_2_8_0_V_read,
        phi_2_8_1_V_read,
        phi_3_0_0_V_read,
        phi_3_0_1_V_read,
        phi_3_1_0_V_read,
        phi_3_1_1_V_read,
        phi_3_2_0_V_read,
        phi_3_2_1_V_read,
        phi_3_3_0_V_read,
        phi_3_3_1_V_read,
        phi_3_4_0_V_read,
        phi_3_4_1_V_read,
        phi_3_5_0_V_read,
        phi_3_5_1_V_read,
        phi_3_6_0_V_read,
        phi_3_6_1_V_read,
        phi_3_7_0_V_read,
        phi_3_7_1_V_read,
        phi_3_8_0_V_read,
        phi_3_8_1_V_read,
        phi_4_0_0_V_read,
        phi_4_0_1_V_read,
        phi_4_1_0_V_read,
        phi_4_1_1_V_read,
        phi_4_2_0_V_read,
        phi_4_2_1_V_read,
        phi_4_3_0_V_read,
        phi_4_3_1_V_read,
        phi_4_4_0_V_read,
        phi_4_4_1_V_read,
        phi_4_5_0_V_read,
        phi_4_5_1_V_read,
        phi_4_6_0_V_read,
        phi_4_6_1_V_read,
        phi_4_7_0_V_read,
        phi_4_7_1_V_read,
        phi_4_8_0_V_read,
        phi_4_8_1_V_read,
        cpati_0_0_0_V_read,
        cpati_0_0_1_V_read,
        cpati_0_1_0_V_read,
        cpati_0_1_1_V_read,
        cpati_0_2_0_V_read,
        cpati_0_2_1_V_read,
        cpati_0_3_0_V_read,
        cpati_0_3_1_V_read,
        cpati_0_4_0_V_read,
        cpati_0_4_1_V_read,
        cpati_0_5_0_V_read,
        cpati_0_5_1_V_read,
        cpati_0_6_0_V_read,
        cpati_0_6_1_V_read,
        cpati_0_7_0_V_read,
        cpati_0_7_1_V_read,
        cpati_0_8_0_V_read,
        cpati_0_8_1_V_read,
        cpati_1_0_0_V_read,
        cpati_1_0_1_V_read,
        cpati_1_1_0_V_read,
        cpati_1_1_1_V_read,
        cpati_1_2_0_V_read,
        cpati_1_2_1_V_read,
        cpati_1_3_0_V_read,
        cpati_1_3_1_V_read,
        cpati_1_4_0_V_read,
        cpati_1_4_1_V_read,
        cpati_1_5_0_V_read,
        cpati_1_5_1_V_read,
        cpati_1_6_0_V_read,
        cpati_1_6_1_V_read,
        cpati_1_7_0_V_read,
        cpati_1_7_1_V_read,
        cpati_1_8_0_V_read,
        cpati_1_8_1_V_read,
        cpati_2_0_0_V_read,
        cpati_2_0_1_V_read,
        cpati_2_1_0_V_read,
        cpati_2_1_1_V_read,
        cpati_2_2_0_V_read,
        cpati_2_2_1_V_read,
        cpati_2_3_0_V_read,
        cpati_2_3_1_V_read,
        cpati_2_4_0_V_read,
        cpati_2_4_1_V_read,
        cpati_2_5_0_V_read,
        cpati_2_5_1_V_read,
        cpati_2_6_0_V_read,
        cpati_2_6_1_V_read,
        cpati_2_7_0_V_read,
        cpati_2_7_1_V_read,
        cpati_2_8_0_V_read,
        cpati_2_8_1_V_read,
        cpati_3_0_0_V_read,
        cpati_3_0_1_V_read,
        cpati_3_1_0_V_read,
        cpati_3_1_1_V_read,
        cpati_3_2_0_V_read,
        cpati_3_2_1_V_read,
        cpati_3_3_0_V_read,
        cpati_3_3_1_V_read,
        cpati_3_4_0_V_read,
        cpati_3_4_1_V_read,
        cpati_3_5_0_V_read,
        cpati_3_5_1_V_read,
        cpati_3_6_0_V_read,
        cpati_3_6_1_V_read,
        cpati_3_7_0_V_read,
        cpati_3_7_1_V_read,
        cpati_3_8_0_V_read,
        cpati_3_8_1_V_read,
        cpati_4_0_0_V_read,
        cpati_4_0_1_V_read,
        cpati_4_1_0_V_read,
        cpati_4_1_1_V_read,
        cpati_4_2_0_V_read,
        cpati_4_2_1_V_read,
        cpati_4_3_0_V_read,
        cpati_4_3_1_V_read,
        cpati_4_4_0_V_read,
        cpati_4_4_1_V_read,
        cpati_4_5_0_V_read,
        cpati_4_5_1_V_read,
        cpati_4_6_0_V_read,
        cpati_4_6_1_V_read,
        cpati_4_7_0_V_read,
        cpati_4_7_1_V_read,
        cpati_4_8_0_V_read,
        cpati_4_8_1_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37
);

parameter    ap_ST_pp0_stg0_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] phi_0_0_0_V_read;
input  [11:0] phi_0_0_1_V_read;
input  [11:0] phi_0_1_0_V_read;
input  [11:0] phi_0_1_1_V_read;
input  [11:0] phi_0_2_0_V_read;
input  [11:0] phi_0_2_1_V_read;
input  [11:0] phi_0_3_0_V_read;
input  [11:0] phi_0_3_1_V_read;
input  [11:0] phi_0_4_0_V_read;
input  [11:0] phi_0_4_1_V_read;
input  [11:0] phi_0_5_0_V_read;
input  [11:0] phi_0_5_1_V_read;
input  [11:0] phi_0_6_0_V_read;
input  [11:0] phi_0_6_1_V_read;
input  [11:0] phi_0_7_0_V_read;
input  [11:0] phi_0_7_1_V_read;
input  [11:0] phi_0_8_0_V_read;
input  [11:0] phi_0_8_1_V_read;
input  [11:0] phi_1_0_0_V_read;
input  [11:0] phi_1_0_1_V_read;
input  [11:0] phi_1_1_0_V_read;
input  [11:0] phi_1_1_1_V_read;
input  [11:0] phi_1_2_0_V_read;
input  [11:0] phi_1_2_1_V_read;
input  [11:0] phi_1_3_0_V_read;
input  [11:0] phi_1_3_1_V_read;
input  [11:0] phi_1_4_0_V_read;
input  [11:0] phi_1_4_1_V_read;
input  [11:0] phi_1_5_0_V_read;
input  [11:0] phi_1_5_1_V_read;
input  [11:0] phi_1_6_0_V_read;
input  [11:0] phi_1_6_1_V_read;
input  [11:0] phi_1_7_0_V_read;
input  [11:0] phi_1_7_1_V_read;
input  [11:0] phi_1_8_0_V_read;
input  [11:0] phi_1_8_1_V_read;
input  [11:0] phi_2_0_0_V_read;
input  [11:0] phi_2_0_1_V_read;
input  [11:0] phi_2_1_0_V_read;
input  [11:0] phi_2_1_1_V_read;
input  [11:0] phi_2_2_0_V_read;
input  [11:0] phi_2_2_1_V_read;
input  [11:0] phi_2_3_0_V_read;
input  [11:0] phi_2_3_1_V_read;
input  [11:0] phi_2_4_0_V_read;
input  [11:0] phi_2_4_1_V_read;
input  [11:0] phi_2_5_0_V_read;
input  [11:0] phi_2_5_1_V_read;
input  [11:0] phi_2_6_0_V_read;
input  [11:0] phi_2_6_1_V_read;
input  [11:0] phi_2_7_0_V_read;
input  [11:0] phi_2_7_1_V_read;
input  [11:0] phi_2_8_0_V_read;
input  [11:0] phi_2_8_1_V_read;
input  [11:0] phi_3_0_0_V_read;
input  [11:0] phi_3_0_1_V_read;
input  [11:0] phi_3_1_0_V_read;
input  [11:0] phi_3_1_1_V_read;
input  [11:0] phi_3_2_0_V_read;
input  [11:0] phi_3_2_1_V_read;
input  [11:0] phi_3_3_0_V_read;
input  [11:0] phi_3_3_1_V_read;
input  [11:0] phi_3_4_0_V_read;
input  [11:0] phi_3_4_1_V_read;
input  [11:0] phi_3_5_0_V_read;
input  [11:0] phi_3_5_1_V_read;
input  [11:0] phi_3_6_0_V_read;
input  [11:0] phi_3_6_1_V_read;
input  [11:0] phi_3_7_0_V_read;
input  [11:0] phi_3_7_1_V_read;
input  [11:0] phi_3_8_0_V_read;
input  [11:0] phi_3_8_1_V_read;
input  [11:0] phi_4_0_0_V_read;
input  [11:0] phi_4_0_1_V_read;
input  [11:0] phi_4_1_0_V_read;
input  [11:0] phi_4_1_1_V_read;
input  [11:0] phi_4_2_0_V_read;
input  [11:0] phi_4_2_1_V_read;
input  [11:0] phi_4_3_0_V_read;
input  [11:0] phi_4_3_1_V_read;
input  [11:0] phi_4_4_0_V_read;
input  [11:0] phi_4_4_1_V_read;
input  [11:0] phi_4_5_0_V_read;
input  [11:0] phi_4_5_1_V_read;
input  [11:0] phi_4_6_0_V_read;
input  [11:0] phi_4_6_1_V_read;
input  [11:0] phi_4_7_0_V_read;
input  [11:0] phi_4_7_1_V_read;
input  [11:0] phi_4_8_0_V_read;
input  [11:0] phi_4_8_1_V_read;
input  [3:0] cpati_0_0_0_V_read;
input  [3:0] cpati_0_0_1_V_read;
input  [3:0] cpati_0_1_0_V_read;
input  [3:0] cpati_0_1_1_V_read;
input  [3:0] cpati_0_2_0_V_read;
input  [3:0] cpati_0_2_1_V_read;
input  [3:0] cpati_0_3_0_V_read;
input  [3:0] cpati_0_3_1_V_read;
input  [3:0] cpati_0_4_0_V_read;
input  [3:0] cpati_0_4_1_V_read;
input  [3:0] cpati_0_5_0_V_read;
input  [3:0] cpati_0_5_1_V_read;
input  [3:0] cpati_0_6_0_V_read;
input  [3:0] cpati_0_6_1_V_read;
input  [3:0] cpati_0_7_0_V_read;
input  [3:0] cpati_0_7_1_V_read;
input  [3:0] cpati_0_8_0_V_read;
input  [3:0] cpati_0_8_1_V_read;
input  [3:0] cpati_1_0_0_V_read;
input  [3:0] cpati_1_0_1_V_read;
input  [3:0] cpati_1_1_0_V_read;
input  [3:0] cpati_1_1_1_V_read;
input  [3:0] cpati_1_2_0_V_read;
input  [3:0] cpati_1_2_1_V_read;
input  [3:0] cpati_1_3_0_V_read;
input  [3:0] cpati_1_3_1_V_read;
input  [3:0] cpati_1_4_0_V_read;
input  [3:0] cpati_1_4_1_V_read;
input  [3:0] cpati_1_5_0_V_read;
input  [3:0] cpati_1_5_1_V_read;
input  [3:0] cpati_1_6_0_V_read;
input  [3:0] cpati_1_6_1_V_read;
input  [3:0] cpati_1_7_0_V_read;
input  [3:0] cpati_1_7_1_V_read;
input  [3:0] cpati_1_8_0_V_read;
input  [3:0] cpati_1_8_1_V_read;
input  [3:0] cpati_2_0_0_V_read;
input  [3:0] cpati_2_0_1_V_read;
input  [3:0] cpati_2_1_0_V_read;
input  [3:0] cpati_2_1_1_V_read;
input  [3:0] cpati_2_2_0_V_read;
input  [3:0] cpati_2_2_1_V_read;
input  [3:0] cpati_2_3_0_V_read;
input  [3:0] cpati_2_3_1_V_read;
input  [3:0] cpati_2_4_0_V_read;
input  [3:0] cpati_2_4_1_V_read;
input  [3:0] cpati_2_5_0_V_read;
input  [3:0] cpati_2_5_1_V_read;
input  [3:0] cpati_2_6_0_V_read;
input  [3:0] cpati_2_6_1_V_read;
input  [3:0] cpati_2_7_0_V_read;
input  [3:0] cpati_2_7_1_V_read;
input  [3:0] cpati_2_8_0_V_read;
input  [3:0] cpati_2_8_1_V_read;
input  [3:0] cpati_3_0_0_V_read;
input  [3:0] cpati_3_0_1_V_read;
input  [3:0] cpati_3_1_0_V_read;
input  [3:0] cpati_3_1_1_V_read;
input  [3:0] cpati_3_2_0_V_read;
input  [3:0] cpati_3_2_1_V_read;
input  [3:0] cpati_3_3_0_V_read;
input  [3:0] cpati_3_3_1_V_read;
input  [3:0] cpati_3_4_0_V_read;
input  [3:0] cpati_3_4_1_V_read;
input  [3:0] cpati_3_5_0_V_read;
input  [3:0] cpati_3_5_1_V_read;
input  [3:0] cpati_3_6_0_V_read;
input  [3:0] cpati_3_6_1_V_read;
input  [3:0] cpati_3_7_0_V_read;
input  [3:0] cpati_3_7_1_V_read;
input  [3:0] cpati_3_8_0_V_read;
input  [3:0] cpati_3_8_1_V_read;
input  [3:0] cpati_4_0_0_V_read;
input  [3:0] cpati_4_0_1_V_read;
input  [3:0] cpati_4_1_0_V_read;
input  [3:0] cpati_4_1_1_V_read;
input  [3:0] cpati_4_2_0_V_read;
input  [3:0] cpati_4_2_1_V_read;
input  [3:0] cpati_4_3_0_V_read;
input  [3:0] cpati_4_3_1_V_read;
input  [3:0] cpati_4_4_0_V_read;
input  [3:0] cpati_4_4_1_V_read;
input  [3:0] cpati_4_5_0_V_read;
input  [3:0] cpati_4_5_1_V_read;
input  [3:0] cpati_4_6_0_V_read;
input  [3:0] cpati_4_6_1_V_read;
input  [3:0] cpati_4_7_0_V_read;
input  [3:0] cpati_4_7_1_V_read;
input  [3:0] cpati_4_8_0_V_read;
input  [3:0] cpati_4_8_1_V_read;
output  [11:0] ap_return_0;
output  [11:0] ap_return_1;
output  [11:0] ap_return_2;
output  [11:0] ap_return_3;
output  [11:0] ap_return_4;
output  [11:0] ap_return_5;
output  [11:0] ap_return_6;
output  [11:0] ap_return_7;
output  [11:0] ap_return_8;
output  [6:0] ap_return_9;
output  [6:0] ap_return_10;
output  [6:0] ap_return_11;
output  [6:0] ap_return_12;
output  [6:0] ap_return_13;
output  [6:0] ap_return_14;
output  [6:0] ap_return_15;
output  [6:0] ap_return_16;
output  [6:0] ap_return_17;
output  [6:0] ap_return_18;
output  [6:0] ap_return_19;
output  [6:0] ap_return_20;
output  [6:0] ap_return_21;
output  [6:0] ap_return_22;
output  [6:0] ap_return_23;
output  [6:0] ap_return_24;
output  [6:0] ap_return_25;
output  [6:0] ap_return_26;
output  [6:0] ap_return_27;
output  [6:0] ap_return_28;
output  [3:0] ap_return_29;
output  [3:0] ap_return_30;
output  [3:0] ap_return_31;
output  [3:0] ap_return_32;
output  [3:0] ap_return_33;
output  [3:0] ap_return_34;
output  [3:0] ap_return_35;
output  [3:0] ap_return_36;
output  [3:0] ap_return_37;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_0;
reg    ap_sig_18;
wire    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it3;
reg    grp_sp_co_ord_delay_actual_fu_2538_ap_start;
wire    grp_sp_co_ord_delay_actual_fu_2538_ap_done;
wire    grp_sp_co_ord_delay_actual_fu_2538_ap_idle;
wire    grp_sp_co_ord_delay_actual_fu_2538_ap_ready;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_0;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_1;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_2;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_3;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_4;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_5;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_6;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_7;
wire   [11:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_8;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_9;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_10;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_11;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_12;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_13;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_14;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_15;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_16;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_17;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_18;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_19;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_20;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_21;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_22;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_23;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_24;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_25;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_26;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_27;
wire   [6:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_28;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_29;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_30;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_31;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_32;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_33;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_34;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_35;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_36;
wire   [3:0] grp_sp_co_ord_delay_actual_fu_2538_ap_return_37;
reg   [0:0] ap_NS_fsm;
reg    ap_sig_grp_sp_co_ord_delay_actual_fu_2538_ap_start;
reg    ap_sig_pprstidle_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
end

sp_co_ord_delay_actual grp_sp_co_ord_delay_actual_fu_2538(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sp_co_ord_delay_actual_fu_2538_ap_start),
    .ap_done(grp_sp_co_ord_delay_actual_fu_2538_ap_done),
    .ap_idle(grp_sp_co_ord_delay_actual_fu_2538_ap_idle),
    .ap_ready(grp_sp_co_ord_delay_actual_fu_2538_ap_ready),
    .phi_0_0_0_V_read(phi_0_0_0_V_read),
    .phi_0_0_1_V_read(phi_0_0_1_V_read),
    .phi_0_1_0_V_read(phi_0_1_0_V_read),
    .phi_0_1_1_V_read(phi_0_1_1_V_read),
    .phi_0_2_0_V_read(phi_0_2_0_V_read),
    .phi_0_2_1_V_read(phi_0_2_1_V_read),
    .phi_0_3_0_V_read(phi_0_3_0_V_read),
    .phi_0_3_1_V_read(phi_0_3_1_V_read),
    .phi_0_4_0_V_read(phi_0_4_0_V_read),
    .phi_0_4_1_V_read(phi_0_4_1_V_read),
    .phi_0_5_0_V_read(phi_0_5_0_V_read),
    .phi_0_5_1_V_read(phi_0_5_1_V_read),
    .phi_0_6_0_V_read(phi_0_6_0_V_read),
    .phi_0_6_1_V_read(phi_0_6_1_V_read),
    .phi_0_7_0_V_read(phi_0_7_0_V_read),
    .phi_0_7_1_V_read(phi_0_7_1_V_read),
    .phi_0_8_0_V_read(phi_0_8_0_V_read),
    .phi_0_8_1_V_read(phi_0_8_1_V_read),
    .phi_1_0_0_V_read(phi_1_0_0_V_read),
    .phi_1_0_1_V_read(phi_1_0_1_V_read),
    .phi_1_1_0_V_read(phi_1_1_0_V_read),
    .phi_1_1_1_V_read(phi_1_1_1_V_read),
    .phi_1_2_0_V_read(phi_1_2_0_V_read),
    .phi_1_2_1_V_read(phi_1_2_1_V_read),
    .phi_1_3_0_V_read(phi_1_3_0_V_read),
    .phi_1_3_1_V_read(phi_1_3_1_V_read),
    .phi_1_4_0_V_read(phi_1_4_0_V_read),
    .phi_1_4_1_V_read(phi_1_4_1_V_read),
    .phi_1_5_0_V_read(phi_1_5_0_V_read),
    .phi_1_5_1_V_read(phi_1_5_1_V_read),
    .phi_1_6_0_V_read(phi_1_6_0_V_read),
    .phi_1_6_1_V_read(phi_1_6_1_V_read),
    .phi_1_7_0_V_read(phi_1_7_0_V_read),
    .phi_1_7_1_V_read(phi_1_7_1_V_read),
    .phi_1_8_0_V_read(phi_1_8_0_V_read),
    .phi_1_8_1_V_read(phi_1_8_1_V_read),
    .phi_2_0_0_V_read(phi_2_0_0_V_read),
    .phi_2_0_1_V_read(phi_2_0_1_V_read),
    .phi_2_1_0_V_read(phi_2_1_0_V_read),
    .phi_2_1_1_V_read(phi_2_1_1_V_read),
    .phi_2_2_0_V_read(phi_2_2_0_V_read),
    .phi_2_2_1_V_read(phi_2_2_1_V_read),
    .phi_2_3_0_V_read(phi_2_3_0_V_read),
    .phi_2_3_1_V_read(phi_2_3_1_V_read),
    .phi_2_4_0_V_read(phi_2_4_0_V_read),
    .phi_2_4_1_V_read(phi_2_4_1_V_read),
    .phi_2_5_0_V_read(phi_2_5_0_V_read),
    .phi_2_5_1_V_read(phi_2_5_1_V_read),
    .phi_2_6_0_V_read(phi_2_6_0_V_read),
    .phi_2_6_1_V_read(phi_2_6_1_V_read),
    .phi_2_7_0_V_read(phi_2_7_0_V_read),
    .phi_2_7_1_V_read(phi_2_7_1_V_read),
    .phi_2_8_0_V_read(phi_2_8_0_V_read),
    .phi_2_8_1_V_read(phi_2_8_1_V_read),
    .phi_3_0_0_V_read(phi_3_0_0_V_read),
    .phi_3_0_1_V_read(phi_3_0_1_V_read),
    .phi_3_1_0_V_read(phi_3_1_0_V_read),
    .phi_3_1_1_V_read(phi_3_1_1_V_read),
    .phi_3_2_0_V_read(phi_3_2_0_V_read),
    .phi_3_2_1_V_read(phi_3_2_1_V_read),
    .phi_3_3_0_V_read(phi_3_3_0_V_read),
    .phi_3_3_1_V_read(phi_3_3_1_V_read),
    .phi_3_4_0_V_read(phi_3_4_0_V_read),
    .phi_3_4_1_V_read(phi_3_4_1_V_read),
    .phi_3_5_0_V_read(phi_3_5_0_V_read),
    .phi_3_5_1_V_read(phi_3_5_1_V_read),
    .phi_3_6_0_V_read(phi_3_6_0_V_read),
    .phi_3_6_1_V_read(phi_3_6_1_V_read),
    .phi_3_7_0_V_read(phi_3_7_0_V_read),
    .phi_3_7_1_V_read(phi_3_7_1_V_read),
    .phi_3_8_0_V_read(phi_3_8_0_V_read),
    .phi_3_8_1_V_read(phi_3_8_1_V_read),
    .phi_4_0_0_V_read(phi_4_0_0_V_read),
    .phi_4_0_1_V_read(phi_4_0_1_V_read),
    .phi_4_1_0_V_read(phi_4_1_0_V_read),
    .phi_4_1_1_V_read(phi_4_1_1_V_read),
    .phi_4_2_0_V_read(phi_4_2_0_V_read),
    .phi_4_2_1_V_read(phi_4_2_1_V_read),
    .phi_4_3_0_V_read(phi_4_3_0_V_read),
    .phi_4_3_1_V_read(phi_4_3_1_V_read),
    .phi_4_4_0_V_read(phi_4_4_0_V_read),
    .phi_4_4_1_V_read(phi_4_4_1_V_read),
    .phi_4_5_0_V_read(phi_4_5_0_V_read),
    .phi_4_5_1_V_read(phi_4_5_1_V_read),
    .phi_4_6_0_V_read(phi_4_6_0_V_read),
    .phi_4_6_1_V_read(phi_4_6_1_V_read),
    .phi_4_7_0_V_read(phi_4_7_0_V_read),
    .phi_4_7_1_V_read(phi_4_7_1_V_read),
    .phi_4_8_0_V_read(phi_4_8_0_V_read),
    .phi_4_8_1_V_read(phi_4_8_1_V_read),
    .cpati_0_0_0_V_read(cpati_0_0_0_V_read),
    .cpati_0_0_1_V_read(cpati_0_0_1_V_read),
    .cpati_0_1_0_V_read(cpati_0_1_0_V_read),
    .cpati_0_1_1_V_read(cpati_0_1_1_V_read),
    .cpati_0_2_0_V_read(cpati_0_2_0_V_read),
    .cpati_0_2_1_V_read(cpati_0_2_1_V_read),
    .cpati_0_3_0_V_read(cpati_0_3_0_V_read),
    .cpati_0_3_1_V_read(cpati_0_3_1_V_read),
    .cpati_0_4_0_V_read(cpati_0_4_0_V_read),
    .cpati_0_4_1_V_read(cpati_0_4_1_V_read),
    .cpati_0_5_0_V_read(cpati_0_5_0_V_read),
    .cpati_0_5_1_V_read(cpati_0_5_1_V_read),
    .cpati_0_6_0_V_read(cpati_0_6_0_V_read),
    .cpati_0_6_1_V_read(cpati_0_6_1_V_read),
    .cpati_0_7_0_V_read(cpati_0_7_0_V_read),
    .cpati_0_7_1_V_read(cpati_0_7_1_V_read),
    .cpati_0_8_0_V_read(cpati_0_8_0_V_read),
    .cpati_0_8_1_V_read(cpati_0_8_1_V_read),
    .cpati_1_0_0_V_read(cpati_1_0_0_V_read),
    .cpati_1_0_1_V_read(cpati_1_0_1_V_read),
    .cpati_1_1_0_V_read(cpati_1_1_0_V_read),
    .cpati_1_1_1_V_read(cpati_1_1_1_V_read),
    .cpati_1_2_0_V_read(cpati_1_2_0_V_read),
    .cpati_1_2_1_V_read(cpati_1_2_1_V_read),
    .cpati_1_3_0_V_read(cpati_1_3_0_V_read),
    .cpati_1_3_1_V_read(cpati_1_3_1_V_read),
    .cpati_1_4_0_V_read(cpati_1_4_0_V_read),
    .cpati_1_4_1_V_read(cpati_1_4_1_V_read),
    .cpati_1_5_0_V_read(cpati_1_5_0_V_read),
    .cpati_1_5_1_V_read(cpati_1_5_1_V_read),
    .cpati_1_6_0_V_read(cpati_1_6_0_V_read),
    .cpati_1_6_1_V_read(cpati_1_6_1_V_read),
    .cpati_1_7_0_V_read(cpati_1_7_0_V_read),
    .cpati_1_7_1_V_read(cpati_1_7_1_V_read),
    .cpati_1_8_0_V_read(cpati_1_8_0_V_read),
    .cpati_1_8_1_V_read(cpati_1_8_1_V_read),
    .cpati_2_0_0_V_read(cpati_2_0_0_V_read),
    .cpati_2_0_1_V_read(cpati_2_0_1_V_read),
    .cpati_2_1_0_V_read(cpati_2_1_0_V_read),
    .cpati_2_1_1_V_read(cpati_2_1_1_V_read),
    .cpati_2_2_0_V_read(cpati_2_2_0_V_read),
    .cpati_2_2_1_V_read(cpati_2_2_1_V_read),
    .cpati_2_3_0_V_read(cpati_2_3_0_V_read),
    .cpati_2_3_1_V_read(cpati_2_3_1_V_read),
    .cpati_2_4_0_V_read(cpati_2_4_0_V_read),
    .cpati_2_4_1_V_read(cpati_2_4_1_V_read),
    .cpati_2_5_0_V_read(cpati_2_5_0_V_read),
    .cpati_2_5_1_V_read(cpati_2_5_1_V_read),
    .cpati_2_6_0_V_read(cpati_2_6_0_V_read),
    .cpati_2_6_1_V_read(cpati_2_6_1_V_read),
    .cpati_2_7_0_V_read(cpati_2_7_0_V_read),
    .cpati_2_7_1_V_read(cpati_2_7_1_V_read),
    .cpati_2_8_0_V_read(cpati_2_8_0_V_read),
    .cpati_2_8_1_V_read(cpati_2_8_1_V_read),
    .cpati_3_0_0_V_read(cpati_3_0_0_V_read),
    .cpati_3_0_1_V_read(cpati_3_0_1_V_read),
    .cpati_3_1_0_V_read(cpati_3_1_0_V_read),
    .cpati_3_1_1_V_read(cpati_3_1_1_V_read),
    .cpati_3_2_0_V_read(cpati_3_2_0_V_read),
    .cpati_3_2_1_V_read(cpati_3_2_1_V_read),
    .cpati_3_3_0_V_read(cpati_3_3_0_V_read),
    .cpati_3_3_1_V_read(cpati_3_3_1_V_read),
    .cpati_3_4_0_V_read(cpati_3_4_0_V_read),
    .cpati_3_4_1_V_read(cpati_3_4_1_V_read),
    .cpati_3_5_0_V_read(cpati_3_5_0_V_read),
    .cpati_3_5_1_V_read(cpati_3_5_1_V_read),
    .cpati_3_6_0_V_read(cpati_3_6_0_V_read),
    .cpati_3_6_1_V_read(cpati_3_6_1_V_read),
    .cpati_3_7_0_V_read(cpati_3_7_0_V_read),
    .cpati_3_7_1_V_read(cpati_3_7_1_V_read),
    .cpati_3_8_0_V_read(cpati_3_8_0_V_read),
    .cpati_3_8_1_V_read(cpati_3_8_1_V_read),
    .cpati_4_0_0_V_read(cpati_4_0_0_V_read),
    .cpati_4_0_1_V_read(cpati_4_0_1_V_read),
    .cpati_4_1_0_V_read(cpati_4_1_0_V_read),
    .cpati_4_1_1_V_read(cpati_4_1_1_V_read),
    .cpati_4_2_0_V_read(cpati_4_2_0_V_read),
    .cpati_4_2_1_V_read(cpati_4_2_1_V_read),
    .cpati_4_3_0_V_read(cpati_4_3_0_V_read),
    .cpati_4_3_1_V_read(cpati_4_3_1_V_read),
    .cpati_4_4_0_V_read(cpati_4_4_0_V_read),
    .cpati_4_4_1_V_read(cpati_4_4_1_V_read),
    .cpati_4_5_0_V_read(cpati_4_5_0_V_read),
    .cpati_4_5_1_V_read(cpati_4_5_1_V_read),
    .cpati_4_6_0_V_read(cpati_4_6_0_V_read),
    .cpati_4_6_1_V_read(cpati_4_6_1_V_read),
    .cpati_4_7_0_V_read(cpati_4_7_0_V_read),
    .cpati_4_7_1_V_read(cpati_4_7_1_V_read),
    .cpati_4_8_0_V_read(cpati_4_8_0_V_read),
    .cpati_4_8_1_V_read(cpati_4_8_1_V_read),
    .ap_return_0(grp_sp_co_ord_delay_actual_fu_2538_ap_return_0),
    .ap_return_1(grp_sp_co_ord_delay_actual_fu_2538_ap_return_1),
    .ap_return_2(grp_sp_co_ord_delay_actual_fu_2538_ap_return_2),
    .ap_return_3(grp_sp_co_ord_delay_actual_fu_2538_ap_return_3),
    .ap_return_4(grp_sp_co_ord_delay_actual_fu_2538_ap_return_4),
    .ap_return_5(grp_sp_co_ord_delay_actual_fu_2538_ap_return_5),
    .ap_return_6(grp_sp_co_ord_delay_actual_fu_2538_ap_return_6),
    .ap_return_7(grp_sp_co_ord_delay_actual_fu_2538_ap_return_7),
    .ap_return_8(grp_sp_co_ord_delay_actual_fu_2538_ap_return_8),
    .ap_return_9(grp_sp_co_ord_delay_actual_fu_2538_ap_return_9),
    .ap_return_10(grp_sp_co_ord_delay_actual_fu_2538_ap_return_10),
    .ap_return_11(grp_sp_co_ord_delay_actual_fu_2538_ap_return_11),
    .ap_return_12(grp_sp_co_ord_delay_actual_fu_2538_ap_return_12),
    .ap_return_13(grp_sp_co_ord_delay_actual_fu_2538_ap_return_13),
    .ap_return_14(grp_sp_co_ord_delay_actual_fu_2538_ap_return_14),
    .ap_return_15(grp_sp_co_ord_delay_actual_fu_2538_ap_return_15),
    .ap_return_16(grp_sp_co_ord_delay_actual_fu_2538_ap_return_16),
    .ap_return_17(grp_sp_co_ord_delay_actual_fu_2538_ap_return_17),
    .ap_return_18(grp_sp_co_ord_delay_actual_fu_2538_ap_return_18),
    .ap_return_19(grp_sp_co_ord_delay_actual_fu_2538_ap_return_19),
    .ap_return_20(grp_sp_co_ord_delay_actual_fu_2538_ap_return_20),
    .ap_return_21(grp_sp_co_ord_delay_actual_fu_2538_ap_return_21),
    .ap_return_22(grp_sp_co_ord_delay_actual_fu_2538_ap_return_22),
    .ap_return_23(grp_sp_co_ord_delay_actual_fu_2538_ap_return_23),
    .ap_return_24(grp_sp_co_ord_delay_actual_fu_2538_ap_return_24),
    .ap_return_25(grp_sp_co_ord_delay_actual_fu_2538_ap_return_25),
    .ap_return_26(grp_sp_co_ord_delay_actual_fu_2538_ap_return_26),
    .ap_return_27(grp_sp_co_ord_delay_actual_fu_2538_ap_return_27),
    .ap_return_28(grp_sp_co_ord_delay_actual_fu_2538_ap_return_28),
    .ap_return_29(grp_sp_co_ord_delay_actual_fu_2538_ap_return_29),
    .ap_return_30(grp_sp_co_ord_delay_actual_fu_2538_ap_return_30),
    .ap_return_31(grp_sp_co_ord_delay_actual_fu_2538_ap_return_31),
    .ap_return_32(grp_sp_co_ord_delay_actual_fu_2538_ap_return_32),
    .ap_return_33(grp_sp_co_ord_delay_actual_fu_2538_ap_return_33),
    .ap_return_34(grp_sp_co_ord_delay_actual_fu_2538_ap_return_34),
    .ap_return_35(grp_sp_co_ord_delay_actual_fu_2538_ap_return_35),
    .ap_return_36(grp_sp_co_ord_delay_actual_fu_2538_ap_return_36),
    .ap_return_37(grp_sp_co_ord_delay_actual_fu_2538_ap_return_37)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if (~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0)) | ((1'b1 == ap_reg_ppiten_pp0_it3) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b0 == ap_reg_ppiten_pp0_it0) & (1'b0 == ap_reg_ppiten_pp0_it1) & (1'b0 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppiten_pp0_it3))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_18) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(ap_start == 1'b0))) begin
        ap_sig_grp_sp_co_ord_delay_actual_fu_2538_ap_start = 1'b1;
    end else begin
        ap_sig_grp_sp_co_ord_delay_actual_fu_2538_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_reg_ppiten_pp0_it0) & (1'b0 == ap_reg_ppiten_pp0_it1) & (1'b0 == ap_reg_ppiten_pp0_it2))) begin
        ap_sig_pprstidle_pp0 = 1'b1;
    end else begin
        ap_sig_pprstidle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_grp_sp_co_ord_delay_actual_fu_2538_ap_start)) begin
        grp_sp_co_ord_delay_actual_fu_2538_ap_start = ap_sig_grp_sp_co_ord_delay_actual_fu_2538_ap_start;
    end else begin
        grp_sp_co_ord_delay_actual_fu_2538_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_ppiten_pp0_it0 = ap_start;

assign ap_return_0 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_0;

assign ap_return_1 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_1;

assign ap_return_10 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_10;

assign ap_return_11 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_11;

assign ap_return_12 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_12;

assign ap_return_13 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_13;

assign ap_return_14 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_14;

assign ap_return_15 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_15;

assign ap_return_16 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_16;

assign ap_return_17 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_17;

assign ap_return_18 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_18;

assign ap_return_19 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_19;

assign ap_return_2 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_2;

assign ap_return_20 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_20;

assign ap_return_21 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_21;

assign ap_return_22 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_22;

assign ap_return_23 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_23;

assign ap_return_24 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_24;

assign ap_return_25 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_25;

assign ap_return_26 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_26;

assign ap_return_27 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_27;

assign ap_return_28 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_28;

assign ap_return_29 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_29;

assign ap_return_3 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_3;

assign ap_return_30 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_30;

assign ap_return_31 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_31;

assign ap_return_32 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_32;

assign ap_return_33 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_33;

assign ap_return_34 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_34;

assign ap_return_35 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_35;

assign ap_return_36 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_36;

assign ap_return_37 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_37;

assign ap_return_4 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_4;

assign ap_return_5 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_5;

assign ap_return_6 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_6;

assign ap_return_7 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_7;

assign ap_return_8 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_8;

assign ap_return_9 = grp_sp_co_ord_delay_actual_fu_2538_ap_return_9;

always @ (*) begin
    ap_sig_18 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

endmodule //sp_co_ord_delay
