// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sp_deltas_m1 (
        ph_match_0_V_read,
        ph_match_1_V_read,
        ph_match_2_V_read,
        ph_match_3_V_read,
        th_match_1_0_V_read,
        th_match_1_1_V_read,
        th_match_2_0_V_read,
        th_match_2_1_V_read,
        th_match_3_0_V_read,
        th_match_3_1_V_read,
        th_match11_0_V_read,
        th_match11_1_V_read,
        th_match11_2_V_read,
        th_match11_3_V_read,
        cpat_match_0_V_read,
        cpat_match_1_V_read,
        cpat_match_2_V_read,
        cpat_match_3_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20
);

parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv7_5 = 7'b101;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv7_4 = 7'b100;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_1 = 4'b1;

input  [11:0] ph_match_0_V_read;
input  [11:0] ph_match_1_V_read;
input  [11:0] ph_match_2_V_read;
input  [11:0] ph_match_3_V_read;
input  [6:0] th_match_1_0_V_read;
input  [6:0] th_match_1_1_V_read;
input  [6:0] th_match_2_0_V_read;
input  [6:0] th_match_2_1_V_read;
input  [6:0] th_match_3_0_V_read;
input  [6:0] th_match_3_1_V_read;
input  [6:0] th_match11_0_V_read;
input  [6:0] th_match11_1_V_read;
input  [6:0] th_match11_2_V_read;
input  [6:0] th_match11_3_V_read;
input  [3:0] cpat_match_0_V_read;
input  [3:0] cpat_match_1_V_read;
input  [3:0] cpat_match_2_V_read;
input  [3:0] cpat_match_3_V_read;
output  [11:0] ap_return_0;
output  [6:0] ap_return_1;
output  [5:0] ap_return_2;
output  [5:0] ap_return_3;
output  [6:0] ap_return_4;
output  [3:0] ap_return_5;
output  [3:0] ap_return_6;
output  [3:0] ap_return_7;
output  [3:0] ap_return_8;
output  [11:0] ap_return_9;
output  [11:0] ap_return_10;
output  [11:0] ap_return_11;
output  [11:0] ap_return_12;
output  [11:0] ap_return_13;
output  [11:0] ap_return_14;
output  [6:0] ap_return_15;
output  [6:0] ap_return_16;
output  [6:0] ap_return_17;
output  [6:0] ap_return_18;
output  [6:0] ap_return_19;
output  [6:0] ap_return_20;

wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_0_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_1_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_2_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_3_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_4_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_5_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_6_V_read;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_dth_7_V_read;
wire   [7:0] call_ret212_sp_best_delta_seg1_fu_238_sth_V;
wire   [6:0] call_ret212_sp_best_delta_seg1_fu_238_ap_return_0;
wire   [0:0] call_ret212_sp_best_delta_seg1_fu_238_ap_return_1;
wire   [0:0] call_ret212_sp_best_delta_seg1_fu_238_ap_return_2;
wire   [2:0] call_ret212_sp_best_delta_seg1_fu_238_ap_return_3;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_0_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_1_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_2_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_3_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_4_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_5_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_6_V_read;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_dth_7_V_read;
wire   [7:0] call_ret203_sp_best_delta_seg1_fu_253_sth_V;
wire   [6:0] call_ret203_sp_best_delta_seg1_fu_253_ap_return_0;
wire   [0:0] call_ret203_sp_best_delta_seg1_fu_253_ap_return_1;
wire   [0:0] call_ret203_sp_best_delta_seg1_fu_253_ap_return_2;
wire   [2:0] call_ret203_sp_best_delta_seg1_fu_253_ap_return_3;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_0_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_1_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_2_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_3_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_4_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_5_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_6_V_read;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_dth_7_V_read;
wire   [7:0] call_ret194_sp_best_delta_seg1_fu_268_sth_V;
wire   [6:0] call_ret194_sp_best_delta_seg1_fu_268_ap_return_0;
wire   [0:0] call_ret194_sp_best_delta_seg1_fu_268_ap_return_1;
wire   [0:0] call_ret194_sp_best_delta_seg1_fu_268_ap_return_2;
wire   [2:0] call_ret194_sp_best_delta_seg1_fu_268_ap_return_3;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_283_dth_0_V_read;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_283_dth_1_V_read;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_283_dth_2_V_read;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_283_dth_3_V_read;
wire   [3:0] call_ret185_sp_best_delta_seg_ch_fu_283_sth_V;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_0;
wire   [0:0] call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_1;
wire   [0:0] call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_2;
wire   [1:0] call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_3;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_294_dth_0_V_read;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_294_dth_1_V_read;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_294_dth_2_V_read;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_294_dth_3_V_read;
wire   [3:0] call_ret180_sp_best_delta_seg_ch_fu_294_sth_V;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_0;
wire   [0:0] call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_1;
wire   [0:0] call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_2;
wire   [1:0] call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_3;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_305_dth_0_V_read;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_305_dth_1_V_read;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_305_dth_2_V_read;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_305_dth_3_V_read;
wire   [3:0] call_ret_sp_best_delta_seg_ch_fu_305_sth_V;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_305_ap_return_0;
wire   [0:0] call_ret_sp_best_delta_seg_ch_fu_305_ap_return_1;
wire   [0:0] call_ret_sp_best_delta_seg_ch_fu_305_ap_return_2;
wire   [1:0] call_ret_sp_best_delta_seg_ch_fu_305_ap_return_3;
wire   [0:0] val_assign_fu_316_p2;
wire   [6:0] tmp_225_fu_322_p2;
wire   [6:0] tmp_226_fu_328_p2;
wire   [0:0] val_assign_0_0_0_1_fu_343_p2;
wire   [6:0] tmp_1042_0_0_0_1_fu_349_p2;
wire   [6:0] tmp_1043_0_0_0_1_fu_355_p2;
wire   [0:0] val_assign_0_0_1_fu_370_p2;
wire   [6:0] tmp_1042_0_0_1_fu_376_p2;
wire   [6:0] tmp_1043_0_0_1_fu_382_p2;
wire   [0:0] val_assign_0_0_1_1_fu_397_p2;
wire   [6:0] tmp_1042_0_0_1_1_fu_403_p2;
wire   [6:0] tmp_1043_0_0_1_1_fu_409_p2;
wire   [0:0] val_assign_0_0_2_fu_424_p2;
wire   [6:0] tmp_1042_0_0_2_fu_430_p2;
wire   [6:0] tmp_1043_0_0_2_fu_436_p2;
wire   [0:0] val_assign_0_0_2_1_fu_451_p2;
wire   [6:0] tmp_1042_0_0_2_1_fu_457_p2;
wire   [6:0] tmp_1043_0_0_2_1_fu_463_p2;
wire   [0:0] val_assign_0_0_3_fu_478_p2;
wire   [6:0] tmp_1042_0_0_3_fu_484_p2;
wire   [6:0] tmp_1043_0_0_3_fu_490_p2;
wire   [0:0] val_assign_0_0_3_1_fu_505_p2;
wire   [6:0] tmp_1042_0_0_3_1_fu_511_p2;
wire   [6:0] tmp_1043_0_0_3_1_fu_517_p2;
wire   [0:0] sph12_V_fu_553_p2;
wire   [11:0] tmp_227_fu_559_p2;
wire   [11:0] tmp_228_fu_565_p2;
wire   [0:0] val_assign_0_1_fu_579_p2;
wire   [6:0] tmp_1042_0_1_fu_585_p2;
wire   [6:0] tmp_1043_0_1_fu_591_p2;
wire   [0:0] val_assign_0_1_0_1_fu_606_p2;
wire   [6:0] tmp_1042_0_1_0_1_fu_612_p2;
wire   [6:0] tmp_1043_0_1_0_1_fu_618_p2;
wire   [0:0] val_assign_0_1_1_fu_633_p2;
wire   [6:0] tmp_1042_0_1_1_fu_639_p2;
wire   [6:0] tmp_1043_0_1_1_fu_645_p2;
wire   [0:0] val_assign_0_1_1_1_fu_660_p2;
wire   [6:0] tmp_1042_0_1_1_1_fu_666_p2;
wire   [6:0] tmp_1043_0_1_1_1_fu_672_p2;
wire   [0:0] val_assign_0_1_2_fu_687_p2;
wire   [6:0] tmp_1042_0_1_2_fu_693_p2;
wire   [6:0] tmp_1043_0_1_2_fu_699_p2;
wire   [0:0] val_assign_0_1_2_1_fu_714_p2;
wire   [6:0] tmp_1042_0_1_2_1_fu_720_p2;
wire   [6:0] tmp_1043_0_1_2_1_fu_726_p2;
wire   [0:0] val_assign_0_1_3_fu_741_p2;
wire   [6:0] tmp_1042_0_1_3_fu_747_p2;
wire   [6:0] tmp_1043_0_1_3_fu_753_p2;
wire   [0:0] val_assign_0_1_3_1_fu_768_p2;
wire   [6:0] tmp_1042_0_1_3_1_fu_774_p2;
wire   [6:0] tmp_1043_0_1_3_1_fu_780_p2;
wire   [0:0] sph12_V_0_1_fu_816_p2;
wire   [11:0] tmp_1037_0_1_fu_822_p2;
wire   [11:0] tmp_1038_0_1_fu_828_p2;
wire   [0:0] val_assign_0_2_fu_842_p2;
wire   [6:0] tmp_1042_0_2_fu_848_p2;
wire   [6:0] tmp_1043_0_2_fu_854_p2;
wire   [0:0] val_assign_0_2_0_1_fu_869_p2;
wire   [6:0] tmp_1042_0_2_0_1_fu_875_p2;
wire   [6:0] tmp_1043_0_2_0_1_fu_881_p2;
wire   [0:0] val_assign_0_2_1_fu_896_p2;
wire   [6:0] tmp_1042_0_2_1_fu_902_p2;
wire   [6:0] tmp_1043_0_2_1_fu_908_p2;
wire   [0:0] val_assign_0_2_1_1_fu_923_p2;
wire   [6:0] tmp_1042_0_2_1_1_fu_929_p2;
wire   [6:0] tmp_1043_0_2_1_1_fu_935_p2;
wire   [0:0] val_assign_0_2_2_fu_950_p2;
wire   [6:0] tmp_1042_0_2_2_fu_956_p2;
wire   [6:0] tmp_1043_0_2_2_fu_962_p2;
wire   [0:0] val_assign_0_2_2_1_fu_977_p2;
wire   [6:0] tmp_1042_0_2_2_1_fu_983_p2;
wire   [6:0] tmp_1043_0_2_2_1_fu_989_p2;
wire   [0:0] val_assign_0_2_3_fu_1004_p2;
wire   [6:0] tmp_1042_0_2_3_fu_1010_p2;
wire   [6:0] tmp_1043_0_2_3_fu_1016_p2;
wire   [0:0] val_assign_0_2_3_1_fu_1031_p2;
wire   [6:0] tmp_1042_0_2_3_1_fu_1037_p2;
wire   [6:0] tmp_1043_0_2_3_1_fu_1043_p2;
wire   [0:0] sph12_V_0_2_fu_1079_p2;
wire   [11:0] tmp_1037_0_2_fu_1085_p2;
wire   [11:0] tmp_1038_0_2_fu_1091_p2;
wire   [0:0] val_assign_1_fu_1105_p2;
wire   [6:0] tmp_1042_1_fu_1111_p2;
wire   [6:0] tmp_1043_1_fu_1117_p2;
wire   [0:0] val_assign_1_0_0_1_fu_1132_p2;
wire   [6:0] tmp_1042_1_0_0_1_fu_1138_p2;
wire   [6:0] tmp_1043_1_0_0_1_fu_1144_p2;
wire   [0:0] val_assign_1_0_1_fu_1159_p2;
wire   [6:0] tmp_1042_1_0_1_fu_1165_p2;
wire   [6:0] tmp_1043_1_0_1_fu_1171_p2;
wire   [0:0] val_assign_1_0_1_1_fu_1186_p2;
wire   [6:0] tmp_1042_1_0_1_1_fu_1192_p2;
wire   [6:0] tmp_1043_1_0_1_1_fu_1198_p2;
wire   [0:0] sph12_V_1_fu_1226_p2;
wire   [11:0] tmp_1037_1_fu_1232_p2;
wire   [11:0] tmp_1038_1_fu_1238_p2;
wire   [0:0] val_assign_1_1_fu_1252_p2;
wire   [6:0] tmp_1042_1_1_fu_1258_p2;
wire   [6:0] tmp_1043_1_1_fu_1264_p2;
wire   [0:0] val_assign_1_1_0_1_fu_1279_p2;
wire   [6:0] tmp_1042_1_1_0_1_fu_1285_p2;
wire   [6:0] tmp_1043_1_1_0_1_fu_1291_p2;
wire   [0:0] val_assign_1_1_1_fu_1306_p2;
wire   [6:0] tmp_1042_1_1_1_fu_1312_p2;
wire   [6:0] tmp_1043_1_1_1_fu_1318_p2;
wire   [0:0] val_assign_1_1_1_1_fu_1333_p2;
wire   [6:0] tmp_1042_1_1_1_1_fu_1339_p2;
wire   [6:0] tmp_1043_1_1_1_1_fu_1345_p2;
wire   [0:0] sph12_V_1_1_fu_1373_p2;
wire   [11:0] tmp_1037_1_1_fu_1379_p2;
wire   [11:0] tmp_1038_1_1_fu_1385_p2;
wire   [0:0] val_assign_2_fu_1399_p2;
wire   [6:0] tmp_1042_2_fu_1405_p2;
wire   [6:0] tmp_1043_2_fu_1411_p2;
wire   [0:0] val_assign_2_0_0_1_fu_1426_p2;
wire   [6:0] tmp_1042_2_0_0_1_fu_1432_p2;
wire   [6:0] tmp_1043_2_0_0_1_fu_1438_p2;
wire   [0:0] val_assign_2_0_1_fu_1453_p2;
wire   [6:0] tmp_1042_2_0_1_fu_1459_p2;
wire   [6:0] tmp_1043_2_0_1_fu_1465_p2;
wire   [0:0] val_assign_2_0_1_1_fu_1480_p2;
wire   [6:0] tmp_1042_2_0_1_1_fu_1486_p2;
wire   [6:0] tmp_1043_2_0_1_1_fu_1492_p2;
wire   [0:0] sph12_V_2_fu_1520_p2;
wire   [11:0] tmp_1037_2_fu_1526_p2;
wire   [11:0] tmp_1038_2_fu_1532_p2;
wire   [0:0] not_tmp_fu_1642_p2;
wire   [0:0] p_7_fu_1648_p2;
wire   [2:0] vmask1_V_fu_1668_p3;
wire   [2:0] p_7_cast_cast_fu_1654_p3;
wire   [0:0] tmp_s_fu_1662_p2;
wire   [2:0] p_0720_0_s_fu_1676_p3;
wire   [2:0] p_01414_1_fu_1684_p3;
wire   [2:0] tmp_52_fu_1702_p2;
wire   [3:0] vmask1_V_1_fu_1708_p3;
wire   [3:0] p_01414_1_cast_fu_1692_p1;
wire   [0:0] tmp_85_fu_1696_p2;
wire   [3:0] p_0695_0_01414_1_fu_1716_p3;
wire   [0:0] tmp_86_fu_1732_p2;
wire   [0:0] tmp_fu_1746_p2;
wire   [1:0] p_5_fu_1738_p3;
wire   [1:0] p_8_fu_1752_p3;
wire  signed [2:0] p_8_cast1_fu_1760_p1;
wire   [2:0] tmp_53_fu_1774_p2;
wire   [3:0] vmask2_V_fu_1780_p3;
wire   [3:0] p_8_cast_fu_1764_p1;
wire   [0:0] tmp_87_fu_1768_p2;
wire   [3:0] p_0645_0_s_fu_1788_p3;
wire   [0:0] tmp_88_fu_1804_p2;
wire   [0:0] tmp_199_fu_1818_p2;
wire   [2:0] p_6_fu_1810_p3;
wire   [2:0] rhs_V_1_fu_1824_p3;
wire   [3:0] rhs_V_fu_1796_p3;
wire   [3:0] vstat_V_fu_1724_p3;
wire   [3:0] r_V_fu_1836_p2;
wire   [0:0] tmp_89_fu_1842_p2;
wire   [0:0] tmp_90_fu_1848_p2;
wire   [0:0] or_cond_fu_1854_p2;
wire   [3:0] tmp_91_fu_1860_p3;
wire  signed [3:0] rhs_V_1_cast_fu_1832_p1;
wire   [3:0] vstat_V_1_fu_1868_p2;
wire   [3:0] r_V_1_fu_1874_p2;
wire   [0:0] tmp_92_fu_1880_p2;
wire   [0:0] tmp_93_fu_1886_p2;
wire   [0:0] or_cond2_fu_1892_p2;
wire   [2:0] tmp_94_fu_1898_p3;
wire  signed [3:0] tmp_94_cast_fu_1906_p1;
wire   [3:0] vstat_V_2_fu_1910_p2;
wire   [0:0] tmp_1117_fu_1964_p1;
wire   [1:0] tmp_229_fu_1968_p3;
wire   [3:0] a_theta_V_fu_1980_p9;
wire   [0:0] tmp_1119_fu_2010_p3;
wire   [1:0] tmp_230_fu_2018_p3;
wire   [3:0] a_theta_V_1_fu_2030_p9;
wire   [0:0] tmp_1120_fu_2052_p1;
wire   [2:0] tmp_231_fu_2056_p3;
wire   [3:0] a_theta_V_2_fu_2068_p9;
wire   [0:0] tmp_1121_fu_2090_p3;
wire   [1:0] tmp_232_fu_2098_p3;
wire   [3:0] a_theta_V_3_fu_2110_p9;
wire   [0:0] tmp_1122_fu_2132_p3;
wire   [2:0] tmp_233_fu_2140_p3;
wire   [3:0] a_theta_V_4_fu_2152_p9;
wire   [0:0] tmp_1123_fu_2174_p1;
wire   [2:0] tmp_234_fu_2178_p3;
wire   [3:0] a_theta_V_5_fu_2190_p9;
wire   [0:0] tmp_1115_fu_1948_p3;
wire   [0:0] tmp_1116_fu_1956_p3;
wire   [0:0] sel_tmp12_fu_2212_p2;
wire   [0:0] sel_tmp13_fu_2218_p2;
wire   [0:0] sel_tmp14_fu_2224_p2;
wire   [0:0] sel_tmp15_fu_2230_p2;
wire   [0:0] sel_tmp16_fu_2236_p2;
wire   [0:0] sel_tmp20_fu_2250_p2;
wire   [11:0] a_phi_V_fu_2242_p3;
wire   [0:0] sel_tmp24_demorgan_fu_2264_p2;
wire   [0:0] tmp_1118_fu_2002_p3;
wire   [0:0] sel_tmp24_fu_2270_p2;
wire   [0:0] sel_tmp25_fu_2276_p2;
wire   [0:0] sel_tmp26_fu_2282_p2;
wire   [11:0] a_phi_V_1_fu_2256_p3;
wire   [0:0] sel_tmp32_fu_2296_p2;
wire   [0:0] sel_tmp33_fu_2302_p2;
wire   [11:0] a_phi_V_2_fu_2288_p3;
wire   [0:0] sel_tmp39_demorgan_fu_2316_p2;
wire   [11:0] a_phi_V_3_fu_2308_p3;
wire   [0:0] sel_tmp45_fu_2330_p2;
wire   [0:0] sel_tmp46_fu_2336_p2;
wire   [11:0] a_phi_V_4_fu_2322_p3;
wire   [0:0] sel_tmp48_fu_2350_p2;
wire   [0:0] sel_tmp49_fu_2356_p2;
wire   [0:0] sel_tmp50_fu_2362_p2;
wire   [6:0] a_theta_V_1_fu_2030_p10;
wire   [0:0] sel_tmp54_fu_2376_p2;
wire   [0:0] tmp24_fu_2382_p2;
wire   [0:0] sel_tmp56_fu_2388_p2;
wire   [6:0] a_theta_V_3_fu_2110_p10;
wire   [6:0] a_theta_V_6_fu_2368_p3;
wire   [0:0] sel_tmp58_fu_2402_p2;
wire   [6:0] a_theta_V_fu_1980_p10;
wire   [6:0] a_theta_V_7_fu_2394_p3;
wire   [6:0] a_theta_V_4_fu_2152_p10;
wire   [6:0] a_theta_V_8_fu_2408_p3;
wire   [6:0] a_theta_V_2_fu_2068_p10;
wire   [6:0] a_theta_V_9_fu_2416_p3;
wire   [6:0] a_theta_V_5_fu_2190_p10;
wire   [6:0] a_theta_V_10_fu_2424_p3;
wire   [6:0] a_theta_V_11_fu_2432_p3;
wire   [6:0] a_theta_V_12_fu_2440_p3;
wire   [6:0] a_theta_V_13_fu_2448_p3;
wire   [0:0] tmp_1124_fu_2464_p1;
reg   [1:0] tmp_235_fu_2468_p4;
wire   [0:0] sel_tmp96_fu_2494_p2;
wire   [0:0] sel_tmp97_fu_2500_p2;
wire   [0:0] sel_tmp98_fu_2506_p2;
wire   [0:0] sel_tmp99_fu_2512_p2;
wire   [0:0] tmp26_fu_2524_p2;
wire   [0:0] tmp25_fu_2518_p2;
wire   [0:0] sel_tmp102_fu_2530_p2;
wire   [6:0] p_Result_123_fu_2478_p7;
wire   [11:0] a_phi_V_5_fu_2342_p3;
wire   [6:0] a_theta_V_14_fu_2456_p3;
wire   [5:0] p_Result_s_fu_1916_p7;
wire   [5:0] p_Result_122_fu_1932_p7;
wire   [6:0] ssdm_int_V_write_assign_fu_2536_p3;
wire   [11:0] delta_ph_0_V_write_assign_fu_571_p3;
wire   [11:0] delta_ph_1_V_write_assign_fu_834_p3;
wire   [11:0] delta_ph_2_V_write_assign_fu_1097_p3;
wire   [11:0] delta_ph_3_V_write_assign_fu_1244_p3;
wire   [11:0] delta_ph_4_V_write_assign_fu_1391_p3;
wire   [11:0] delta_ph_5_V_write_assign_fu_1538_p3;

sp_best_delta_seg1 call_ret212_sp_best_delta_seg1_fu_238(
    .dth_0_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_0_V_read),
    .dth_1_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_1_V_read),
    .dth_2_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_2_V_read),
    .dth_3_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_3_V_read),
    .dth_4_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_4_V_read),
    .dth_5_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_5_V_read),
    .dth_6_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_6_V_read),
    .dth_7_V_read(call_ret212_sp_best_delta_seg1_fu_238_dth_7_V_read),
    .sth_V(call_ret212_sp_best_delta_seg1_fu_238_sth_V),
    .dvl_V(ap_const_lv8_0),
    .ap_return_0(call_ret212_sp_best_delta_seg1_fu_238_ap_return_0),
    .ap_return_1(call_ret212_sp_best_delta_seg1_fu_238_ap_return_1),
    .ap_return_2(call_ret212_sp_best_delta_seg1_fu_238_ap_return_2),
    .ap_return_3(call_ret212_sp_best_delta_seg1_fu_238_ap_return_3)
);

sp_best_delta_seg1 call_ret203_sp_best_delta_seg1_fu_253(
    .dth_0_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_0_V_read),
    .dth_1_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_1_V_read),
    .dth_2_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_2_V_read),
    .dth_3_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_3_V_read),
    .dth_4_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_4_V_read),
    .dth_5_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_5_V_read),
    .dth_6_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_6_V_read),
    .dth_7_V_read(call_ret203_sp_best_delta_seg1_fu_253_dth_7_V_read),
    .sth_V(call_ret203_sp_best_delta_seg1_fu_253_sth_V),
    .dvl_V(ap_const_lv8_0),
    .ap_return_0(call_ret203_sp_best_delta_seg1_fu_253_ap_return_0),
    .ap_return_1(call_ret203_sp_best_delta_seg1_fu_253_ap_return_1),
    .ap_return_2(call_ret203_sp_best_delta_seg1_fu_253_ap_return_2),
    .ap_return_3(call_ret203_sp_best_delta_seg1_fu_253_ap_return_3)
);

sp_best_delta_seg1 call_ret194_sp_best_delta_seg1_fu_268(
    .dth_0_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_0_V_read),
    .dth_1_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_1_V_read),
    .dth_2_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_2_V_read),
    .dth_3_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_3_V_read),
    .dth_4_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_4_V_read),
    .dth_5_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_5_V_read),
    .dth_6_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_6_V_read),
    .dth_7_V_read(call_ret194_sp_best_delta_seg1_fu_268_dth_7_V_read),
    .sth_V(call_ret194_sp_best_delta_seg1_fu_268_sth_V),
    .dvl_V(ap_const_lv8_0),
    .ap_return_0(call_ret194_sp_best_delta_seg1_fu_268_ap_return_0),
    .ap_return_1(call_ret194_sp_best_delta_seg1_fu_268_ap_return_1),
    .ap_return_2(call_ret194_sp_best_delta_seg1_fu_268_ap_return_2),
    .ap_return_3(call_ret194_sp_best_delta_seg1_fu_268_ap_return_3)
);

sp_best_delta_seg_ch call_ret185_sp_best_delta_seg_ch_fu_283(
    .dth_0_V_read(call_ret185_sp_best_delta_seg_ch_fu_283_dth_0_V_read),
    .dth_1_V_read(call_ret185_sp_best_delta_seg_ch_fu_283_dth_1_V_read),
    .dth_2_V_read(call_ret185_sp_best_delta_seg_ch_fu_283_dth_2_V_read),
    .dth_3_V_read(call_ret185_sp_best_delta_seg_ch_fu_283_dth_3_V_read),
    .sth_V(call_ret185_sp_best_delta_seg_ch_fu_283_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_0),
    .ap_return_1(call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_1),
    .ap_return_2(call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_2),
    .ap_return_3(call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_3)
);

sp_best_delta_seg_ch call_ret180_sp_best_delta_seg_ch_fu_294(
    .dth_0_V_read(call_ret180_sp_best_delta_seg_ch_fu_294_dth_0_V_read),
    .dth_1_V_read(call_ret180_sp_best_delta_seg_ch_fu_294_dth_1_V_read),
    .dth_2_V_read(call_ret180_sp_best_delta_seg_ch_fu_294_dth_2_V_read),
    .dth_3_V_read(call_ret180_sp_best_delta_seg_ch_fu_294_dth_3_V_read),
    .sth_V(call_ret180_sp_best_delta_seg_ch_fu_294_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_0),
    .ap_return_1(call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_1),
    .ap_return_2(call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_2),
    .ap_return_3(call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_3)
);

sp_best_delta_seg_ch call_ret_sp_best_delta_seg_ch_fu_305(
    .dth_0_V_read(call_ret_sp_best_delta_seg_ch_fu_305_dth_0_V_read),
    .dth_1_V_read(call_ret_sp_best_delta_seg_ch_fu_305_dth_1_V_read),
    .dth_2_V_read(call_ret_sp_best_delta_seg_ch_fu_305_dth_2_V_read),
    .dth_3_V_read(call_ret_sp_best_delta_seg_ch_fu_305_dth_3_V_read),
    .sth_V(call_ret_sp_best_delta_seg_ch_fu_305_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret_sp_best_delta_seg_ch_fu_305_ap_return_0),
    .ap_return_1(call_ret_sp_best_delta_seg_ch_fu_305_ap_return_1),
    .ap_return_2(call_ret_sp_best_delta_seg_ch_fu_305_ap_return_2),
    .ap_return_3(call_ret_sp_best_delta_seg_ch_fu_305_ap_return_3)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3441(
    .din1(ap_const_lv7_0),
    .din2(ap_const_lv7_0),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_fu_1980_p9),
    .dout(a_theta_V_fu_1980_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3442(
    .din1(ap_const_lv7_0),
    .din2(ap_const_lv7_0),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_1_fu_2030_p9),
    .dout(a_theta_V_1_fu_2030_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3443(
    .din1(ap_const_lv7_0),
    .din2(ap_const_lv7_0),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_2_fu_2068_p9),
    .dout(a_theta_V_2_fu_2068_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3444(
    .din1(ap_const_lv7_0),
    .din2(ap_const_lv7_0),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_3_fu_2110_p9),
    .dout(a_theta_V_3_fu_2110_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3445(
    .din1(ap_const_lv7_0),
    .din2(ap_const_lv7_0),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_4_fu_2152_p9),
    .dout(a_theta_V_4_fu_2152_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3446(
    .din1(ap_const_lv7_0),
    .din2(ap_const_lv7_0),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_5_fu_2190_p9),
    .dout(a_theta_V_5_fu_2190_p10)
);

assign a_phi_V_1_fu_2256_p3 = ((sel_tmp20_fu_2250_p2[0:0] === 1'b1) ? ph_match_2_V_read : a_phi_V_fu_2242_p3);

assign a_phi_V_2_fu_2288_p3 = ((sel_tmp26_fu_2282_p2[0:0] === 1'b1) ? ph_match_3_V_read : a_phi_V_1_fu_2256_p3);

assign a_phi_V_3_fu_2308_p3 = ((sel_tmp33_fu_2302_p2[0:0] === 1'b1) ? ph_match_2_V_read : a_phi_V_2_fu_2288_p3);

assign a_phi_V_4_fu_2322_p3 = ((sel_tmp39_demorgan_fu_2316_p2[0:0] === 1'b1) ? a_phi_V_3_fu_2308_p3 : ap_const_lv12_0);

assign a_phi_V_5_fu_2342_p3 = ((sel_tmp46_fu_2336_p2[0:0] === 1'b1) ? ph_match_3_V_read : a_phi_V_4_fu_2322_p3);

assign a_phi_V_fu_2242_p3 = ((sel_tmp16_fu_2236_p2[0:0] === 1'b1) ? ph_match_2_V_read : ph_match_1_V_read);

assign a_theta_V_10_fu_2424_p3 = ((sel_tmp20_fu_2250_p2[0:0] === 1'b1) ? a_theta_V_2_fu_2068_p10 : a_theta_V_9_fu_2416_p3);

assign a_theta_V_11_fu_2432_p3 = ((sel_tmp26_fu_2282_p2[0:0] === 1'b1) ? a_theta_V_5_fu_2190_p10 : a_theta_V_10_fu_2424_p3);

assign a_theta_V_12_fu_2440_p3 = ((sel_tmp33_fu_2302_p2[0:0] === 1'b1) ? ap_const_lv7_0 : a_theta_V_11_fu_2432_p3);

assign a_theta_V_13_fu_2448_p3 = ((sel_tmp39_demorgan_fu_2316_p2[0:0] === 1'b1) ? a_theta_V_12_fu_2440_p3 : ap_const_lv7_0);

assign a_theta_V_14_fu_2456_p3 = ((sel_tmp46_fu_2336_p2[0:0] === 1'b1) ? ap_const_lv7_0 : a_theta_V_13_fu_2448_p3);

assign a_theta_V_1_fu_2030_p9 = tmp_230_fu_2018_p3;

assign a_theta_V_2_fu_2068_p9 = tmp_231_fu_2056_p3;

assign a_theta_V_3_fu_2110_p9 = tmp_232_fu_2098_p3;

assign a_theta_V_4_fu_2152_p9 = tmp_233_fu_2140_p3;

assign a_theta_V_5_fu_2190_p9 = tmp_234_fu_2178_p3;

assign a_theta_V_6_fu_2368_p3 = ((sel_tmp50_fu_2362_p2[0:0] === 1'b1) ? a_theta_V_1_fu_2030_p10 : ap_const_lv7_0);

assign a_theta_V_7_fu_2394_p3 = ((sel_tmp56_fu_2388_p2[0:0] === 1'b1) ? a_theta_V_3_fu_2110_p10 : a_theta_V_6_fu_2368_p3);

assign a_theta_V_8_fu_2408_p3 = ((sel_tmp58_fu_2402_p2[0:0] === 1'b1) ? a_theta_V_fu_1980_p10 : a_theta_V_7_fu_2394_p3);

assign a_theta_V_9_fu_2416_p3 = ((sel_tmp16_fu_2236_p2[0:0] === 1'b1) ? a_theta_V_4_fu_2152_p10 : a_theta_V_8_fu_2408_p3);

assign a_theta_V_fu_1980_p9 = tmp_229_fu_1968_p3;

assign ap_return_0 = a_phi_V_5_fu_2342_p3;

assign ap_return_1 = a_theta_V_14_fu_2456_p3;

assign ap_return_10 = delta_ph_1_V_write_assign_fu_834_p3;

assign ap_return_11 = delta_ph_2_V_write_assign_fu_1097_p3;

assign ap_return_12 = delta_ph_3_V_write_assign_fu_1244_p3;

assign ap_return_13 = delta_ph_4_V_write_assign_fu_1391_p3;

assign ap_return_14 = delta_ph_5_V_write_assign_fu_1538_p3;

assign ap_return_15 = call_ret212_sp_best_delta_seg1_fu_238_ap_return_0;

assign ap_return_16 = call_ret203_sp_best_delta_seg1_fu_253_ap_return_0;

assign ap_return_17 = call_ret194_sp_best_delta_seg1_fu_268_ap_return_0;

assign ap_return_18 = call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_0;

assign ap_return_19 = call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_0;

assign ap_return_2 = p_Result_s_fu_1916_p7;

assign ap_return_20 = call_ret_sp_best_delta_seg_ch_fu_305_ap_return_0;

assign ap_return_3 = p_Result_122_fu_1932_p7;

assign ap_return_4 = ssdm_int_V_write_assign_fu_2536_p3;

assign ap_return_5 = cpat_match_0_V_read;

assign ap_return_6 = cpat_match_1_V_read;

assign ap_return_7 = cpat_match_2_V_read;

assign ap_return_8 = cpat_match_3_V_read;

assign ap_return_9 = delta_ph_0_V_write_assign_fu_571_p3;

assign call_ret180_sp_best_delta_seg_ch_fu_294_dth_0_V_read = ((val_assign_1_1_fu_1252_p2[0:0] === 1'b1) ? tmp_1042_1_1_fu_1258_p2 : tmp_1043_1_1_fu_1264_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_294_dth_1_V_read = ((val_assign_1_1_0_1_fu_1279_p2[0:0] === 1'b1) ? tmp_1042_1_1_0_1_fu_1285_p2 : tmp_1043_1_1_0_1_fu_1291_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_294_dth_2_V_read = ((val_assign_1_1_1_fu_1306_p2[0:0] === 1'b1) ? tmp_1042_1_1_1_fu_1312_p2 : tmp_1043_1_1_1_fu_1318_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_294_dth_3_V_read = ((val_assign_1_1_1_1_fu_1333_p2[0:0] === 1'b1) ? tmp_1042_1_1_1_1_fu_1339_p2 : tmp_1043_1_1_1_1_fu_1345_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_294_sth_V = {{{{val_assign_1_1_1_1_fu_1333_p2}, {val_assign_1_1_1_fu_1306_p2}}, {val_assign_1_1_0_1_fu_1279_p2}}, {val_assign_1_1_fu_1252_p2}};

assign call_ret185_sp_best_delta_seg_ch_fu_283_dth_0_V_read = ((val_assign_1_fu_1105_p2[0:0] === 1'b1) ? tmp_1042_1_fu_1111_p2 : tmp_1043_1_fu_1117_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_283_dth_1_V_read = ((val_assign_1_0_0_1_fu_1132_p2[0:0] === 1'b1) ? tmp_1042_1_0_0_1_fu_1138_p2 : tmp_1043_1_0_0_1_fu_1144_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_283_dth_2_V_read = ((val_assign_1_0_1_fu_1159_p2[0:0] === 1'b1) ? tmp_1042_1_0_1_fu_1165_p2 : tmp_1043_1_0_1_fu_1171_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_283_dth_3_V_read = ((val_assign_1_0_1_1_fu_1186_p2[0:0] === 1'b1) ? tmp_1042_1_0_1_1_fu_1192_p2 : tmp_1043_1_0_1_1_fu_1198_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_283_sth_V = {{{{val_assign_1_0_1_1_fu_1186_p2}, {val_assign_1_0_1_fu_1159_p2}}, {val_assign_1_0_0_1_fu_1132_p2}}, {val_assign_1_fu_1105_p2}};

assign call_ret194_sp_best_delta_seg1_fu_268_dth_0_V_read = ((val_assign_0_2_fu_842_p2[0:0] === 1'b1) ? tmp_1042_0_2_fu_848_p2 : tmp_1043_0_2_fu_854_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_1_V_read = ((val_assign_0_2_0_1_fu_869_p2[0:0] === 1'b1) ? tmp_1042_0_2_0_1_fu_875_p2 : tmp_1043_0_2_0_1_fu_881_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_2_V_read = ((val_assign_0_2_1_fu_896_p2[0:0] === 1'b1) ? tmp_1042_0_2_1_fu_902_p2 : tmp_1043_0_2_1_fu_908_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_3_V_read = ((val_assign_0_2_1_1_fu_923_p2[0:0] === 1'b1) ? tmp_1042_0_2_1_1_fu_929_p2 : tmp_1043_0_2_1_1_fu_935_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_4_V_read = ((val_assign_0_2_2_fu_950_p2[0:0] === 1'b1) ? tmp_1042_0_2_2_fu_956_p2 : tmp_1043_0_2_2_fu_962_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_5_V_read = ((val_assign_0_2_2_1_fu_977_p2[0:0] === 1'b1) ? tmp_1042_0_2_2_1_fu_983_p2 : tmp_1043_0_2_2_1_fu_989_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_6_V_read = ((val_assign_0_2_3_fu_1004_p2[0:0] === 1'b1) ? tmp_1042_0_2_3_fu_1010_p2 : tmp_1043_0_2_3_fu_1016_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_dth_7_V_read = ((val_assign_0_2_3_1_fu_1031_p2[0:0] === 1'b1) ? tmp_1042_0_2_3_1_fu_1037_p2 : tmp_1043_0_2_3_1_fu_1043_p2);

assign call_ret194_sp_best_delta_seg1_fu_268_sth_V = {{{{{{{{val_assign_0_2_3_1_fu_1031_p2}, {val_assign_0_2_3_fu_1004_p2}}, {val_assign_0_2_2_1_fu_977_p2}}, {val_assign_0_2_2_fu_950_p2}}, {val_assign_0_2_1_1_fu_923_p2}}, {val_assign_0_2_1_fu_896_p2}}, {val_assign_0_2_0_1_fu_869_p2}}, {val_assign_0_2_fu_842_p2}};

assign call_ret203_sp_best_delta_seg1_fu_253_dth_0_V_read = ((val_assign_0_1_fu_579_p2[0:0] === 1'b1) ? tmp_1042_0_1_fu_585_p2 : tmp_1043_0_1_fu_591_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_1_V_read = ((val_assign_0_1_0_1_fu_606_p2[0:0] === 1'b1) ? tmp_1042_0_1_0_1_fu_612_p2 : tmp_1043_0_1_0_1_fu_618_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_2_V_read = ((val_assign_0_1_1_fu_633_p2[0:0] === 1'b1) ? tmp_1042_0_1_1_fu_639_p2 : tmp_1043_0_1_1_fu_645_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_3_V_read = ((val_assign_0_1_1_1_fu_660_p2[0:0] === 1'b1) ? tmp_1042_0_1_1_1_fu_666_p2 : tmp_1043_0_1_1_1_fu_672_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_4_V_read = ((val_assign_0_1_2_fu_687_p2[0:0] === 1'b1) ? tmp_1042_0_1_2_fu_693_p2 : tmp_1043_0_1_2_fu_699_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_5_V_read = ((val_assign_0_1_2_1_fu_714_p2[0:0] === 1'b1) ? tmp_1042_0_1_2_1_fu_720_p2 : tmp_1043_0_1_2_1_fu_726_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_6_V_read = ((val_assign_0_1_3_fu_741_p2[0:0] === 1'b1) ? tmp_1042_0_1_3_fu_747_p2 : tmp_1043_0_1_3_fu_753_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_dth_7_V_read = ((val_assign_0_1_3_1_fu_768_p2[0:0] === 1'b1) ? tmp_1042_0_1_3_1_fu_774_p2 : tmp_1043_0_1_3_1_fu_780_p2);

assign call_ret203_sp_best_delta_seg1_fu_253_sth_V = {{{{{{{{val_assign_0_1_3_1_fu_768_p2}, {val_assign_0_1_3_fu_741_p2}}, {val_assign_0_1_2_1_fu_714_p2}}, {val_assign_0_1_2_fu_687_p2}}, {val_assign_0_1_1_1_fu_660_p2}}, {val_assign_0_1_1_fu_633_p2}}, {val_assign_0_1_0_1_fu_606_p2}}, {val_assign_0_1_fu_579_p2}};

assign call_ret212_sp_best_delta_seg1_fu_238_dth_0_V_read = ((val_assign_fu_316_p2[0:0] === 1'b1) ? tmp_225_fu_322_p2 : tmp_226_fu_328_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_1_V_read = ((val_assign_0_0_0_1_fu_343_p2[0:0] === 1'b1) ? tmp_1042_0_0_0_1_fu_349_p2 : tmp_1043_0_0_0_1_fu_355_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_2_V_read = ((val_assign_0_0_1_fu_370_p2[0:0] === 1'b1) ? tmp_1042_0_0_1_fu_376_p2 : tmp_1043_0_0_1_fu_382_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_3_V_read = ((val_assign_0_0_1_1_fu_397_p2[0:0] === 1'b1) ? tmp_1042_0_0_1_1_fu_403_p2 : tmp_1043_0_0_1_1_fu_409_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_4_V_read = ((val_assign_0_0_2_fu_424_p2[0:0] === 1'b1) ? tmp_1042_0_0_2_fu_430_p2 : tmp_1043_0_0_2_fu_436_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_5_V_read = ((val_assign_0_0_2_1_fu_451_p2[0:0] === 1'b1) ? tmp_1042_0_0_2_1_fu_457_p2 : tmp_1043_0_0_2_1_fu_463_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_6_V_read = ((val_assign_0_0_3_fu_478_p2[0:0] === 1'b1) ? tmp_1042_0_0_3_fu_484_p2 : tmp_1043_0_0_3_fu_490_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_dth_7_V_read = ((val_assign_0_0_3_1_fu_505_p2[0:0] === 1'b1) ? tmp_1042_0_0_3_1_fu_511_p2 : tmp_1043_0_0_3_1_fu_517_p2);

assign call_ret212_sp_best_delta_seg1_fu_238_sth_V = {{{{{{{{val_assign_0_0_3_1_fu_505_p2}, {val_assign_0_0_3_fu_478_p2}}, {val_assign_0_0_2_1_fu_451_p2}}, {val_assign_0_0_2_fu_424_p2}}, {val_assign_0_0_1_1_fu_397_p2}}, {val_assign_0_0_1_fu_370_p2}}, {val_assign_0_0_0_1_fu_343_p2}}, {val_assign_fu_316_p2}};

assign call_ret_sp_best_delta_seg_ch_fu_305_dth_0_V_read = ((val_assign_2_fu_1399_p2[0:0] === 1'b1) ? tmp_1042_2_fu_1405_p2 : tmp_1043_2_fu_1411_p2);

assign call_ret_sp_best_delta_seg_ch_fu_305_dth_1_V_read = ((val_assign_2_0_0_1_fu_1426_p2[0:0] === 1'b1) ? tmp_1042_2_0_0_1_fu_1432_p2 : tmp_1043_2_0_0_1_fu_1438_p2);

assign call_ret_sp_best_delta_seg_ch_fu_305_dth_2_V_read = ((val_assign_2_0_1_fu_1453_p2[0:0] === 1'b1) ? tmp_1042_2_0_1_fu_1459_p2 : tmp_1043_2_0_1_fu_1465_p2);

assign call_ret_sp_best_delta_seg_ch_fu_305_dth_3_V_read = ((val_assign_2_0_1_1_fu_1480_p2[0:0] === 1'b1) ? tmp_1042_2_0_1_1_fu_1486_p2 : tmp_1043_2_0_1_1_fu_1492_p2);

assign call_ret_sp_best_delta_seg_ch_fu_305_sth_V = {{{{val_assign_2_0_1_1_fu_1480_p2}, {val_assign_2_0_1_fu_1453_p2}}, {val_assign_2_0_0_1_fu_1426_p2}}, {val_assign_2_fu_1399_p2}};

assign delta_ph_0_V_write_assign_fu_571_p3 = ((sph12_V_fu_553_p2[0:0] === 1'b1) ? tmp_227_fu_559_p2 : tmp_228_fu_565_p2);

assign delta_ph_1_V_write_assign_fu_834_p3 = ((sph12_V_0_1_fu_816_p2[0:0] === 1'b1) ? tmp_1037_0_1_fu_822_p2 : tmp_1038_0_1_fu_828_p2);

assign delta_ph_2_V_write_assign_fu_1097_p3 = ((sph12_V_0_2_fu_1079_p2[0:0] === 1'b1) ? tmp_1037_0_2_fu_1085_p2 : tmp_1038_0_2_fu_1091_p2);

assign delta_ph_3_V_write_assign_fu_1244_p3 = ((sph12_V_1_fu_1226_p2[0:0] === 1'b1) ? tmp_1037_1_fu_1232_p2 : tmp_1038_1_fu_1238_p2);

assign delta_ph_4_V_write_assign_fu_1391_p3 = ((sph12_V_1_1_fu_1373_p2[0:0] === 1'b1) ? tmp_1037_1_1_fu_1379_p2 : tmp_1038_1_1_fu_1385_p2);

assign delta_ph_5_V_write_assign_fu_1538_p3 = ((sph12_V_2_fu_1520_p2[0:0] === 1'b1) ? tmp_1037_2_fu_1526_p2 : tmp_1038_2_fu_1532_p2);

assign not_tmp_fu_1642_p2 = ((call_ret212_sp_best_delta_seg1_fu_238_ap_return_0 < ap_const_lv7_5) ? 1'b1 : 1'b0);

assign or_cond2_fu_1892_p2 = (tmp_92_fu_1880_p2 | tmp_93_fu_1886_p2);

assign or_cond_fu_1854_p2 = (tmp_89_fu_1842_p2 | tmp_90_fu_1848_p2);

assign p_01414_1_cast_fu_1692_p1 = p_01414_1_fu_1684_p3;

assign p_01414_1_fu_1684_p3 = ((tmp_s_fu_1662_p2[0:0] === 1'b1) ? p_7_cast_cast_fu_1654_p3 : p_0720_0_s_fu_1676_p3);

assign p_0645_0_s_fu_1788_p3 = ((call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_2[0:0] === 1'b1) ? vmask2_V_fu_1780_p3 : p_8_cast_fu_1764_p1);

assign p_0695_0_01414_1_fu_1716_p3 = ((call_ret194_sp_best_delta_seg1_fu_268_ap_return_2[0:0] === 1'b1) ? vmask1_V_1_fu_1708_p3 : p_01414_1_cast_fu_1692_p1);

assign p_0720_0_s_fu_1676_p3 = ((call_ret203_sp_best_delta_seg1_fu_253_ap_return_2[0:0] === 1'b1) ? vmask1_V_fu_1668_p3 : p_7_cast_cast_fu_1654_p3);

assign p_5_fu_1738_p3 = ((tmp_86_fu_1732_p2[0:0] === 1'b1) ? ap_const_lv2_0 : ap_const_lv2_2);

assign p_6_fu_1810_p3 = ((tmp_88_fu_1804_p2[0:0] === 1'b1) ? ap_const_lv3_0 : ap_const_lv3_4);

assign p_7_cast_cast_fu_1654_p3 = ((p_7_fu_1648_p2[0:0] === 1'b1) ? ap_const_lv3_3 : ap_const_lv3_0);

assign p_7_fu_1648_p2 = (call_ret212_sp_best_delta_seg1_fu_238_ap_return_2 & not_tmp_fu_1642_p2);

assign p_8_cast1_fu_1760_p1 = $signed(p_8_fu_1752_p3);

assign p_8_cast_fu_1764_p1 = $unsigned(p_8_cast1_fu_1760_p1);

assign p_8_fu_1752_p3 = ((tmp_fu_1746_p2[0:0] === 1'b1) ? p_5_fu_1738_p3 : ap_const_lv2_0);

assign p_Result_122_fu_1932_p7 = {{{{{{call_ret_sp_best_delta_seg_ch_fu_305_ap_return_1}, {call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_1}}, {call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_1}}, {call_ret194_sp_best_delta_seg1_fu_268_ap_return_1}}, {call_ret203_sp_best_delta_seg1_fu_253_ap_return_1}}, {call_ret212_sp_best_delta_seg1_fu_238_ap_return_1}};

assign p_Result_123_fu_2478_p7 = {{{{{{{{{{1'b0}, {tmp_1124_fu_2464_p1}}}, {1'b0}}}, {tmp_1115_fu_1948_p3}}}, {1'b0}}}, {tmp_235_fu_2468_p4}};

assign p_Result_s_fu_1916_p7 = {{{{{{sph12_V_2_fu_1520_p2}, {sph12_V_1_1_fu_1373_p2}}, {sph12_V_1_fu_1226_p2}}, {sph12_V_0_2_fu_1079_p2}}, {sph12_V_0_1_fu_816_p2}}, {sph12_V_fu_553_p2}};

assign r_V_1_fu_1874_p2 = (rhs_V_1_cast_fu_1832_p1 & vstat_V_1_fu_1868_p2);

assign r_V_fu_1836_p2 = (rhs_V_fu_1796_p3 & vstat_V_fu_1724_p3);

assign rhs_V_1_cast_fu_1832_p1 = $signed(rhs_V_1_fu_1824_p3);

assign rhs_V_1_fu_1824_p3 = ((tmp_199_fu_1818_p2[0:0] === 1'b1) ? p_6_fu_1810_p3 : ap_const_lv3_0);

assign rhs_V_fu_1796_p3 = ((tmp_87_fu_1768_p2[0:0] === 1'b1) ? p_8_cast_fu_1764_p1 : p_0645_0_s_fu_1788_p3);

assign sel_tmp102_fu_2530_p2 = (tmp26_fu_2524_p2 | tmp25_fu_2518_p2);

assign sel_tmp12_fu_2212_p2 = (tmp_1115_fu_1948_p3 ^ 1'b1);

assign sel_tmp13_fu_2218_p2 = (tmp_1116_fu_1956_p3 & sel_tmp12_fu_2212_p2);

assign sel_tmp14_fu_2224_p2 = (call_ret203_sp_best_delta_seg1_fu_253_ap_return_2 ^ 1'b1);

assign sel_tmp15_fu_2230_p2 = (sel_tmp13_fu_2218_p2 & sel_tmp14_fu_2224_p2);

assign sel_tmp16_fu_2236_p2 = (sel_tmp15_fu_2230_p2 & call_ret_sp_best_delta_seg_ch_fu_305_ap_return_2);

assign sel_tmp20_fu_2250_p2 = (sel_tmp13_fu_2218_p2 & call_ret203_sp_best_delta_seg1_fu_253_ap_return_2);

assign sel_tmp24_demorgan_fu_2264_p2 = (tmp_1115_fu_1948_p3 | tmp_1116_fu_1956_p3);

assign sel_tmp24_fu_2270_p2 = (sel_tmp24_demorgan_fu_2264_p2 ^ 1'b1);

assign sel_tmp25_fu_2276_p2 = (tmp_1118_fu_2002_p3 & sel_tmp24_fu_2270_p2);

assign sel_tmp26_fu_2282_p2 = (sel_tmp25_fu_2276_p2 & call_ret194_sp_best_delta_seg1_fu_268_ap_return_2);

assign sel_tmp32_fu_2296_p2 = (call_ret_sp_best_delta_seg_ch_fu_305_ap_return_2 ^ 1'b1);

assign sel_tmp33_fu_2302_p2 = (sel_tmp15_fu_2230_p2 & sel_tmp32_fu_2296_p2);

assign sel_tmp39_demorgan_fu_2316_p2 = (sel_tmp24_demorgan_fu_2264_p2 | tmp_1118_fu_2002_p3);

assign sel_tmp45_fu_2330_p2 = (call_ret194_sp_best_delta_seg1_fu_268_ap_return_2 ^ 1'b1);

assign sel_tmp46_fu_2336_p2 = (sel_tmp25_fu_2276_p2 & sel_tmp45_fu_2330_p2);

assign sel_tmp48_fu_2350_p2 = (call_ret212_sp_best_delta_seg1_fu_238_ap_return_2 ^ 1'b1);

assign sel_tmp49_fu_2356_p2 = (tmp_1115_fu_1948_p3 & sel_tmp48_fu_2350_p2);

assign sel_tmp50_fu_2362_p2 = (sel_tmp49_fu_2356_p2 & call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_2);

assign sel_tmp54_fu_2376_p2 = (call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_2 ^ 1'b1);

assign sel_tmp56_fu_2388_p2 = (tmp24_fu_2382_p2 & sel_tmp49_fu_2356_p2);

assign sel_tmp58_fu_2402_p2 = (tmp_1115_fu_1948_p3 & call_ret212_sp_best_delta_seg1_fu_238_ap_return_2);

assign sel_tmp96_fu_2494_p2 = ((vstat_V_2_fu_1910_p2 == ap_const_lv4_4) ? 1'b1 : 1'b0);

assign sel_tmp97_fu_2500_p2 = ((vstat_V_2_fu_1910_p2 == ap_const_lv4_2) ? 1'b1 : 1'b0);

assign sel_tmp98_fu_2506_p2 = ((vstat_V_2_fu_1910_p2 == ap_const_lv4_1) ? 1'b1 : 1'b0);

assign sel_tmp99_fu_2512_p2 = ((vstat_V_2_fu_1910_p2 == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign sph12_V_0_1_fu_816_p2 = ((ph_match_0_V_read > ph_match_2_V_read) ? 1'b1 : 1'b0);

assign sph12_V_0_2_fu_1079_p2 = ((ph_match_0_V_read > ph_match_3_V_read) ? 1'b1 : 1'b0);

assign sph12_V_1_1_fu_1373_p2 = ((ph_match_1_V_read > ph_match_3_V_read) ? 1'b1 : 1'b0);

assign sph12_V_1_fu_1226_p2 = ((ph_match_1_V_read > ph_match_2_V_read) ? 1'b1 : 1'b0);

assign sph12_V_2_fu_1520_p2 = ((ph_match_2_V_read > ph_match_3_V_read) ? 1'b1 : 1'b0);

assign sph12_V_fu_553_p2 = ((ph_match_0_V_read > ph_match_1_V_read) ? 1'b1 : 1'b0);

assign ssdm_int_V_write_assign_fu_2536_p3 = ((sel_tmp102_fu_2530_p2[0:0] === 1'b1) ? ap_const_lv7_0 : p_Result_123_fu_2478_p7);

assign tmp24_fu_2382_p2 = (call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_2 & sel_tmp54_fu_2376_p2);

assign tmp25_fu_2518_p2 = (sel_tmp96_fu_2494_p2 | sel_tmp97_fu_2500_p2);

assign tmp26_fu_2524_p2 = (sel_tmp98_fu_2506_p2 | sel_tmp99_fu_2512_p2);

assign tmp_1037_0_1_fu_822_p2 = (ph_match_0_V_read - ph_match_2_V_read);

assign tmp_1037_0_2_fu_1085_p2 = (ph_match_0_V_read - ph_match_3_V_read);

assign tmp_1037_1_1_fu_1379_p2 = (ph_match_1_V_read - ph_match_3_V_read);

assign tmp_1037_1_fu_1232_p2 = (ph_match_1_V_read - ph_match_2_V_read);

assign tmp_1037_2_fu_1526_p2 = (ph_match_2_V_read - ph_match_3_V_read);

assign tmp_1038_0_1_fu_828_p2 = (ph_match_2_V_read - ph_match_0_V_read);

assign tmp_1038_0_2_fu_1091_p2 = (ph_match_3_V_read - ph_match_0_V_read);

assign tmp_1038_1_1_fu_1385_p2 = (ph_match_3_V_read - ph_match_1_V_read);

assign tmp_1038_1_fu_1238_p2 = (ph_match_2_V_read - ph_match_1_V_read);

assign tmp_1038_2_fu_1532_p2 = (ph_match_3_V_read - ph_match_2_V_read);

assign tmp_1042_0_0_0_1_fu_349_p2 = (th_match11_0_V_read - th_match_1_1_V_read);

assign tmp_1042_0_0_1_1_fu_403_p2 = (th_match11_1_V_read - th_match_1_1_V_read);

assign tmp_1042_0_0_1_fu_376_p2 = (th_match11_1_V_read - th_match_1_0_V_read);

assign tmp_1042_0_0_2_1_fu_457_p2 = (th_match11_2_V_read - th_match_1_1_V_read);

assign tmp_1042_0_0_2_fu_430_p2 = (th_match11_2_V_read - th_match_1_0_V_read);

assign tmp_1042_0_0_3_1_fu_511_p2 = (th_match11_3_V_read - th_match_1_1_V_read);

assign tmp_1042_0_0_3_fu_484_p2 = (th_match11_3_V_read - th_match_1_0_V_read);

assign tmp_1042_0_1_0_1_fu_612_p2 = (th_match11_0_V_read - th_match_2_1_V_read);

assign tmp_1042_0_1_1_1_fu_666_p2 = (th_match11_1_V_read - th_match_2_1_V_read);

assign tmp_1042_0_1_1_fu_639_p2 = (th_match11_1_V_read - th_match_2_0_V_read);

assign tmp_1042_0_1_2_1_fu_720_p2 = (th_match11_2_V_read - th_match_2_1_V_read);

assign tmp_1042_0_1_2_fu_693_p2 = (th_match11_2_V_read - th_match_2_0_V_read);

assign tmp_1042_0_1_3_1_fu_774_p2 = (th_match11_3_V_read - th_match_2_1_V_read);

assign tmp_1042_0_1_3_fu_747_p2 = (th_match11_3_V_read - th_match_2_0_V_read);

assign tmp_1042_0_1_fu_585_p2 = (th_match11_0_V_read - th_match_2_0_V_read);

assign tmp_1042_0_2_0_1_fu_875_p2 = (th_match11_0_V_read - th_match_3_1_V_read);

assign tmp_1042_0_2_1_1_fu_929_p2 = (th_match11_1_V_read - th_match_3_1_V_read);

assign tmp_1042_0_2_1_fu_902_p2 = (th_match11_1_V_read - th_match_3_0_V_read);

assign tmp_1042_0_2_2_1_fu_983_p2 = (th_match11_2_V_read - th_match_3_1_V_read);

assign tmp_1042_0_2_2_fu_956_p2 = (th_match11_2_V_read - th_match_3_0_V_read);

assign tmp_1042_0_2_3_1_fu_1037_p2 = (th_match11_3_V_read - th_match_3_1_V_read);

assign tmp_1042_0_2_3_fu_1010_p2 = (th_match11_3_V_read - th_match_3_0_V_read);

assign tmp_1042_0_2_fu_848_p2 = (th_match11_0_V_read - th_match_3_0_V_read);

assign tmp_1042_1_0_0_1_fu_1138_p2 = (th_match_1_0_V_read - th_match_2_1_V_read);

assign tmp_1042_1_0_1_1_fu_1192_p2 = (th_match_1_1_V_read - th_match_2_1_V_read);

assign tmp_1042_1_0_1_fu_1165_p2 = (th_match_1_1_V_read - th_match_2_0_V_read);

assign tmp_1042_1_1_0_1_fu_1285_p2 = (th_match_1_0_V_read - th_match_3_1_V_read);

assign tmp_1042_1_1_1_1_fu_1339_p2 = (th_match_1_1_V_read - th_match_3_1_V_read);

assign tmp_1042_1_1_1_fu_1312_p2 = (th_match_1_1_V_read - th_match_3_0_V_read);

assign tmp_1042_1_1_fu_1258_p2 = (th_match_1_0_V_read - th_match_3_0_V_read);

assign tmp_1042_1_fu_1111_p2 = (th_match_1_0_V_read - th_match_2_0_V_read);

assign tmp_1042_2_0_0_1_fu_1432_p2 = (th_match_2_0_V_read - th_match_3_1_V_read);

assign tmp_1042_2_0_1_1_fu_1486_p2 = (th_match_2_1_V_read - th_match_3_1_V_read);

assign tmp_1042_2_0_1_fu_1459_p2 = (th_match_2_1_V_read - th_match_3_0_V_read);

assign tmp_1042_2_fu_1405_p2 = (th_match_2_0_V_read - th_match_3_0_V_read);

assign tmp_1043_0_0_0_1_fu_355_p2 = (th_match_1_1_V_read - th_match11_0_V_read);

assign tmp_1043_0_0_1_1_fu_409_p2 = (th_match_1_1_V_read - th_match11_1_V_read);

assign tmp_1043_0_0_1_fu_382_p2 = (th_match_1_0_V_read - th_match11_1_V_read);

assign tmp_1043_0_0_2_1_fu_463_p2 = (th_match_1_1_V_read - th_match11_2_V_read);

assign tmp_1043_0_0_2_fu_436_p2 = (th_match_1_0_V_read - th_match11_2_V_read);

assign tmp_1043_0_0_3_1_fu_517_p2 = (th_match_1_1_V_read - th_match11_3_V_read);

assign tmp_1043_0_0_3_fu_490_p2 = (th_match_1_0_V_read - th_match11_3_V_read);

assign tmp_1043_0_1_0_1_fu_618_p2 = (th_match_2_1_V_read - th_match11_0_V_read);

assign tmp_1043_0_1_1_1_fu_672_p2 = (th_match_2_1_V_read - th_match11_1_V_read);

assign tmp_1043_0_1_1_fu_645_p2 = (th_match_2_0_V_read - th_match11_1_V_read);

assign tmp_1043_0_1_2_1_fu_726_p2 = (th_match_2_1_V_read - th_match11_2_V_read);

assign tmp_1043_0_1_2_fu_699_p2 = (th_match_2_0_V_read - th_match11_2_V_read);

assign tmp_1043_0_1_3_1_fu_780_p2 = (th_match_2_1_V_read - th_match11_3_V_read);

assign tmp_1043_0_1_3_fu_753_p2 = (th_match_2_0_V_read - th_match11_3_V_read);

assign tmp_1043_0_1_fu_591_p2 = (th_match_2_0_V_read - th_match11_0_V_read);

assign tmp_1043_0_2_0_1_fu_881_p2 = (th_match_3_1_V_read - th_match11_0_V_read);

assign tmp_1043_0_2_1_1_fu_935_p2 = (th_match_3_1_V_read - th_match11_1_V_read);

assign tmp_1043_0_2_1_fu_908_p2 = (th_match_3_0_V_read - th_match11_1_V_read);

assign tmp_1043_0_2_2_1_fu_989_p2 = (th_match_3_1_V_read - th_match11_2_V_read);

assign tmp_1043_0_2_2_fu_962_p2 = (th_match_3_0_V_read - th_match11_2_V_read);

assign tmp_1043_0_2_3_1_fu_1043_p2 = (th_match_3_1_V_read - th_match11_3_V_read);

assign tmp_1043_0_2_3_fu_1016_p2 = (th_match_3_0_V_read - th_match11_3_V_read);

assign tmp_1043_0_2_fu_854_p2 = (th_match_3_0_V_read - th_match11_0_V_read);

assign tmp_1043_1_0_0_1_fu_1144_p2 = (th_match_2_1_V_read - th_match_1_0_V_read);

assign tmp_1043_1_0_1_1_fu_1198_p2 = (th_match_2_1_V_read - th_match_1_1_V_read);

assign tmp_1043_1_0_1_fu_1171_p2 = (th_match_2_0_V_read - th_match_1_1_V_read);

assign tmp_1043_1_1_0_1_fu_1291_p2 = (th_match_3_1_V_read - th_match_1_0_V_read);

assign tmp_1043_1_1_1_1_fu_1345_p2 = (th_match_3_1_V_read - th_match_1_1_V_read);

assign tmp_1043_1_1_1_fu_1318_p2 = (th_match_3_0_V_read - th_match_1_1_V_read);

assign tmp_1043_1_1_fu_1264_p2 = (th_match_3_0_V_read - th_match_1_0_V_read);

assign tmp_1043_1_fu_1117_p2 = (th_match_2_0_V_read - th_match_1_0_V_read);

assign tmp_1043_2_0_0_1_fu_1438_p2 = (th_match_3_1_V_read - th_match_2_0_V_read);

assign tmp_1043_2_0_1_1_fu_1492_p2 = (th_match_3_1_V_read - th_match_2_1_V_read);

assign tmp_1043_2_0_1_fu_1465_p2 = (th_match_3_0_V_read - th_match_2_1_V_read);

assign tmp_1043_2_fu_1411_p2 = (th_match_3_0_V_read - th_match_2_0_V_read);

assign tmp_1115_fu_1948_p3 = vstat_V_2_fu_1910_p2[ap_const_lv32_1];

assign tmp_1116_fu_1956_p3 = vstat_V_2_fu_1910_p2[ap_const_lv32_2];

assign tmp_1117_fu_1964_p1 = call_ret212_sp_best_delta_seg1_fu_238_ap_return_3[0:0];

assign tmp_1118_fu_2002_p3 = vstat_V_2_fu_1910_p2[ap_const_lv32_3];

assign tmp_1119_fu_2010_p3 = call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_3[ap_const_lv32_1];

assign tmp_1120_fu_2052_p1 = call_ret203_sp_best_delta_seg1_fu_253_ap_return_3[0:0];

assign tmp_1121_fu_2090_p3 = call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_3[ap_const_lv32_1];

assign tmp_1122_fu_2132_p3 = call_ret_sp_best_delta_seg_ch_fu_305_ap_return_3[ap_const_lv32_1];

assign tmp_1123_fu_2174_p1 = call_ret194_sp_best_delta_seg1_fu_268_ap_return_3[0:0];

assign tmp_1124_fu_2464_p1 = vstat_V_1_fu_1868_p2[0:0];

assign tmp_199_fu_1818_p2 = (tmp_88_fu_1804_p2 | call_ret_sp_best_delta_seg_ch_fu_305_ap_return_2);

assign tmp_225_fu_322_p2 = (th_match11_0_V_read - th_match_1_0_V_read);

assign tmp_226_fu_328_p2 = (th_match_1_0_V_read - th_match11_0_V_read);

assign tmp_227_fu_559_p2 = (ph_match_0_V_read - ph_match_1_V_read);

assign tmp_228_fu_565_p2 = (ph_match_1_V_read - ph_match_0_V_read);

assign tmp_229_fu_1968_p3 = {{1'b1}, {tmp_1117_fu_1964_p1}};

assign tmp_230_fu_2018_p3 = {{1'b1}, {tmp_1119_fu_2010_p3}};

assign tmp_231_fu_2056_p3 = {{ap_const_lv2_2}, {tmp_1120_fu_2052_p1}};

assign tmp_232_fu_2098_p3 = {{1'b1}, {tmp_1121_fu_2090_p3}};

assign tmp_233_fu_2140_p3 = {{ap_const_lv2_2}, {tmp_1122_fu_2132_p3}};

assign tmp_234_fu_2178_p3 = {{ap_const_lv2_3}, {tmp_1123_fu_2174_p1}};

integer ap_tvar_int_0;

always @ (vstat_V_2_fu_1910_p2) begin
    for (ap_tvar_int_0 = 2 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > ap_const_lv32_3 - ap_const_lv32_2) begin
            tmp_235_fu_2468_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_235_fu_2468_p4[ap_tvar_int_0] = vstat_V_2_fu_1910_p2[ap_const_lv32_3 - ap_tvar_int_0];
        end
    end
end

assign tmp_52_fu_1702_p2 = (p_01414_1_fu_1684_p3 | ap_const_lv3_1);

assign tmp_53_fu_1774_p2 = (p_8_cast1_fu_1760_p1 | ap_const_lv3_2);

assign tmp_85_fu_1696_p2 = ((call_ret194_sp_best_delta_seg1_fu_268_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_86_fu_1732_p2 = ((call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_87_fu_1768_p2 = ((call_ret180_sp_best_delta_seg_ch_fu_294_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_88_fu_1804_p2 = ((call_ret_sp_best_delta_seg_ch_fu_305_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_89_fu_1842_p2 = ((r_V_fu_1836_p2 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_90_fu_1848_p2 = ((vstat_V_fu_1724_p3 == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_91_fu_1860_p3 = ((or_cond_fu_1854_p2[0:0] === 1'b1) ? rhs_V_fu_1796_p3 : ap_const_lv4_0);

assign tmp_92_fu_1880_p2 = ((r_V_1_fu_1874_p2 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_93_fu_1886_p2 = ((vstat_V_1_fu_1868_p2 == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_94_cast_fu_1906_p1 = $signed(tmp_94_fu_1898_p3);

assign tmp_94_fu_1898_p3 = ((or_cond2_fu_1892_p2[0:0] === 1'b1) ? rhs_V_1_fu_1824_p3 : ap_const_lv3_0);

assign tmp_fu_1746_p2 = (tmp_86_fu_1732_p2 | call_ret185_sp_best_delta_seg_ch_fu_283_ap_return_2);

assign tmp_s_fu_1662_p2 = ((call_ret203_sp_best_delta_seg1_fu_253_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign val_assign_0_0_0_1_fu_343_p2 = ((th_match11_0_V_read > th_match_1_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_1_1_fu_397_p2 = ((th_match11_1_V_read > th_match_1_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_1_fu_370_p2 = ((th_match11_1_V_read > th_match_1_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_2_1_fu_451_p2 = ((th_match11_2_V_read > th_match_1_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_2_fu_424_p2 = ((th_match11_2_V_read > th_match_1_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_3_1_fu_505_p2 = ((th_match11_3_V_read > th_match_1_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_3_fu_478_p2 = ((th_match11_3_V_read > th_match_1_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_0_1_fu_606_p2 = ((th_match11_0_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_1_1_fu_660_p2 = ((th_match11_1_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_1_fu_633_p2 = ((th_match11_1_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_2_1_fu_714_p2 = ((th_match11_2_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_2_fu_687_p2 = ((th_match11_2_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_3_1_fu_768_p2 = ((th_match11_3_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_3_fu_741_p2 = ((th_match11_3_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_fu_579_p2 = ((th_match11_0_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_0_1_fu_869_p2 = ((th_match11_0_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_1_1_fu_923_p2 = ((th_match11_1_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_1_fu_896_p2 = ((th_match11_1_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_2_1_fu_977_p2 = ((th_match11_2_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_2_fu_950_p2 = ((th_match11_2_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_3_1_fu_1031_p2 = ((th_match11_3_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_3_fu_1004_p2 = ((th_match11_3_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_fu_842_p2 = ((th_match11_0_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_0_0_1_fu_1132_p2 = ((th_match_1_0_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_0_1_1_fu_1186_p2 = ((th_match_1_1_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_0_1_fu_1159_p2 = ((th_match_1_1_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_0_1_fu_1279_p2 = ((th_match_1_0_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_1_1_fu_1333_p2 = ((th_match_1_1_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_1_fu_1306_p2 = ((th_match_1_1_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_fu_1252_p2 = ((th_match_1_0_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_fu_1105_p2 = ((th_match_1_0_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_0_0_1_fu_1426_p2 = ((th_match_2_0_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_0_1_1_fu_1480_p2 = ((th_match_2_1_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_0_1_fu_1453_p2 = ((th_match_2_1_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_fu_1399_p2 = ((th_match_2_0_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_fu_316_p2 = ((th_match11_0_V_read > th_match_1_0_V_read) ? 1'b1 : 1'b0);

assign vmask1_V_1_fu_1708_p3 = {{1'b1}, {tmp_52_fu_1702_p2}};

assign vmask1_V_fu_1668_p3 = ((p_7_fu_1648_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_5);

assign vmask2_V_fu_1780_p3 = {{1'b1}, {tmp_53_fu_1774_p2}};

assign vstat_V_1_fu_1868_p2 = (tmp_91_fu_1860_p3 | vstat_V_fu_1724_p3);

assign vstat_V_2_fu_1910_p2 = (tmp_94_cast_fu_1906_p1 | vstat_V_1_fu_1868_p2);

assign vstat_V_fu_1724_p3 = ((tmp_85_fu_1696_p2[0:0] === 1'b1) ? p_01414_1_cast_fu_1692_p1 : p_0695_0_01414_1_fu_1716_p3);

endmodule //sp_deltas_m1
