// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sp_deltas_m0 (
        ph_match_0_V_read,
        ph_match_1_V_read,
        ph_match_2_V_read,
        ph_match_3_V_read,
        th_match_0_0_V_read,
        th_match_0_1_V_read,
        th_match_1_0_V_read,
        th_match_1_1_V_read,
        th_match_2_0_V_read,
        th_match_2_1_V_read,
        th_match_3_0_V_read,
        th_match_3_1_V_read,
        cpat_match_0_V_read,
        cpat_match_1_V_read,
        cpat_match_2_V_read,
        cpat_match_3_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20
);

parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv7_5 = 7'b101;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv7_4 = 7'b100;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_1 = 4'b1;

input  [11:0] ph_match_0_V_read;
input  [11:0] ph_match_1_V_read;
input  [11:0] ph_match_2_V_read;
input  [11:0] ph_match_3_V_read;
input  [6:0] th_match_0_0_V_read;
input  [6:0] th_match_0_1_V_read;
input  [6:0] th_match_1_0_V_read;
input  [6:0] th_match_1_1_V_read;
input  [6:0] th_match_2_0_V_read;
input  [6:0] th_match_2_1_V_read;
input  [6:0] th_match_3_0_V_read;
input  [6:0] th_match_3_1_V_read;
input  [3:0] cpat_match_0_V_read;
input  [3:0] cpat_match_1_V_read;
input  [3:0] cpat_match_2_V_read;
input  [3:0] cpat_match_3_V_read;
output  [11:0] ap_return_0;
output  [6:0] ap_return_1;
output  [5:0] ap_return_2;
output  [5:0] ap_return_3;
output  [6:0] ap_return_4;
output  [3:0] ap_return_5;
output  [3:0] ap_return_6;
output  [3:0] ap_return_7;
output  [3:0] ap_return_8;
output  [11:0] ap_return_9;
output  [11:0] ap_return_10;
output  [11:0] ap_return_11;
output  [11:0] ap_return_12;
output  [11:0] ap_return_13;
output  [11:0] ap_return_14;
output  [6:0] ap_return_15;
output  [6:0] ap_return_16;
output  [6:0] ap_return_17;
output  [6:0] ap_return_18;
output  [6:0] ap_return_19;
output  [6:0] ap_return_20;

wire   [6:0] call_ret200_sp_best_delta_seg_ch_fu_216_dth_0_V_read;
wire   [6:0] call_ret200_sp_best_delta_seg_ch_fu_216_dth_1_V_read;
wire   [6:0] call_ret200_sp_best_delta_seg_ch_fu_216_dth_2_V_read;
wire   [6:0] call_ret200_sp_best_delta_seg_ch_fu_216_dth_3_V_read;
wire   [3:0] call_ret200_sp_best_delta_seg_ch_fu_216_sth_V;
wire   [6:0] call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_0;
wire   [0:0] call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_1;
wire   [0:0] call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_2;
wire   [1:0] call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_3;
wire   [6:0] call_ret195_sp_best_delta_seg_ch_fu_227_dth_0_V_read;
wire   [6:0] call_ret195_sp_best_delta_seg_ch_fu_227_dth_1_V_read;
wire   [6:0] call_ret195_sp_best_delta_seg_ch_fu_227_dth_2_V_read;
wire   [6:0] call_ret195_sp_best_delta_seg_ch_fu_227_dth_3_V_read;
wire   [3:0] call_ret195_sp_best_delta_seg_ch_fu_227_sth_V;
wire   [6:0] call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_0;
wire   [0:0] call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_1;
wire   [0:0] call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_2;
wire   [1:0] call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_3;
wire   [6:0] call_ret190_sp_best_delta_seg_ch_fu_238_dth_0_V_read;
wire   [6:0] call_ret190_sp_best_delta_seg_ch_fu_238_dth_1_V_read;
wire   [6:0] call_ret190_sp_best_delta_seg_ch_fu_238_dth_2_V_read;
wire   [6:0] call_ret190_sp_best_delta_seg_ch_fu_238_dth_3_V_read;
wire   [3:0] call_ret190_sp_best_delta_seg_ch_fu_238_sth_V;
wire   [6:0] call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_0;
wire   [0:0] call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_1;
wire   [0:0] call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_2;
wire   [1:0] call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_3;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_249_dth_0_V_read;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_249_dth_1_V_read;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_249_dth_2_V_read;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_249_dth_3_V_read;
wire   [3:0] call_ret185_sp_best_delta_seg_ch_fu_249_sth_V;
wire   [6:0] call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_0;
wire   [0:0] call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_1;
wire   [0:0] call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_2;
wire   [1:0] call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_3;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_260_dth_0_V_read;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_260_dth_1_V_read;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_260_dth_2_V_read;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_260_dth_3_V_read;
wire   [3:0] call_ret180_sp_best_delta_seg_ch_fu_260_sth_V;
wire   [6:0] call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_0;
wire   [0:0] call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_1;
wire   [0:0] call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_2;
wire   [1:0] call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_3;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_271_dth_0_V_read;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_271_dth_1_V_read;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_271_dth_2_V_read;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_271_dth_3_V_read;
wire   [3:0] call_ret_sp_best_delta_seg_ch_fu_271_sth_V;
wire   [6:0] call_ret_sp_best_delta_seg_ch_fu_271_ap_return_0;
wire   [0:0] call_ret_sp_best_delta_seg_ch_fu_271_ap_return_1;
wire   [0:0] call_ret_sp_best_delta_seg_ch_fu_271_ap_return_2;
wire   [1:0] call_ret_sp_best_delta_seg_ch_fu_271_ap_return_3;
wire   [0:0] val_assign_fu_282_p2;
wire   [6:0] tmp_236_fu_288_p2;
wire   [6:0] tmp_237_fu_294_p2;
wire   [0:0] val_assign_0_0_0_1_fu_309_p2;
wire   [6:0] tmp_1095_0_0_0_1_fu_315_p2;
wire   [6:0] tmp_1096_0_0_0_1_fu_321_p2;
wire   [0:0] val_assign_0_0_1_fu_336_p2;
wire   [6:0] tmp_1095_0_0_1_fu_342_p2;
wire   [6:0] tmp_1096_0_0_1_fu_348_p2;
wire   [0:0] val_assign_0_0_1_1_fu_363_p2;
wire   [6:0] tmp_1095_0_0_1_1_fu_369_p2;
wire   [6:0] tmp_1096_0_0_1_1_fu_375_p2;
wire   [0:0] sph12_V_fu_403_p2;
wire   [11:0] tmp_238_fu_409_p2;
wire   [11:0] tmp_239_fu_415_p2;
wire   [0:0] val_assign_0_1_fu_429_p2;
wire   [6:0] tmp_1095_0_1_fu_435_p2;
wire   [6:0] tmp_1096_0_1_fu_441_p2;
wire   [0:0] val_assign_0_1_0_1_fu_456_p2;
wire   [6:0] tmp_1095_0_1_0_1_fu_462_p2;
wire   [6:0] tmp_1096_0_1_0_1_fu_468_p2;
wire   [0:0] val_assign_0_1_1_fu_483_p2;
wire   [6:0] tmp_1095_0_1_1_fu_489_p2;
wire   [6:0] tmp_1096_0_1_1_fu_495_p2;
wire   [0:0] val_assign_0_1_1_1_fu_510_p2;
wire   [6:0] tmp_1095_0_1_1_1_fu_516_p2;
wire   [6:0] tmp_1096_0_1_1_1_fu_522_p2;
wire   [0:0] sph12_V_0_1_fu_550_p2;
wire   [11:0] tmp_1088_0_1_fu_556_p2;
wire   [11:0] tmp_1089_0_1_fu_562_p2;
wire   [0:0] val_assign_0_2_fu_576_p2;
wire   [6:0] tmp_1095_0_2_fu_582_p2;
wire   [6:0] tmp_1096_0_2_fu_588_p2;
wire   [0:0] val_assign_0_2_0_1_fu_603_p2;
wire   [6:0] tmp_1095_0_2_0_1_fu_609_p2;
wire   [6:0] tmp_1096_0_2_0_1_fu_615_p2;
wire   [0:0] val_assign_0_2_1_fu_630_p2;
wire   [6:0] tmp_1095_0_2_1_fu_636_p2;
wire   [6:0] tmp_1096_0_2_1_fu_642_p2;
wire   [0:0] val_assign_0_2_1_1_fu_657_p2;
wire   [6:0] tmp_1095_0_2_1_1_fu_663_p2;
wire   [6:0] tmp_1096_0_2_1_1_fu_669_p2;
wire   [0:0] sph12_V_0_2_fu_697_p2;
wire   [11:0] tmp_1088_0_2_fu_703_p2;
wire   [11:0] tmp_1089_0_2_fu_709_p2;
wire   [0:0] val_assign_1_fu_723_p2;
wire   [6:0] tmp_1095_1_fu_729_p2;
wire   [6:0] tmp_1096_1_fu_735_p2;
wire   [0:0] val_assign_1_0_0_1_fu_750_p2;
wire   [6:0] tmp_1095_1_0_0_1_fu_756_p2;
wire   [6:0] tmp_1096_1_0_0_1_fu_762_p2;
wire   [0:0] val_assign_1_0_1_fu_777_p2;
wire   [6:0] tmp_1095_1_0_1_fu_783_p2;
wire   [6:0] tmp_1096_1_0_1_fu_789_p2;
wire   [0:0] val_assign_1_0_1_1_fu_804_p2;
wire   [6:0] tmp_1095_1_0_1_1_fu_810_p2;
wire   [6:0] tmp_1096_1_0_1_1_fu_816_p2;
wire   [0:0] sph12_V_1_fu_844_p2;
wire   [11:0] tmp_1088_1_fu_850_p2;
wire   [11:0] tmp_1089_1_fu_856_p2;
wire   [0:0] val_assign_1_1_fu_870_p2;
wire   [6:0] tmp_1095_1_1_fu_876_p2;
wire   [6:0] tmp_1096_1_1_fu_882_p2;
wire   [0:0] val_assign_1_1_0_1_fu_897_p2;
wire   [6:0] tmp_1095_1_1_0_1_fu_903_p2;
wire   [6:0] tmp_1096_1_1_0_1_fu_909_p2;
wire   [0:0] val_assign_1_1_1_fu_924_p2;
wire   [6:0] tmp_1095_1_1_1_fu_930_p2;
wire   [6:0] tmp_1096_1_1_1_fu_936_p2;
wire   [0:0] val_assign_1_1_1_1_fu_951_p2;
wire   [6:0] tmp_1095_1_1_1_1_fu_957_p2;
wire   [6:0] tmp_1096_1_1_1_1_fu_963_p2;
wire   [0:0] sph12_V_1_1_fu_991_p2;
wire   [11:0] tmp_1088_1_1_fu_997_p2;
wire   [11:0] tmp_1089_1_1_fu_1003_p2;
wire   [0:0] val_assign_2_fu_1017_p2;
wire   [6:0] tmp_1095_2_fu_1023_p2;
wire   [6:0] tmp_1096_2_fu_1029_p2;
wire   [0:0] val_assign_2_0_0_1_fu_1044_p2;
wire   [6:0] tmp_1095_2_0_0_1_fu_1050_p2;
wire   [6:0] tmp_1096_2_0_0_1_fu_1056_p2;
wire   [0:0] val_assign_2_0_1_fu_1071_p2;
wire   [6:0] tmp_1095_2_0_1_fu_1077_p2;
wire   [6:0] tmp_1096_2_0_1_fu_1083_p2;
wire   [0:0] val_assign_2_0_1_1_fu_1098_p2;
wire   [6:0] tmp_1095_2_0_1_1_fu_1104_p2;
wire   [6:0] tmp_1096_2_0_1_1_fu_1110_p2;
wire   [0:0] sph12_V_2_fu_1138_p2;
wire   [11:0] tmp_1088_2_fu_1144_p2;
wire   [11:0] tmp_1089_2_fu_1150_p2;
wire   [0:0] not_tmp_fu_1260_p2;
wire   [0:0] p_s_fu_1266_p2;
wire   [2:0] vmask1_V_fu_1286_p3;
wire   [2:0] p_10_cast_cast_fu_1272_p3;
wire   [0:0] tmp_s_fu_1280_p2;
wire   [2:0] p_0720_0_s_fu_1294_p3;
wire   [2:0] p_01408_1_fu_1302_p3;
wire   [2:0] tmp_54_fu_1320_p2;
wire   [3:0] vmask1_V_2_fu_1326_p3;
wire   [3:0] p_01408_1_cast_fu_1310_p1;
wire   [0:0] tmp_95_fu_1314_p2;
wire   [3:0] p_0695_0_01408_1_fu_1334_p3;
wire   [0:0] tmp_96_fu_1350_p2;
wire   [0:0] tmp_fu_1364_p2;
wire   [1:0] p_8_fu_1356_p3;
wire   [1:0] p_2_fu_1370_p3;
wire  signed [2:0] p_11_cast1_fu_1378_p1;
wire   [2:0] tmp_55_fu_1392_p2;
wire   [3:0] vmask2_V_fu_1398_p3;
wire   [3:0] p_11_cast_fu_1382_p1;
wire   [0:0] tmp_97_fu_1386_p2;
wire   [3:0] p_0645_0_s_fu_1406_p3;
wire   [0:0] tmp_98_fu_1422_p2;
wire   [0:0] tmp_206_fu_1436_p2;
wire   [2:0] p_9_fu_1428_p3;
wire   [2:0] rhs_V_2_fu_1442_p3;
wire   [3:0] rhs_V_fu_1414_p3;
wire   [3:0] vstat_V_fu_1342_p3;
wire   [3:0] r_V_fu_1454_p2;
wire   [0:0] tmp_99_fu_1460_p2;
wire   [0:0] tmp_100_fu_1466_p2;
wire   [0:0] or_cond_fu_1472_p2;
wire   [3:0] tmp_101_fu_1478_p3;
wire  signed [3:0] rhs_V_2_cast_fu_1450_p1;
wire   [3:0] vstat_V_3_fu_1486_p2;
wire   [3:0] r_V_2_fu_1492_p2;
wire   [0:0] tmp_102_fu_1498_p2;
wire   [0:0] tmp_103_fu_1504_p2;
wire   [0:0] or_cond3_fu_1510_p2;
wire   [2:0] tmp_104_fu_1516_p3;
wire  signed [3:0] tmp_104_cast_fu_1524_p1;
wire   [3:0] vstat_V_4_fu_1528_p2;
wire   [0:0] tmp_1127_fu_1582_p1;
wire   [1:0] tmp_240_fu_1586_p3;
wire   [3:0] a_theta_V_fu_1598_p9;
wire   [0:0] tmp_1129_fu_1628_p3;
wire   [1:0] tmp_241_fu_1636_p3;
wire   [3:0] a_theta_V_15_fu_1648_p9;
wire   [0:0] tmp_1130_fu_1670_p1;
wire   [2:0] tmp_242_fu_1674_p3;
wire   [3:0] a_theta_V_16_fu_1686_p9;
wire   [0:0] tmp_1131_fu_1708_p3;
wire   [1:0] tmp_243_fu_1716_p3;
wire   [3:0] a_theta_V_17_fu_1728_p9;
wire   [0:0] tmp_1132_fu_1750_p3;
wire   [2:0] tmp_244_fu_1758_p3;
wire   [3:0] a_theta_V_18_fu_1770_p9;
wire   [0:0] tmp_1133_fu_1792_p1;
wire   [2:0] tmp_245_fu_1796_p3;
wire   [3:0] a_theta_V_19_fu_1808_p9;
wire   [0:0] tmp_1125_fu_1566_p3;
wire   [0:0] tmp_1126_fu_1574_p3;
wire   [0:0] sel_tmp12_fu_1830_p2;
wire   [0:0] sel_tmp13_fu_1836_p2;
wire   [0:0] sel_tmp14_fu_1842_p2;
wire   [0:0] sel_tmp15_fu_1848_p2;
wire   [0:0] sel_tmp16_fu_1854_p2;
wire   [0:0] sel_tmp20_fu_1868_p2;
wire   [11:0] a_phi_V_fu_1860_p3;
wire   [0:0] sel_tmp24_demorgan_fu_1882_p2;
wire   [0:0] tmp_1128_fu_1620_p3;
wire   [0:0] sel_tmp24_fu_1888_p2;
wire   [0:0] sel_tmp25_fu_1894_p2;
wire   [0:0] sel_tmp26_fu_1900_p2;
wire   [11:0] a_phi_V_6_fu_1874_p3;
wire   [0:0] sel_tmp32_fu_1914_p2;
wire   [0:0] sel_tmp33_fu_1920_p2;
wire   [11:0] a_phi_V_7_fu_1906_p3;
wire   [0:0] sel_tmp39_demorgan_fu_1934_p2;
wire   [11:0] a_phi_V_8_fu_1926_p3;
wire   [0:0] sel_tmp45_fu_1948_p2;
wire   [0:0] sel_tmp46_fu_1954_p2;
wire   [11:0] a_phi_V_9_fu_1940_p3;
wire   [0:0] sel_tmp48_fu_1968_p2;
wire   [0:0] sel_tmp49_fu_1974_p2;
wire   [0:0] sel_tmp50_fu_1980_p2;
wire   [6:0] a_theta_V_15_fu_1648_p10;
wire   [0:0] sel_tmp54_fu_1994_p2;
wire   [0:0] tmp20_fu_2000_p2;
wire   [0:0] sel_tmp56_fu_2006_p2;
wire   [6:0] a_theta_V_17_fu_1728_p10;
wire   [6:0] a_theta_V_20_fu_1986_p3;
wire   [0:0] sel_tmp58_fu_2020_p2;
wire   [6:0] a_theta_V_fu_1598_p10;
wire   [6:0] a_theta_V_21_fu_2012_p3;
wire   [6:0] a_theta_V_18_fu_1770_p10;
wire   [6:0] a_theta_V_22_fu_2026_p3;
wire   [6:0] a_theta_V_16_fu_1686_p10;
wire   [6:0] a_theta_V_23_fu_2034_p3;
wire   [6:0] a_theta_V_19_fu_1808_p10;
wire   [6:0] a_theta_V_24_fu_2042_p3;
wire   [6:0] a_theta_V_25_fu_2050_p3;
wire   [6:0] a_theta_V_26_fu_2058_p3;
wire   [6:0] a_theta_V_27_fu_2066_p3;
wire   [0:0] tmp_1134_fu_2082_p1;
reg   [1:0] tmp_246_fu_2086_p4;
wire   [0:0] sel_tmp96_fu_2112_p2;
wire   [0:0] sel_tmp97_fu_2118_p2;
wire   [0:0] sel_tmp99_fu_2130_p2;
wire   [0:0] sel_tmp100_fu_2136_p2;
wire   [0:0] tmp23_fu_2148_p2;
wire   [0:0] sel_tmp98_fu_2124_p2;
wire   [0:0] tmp22_fu_2154_p2;
wire   [0:0] tmp21_fu_2142_p2;
wire   [0:0] sel_tmp104_fu_2160_p2;
wire   [6:0] p_Result_125_fu_2096_p7;
wire   [11:0] a_phi_V_10_fu_1960_p3;
wire   [6:0] a_theta_V_28_fu_2074_p3;
wire   [5:0] p_Result_s_fu_1534_p7;
wire   [5:0] p_Result_124_fu_1550_p7;
wire   [6:0] ssdm_int_V_write_assign_fu_2166_p3;
wire   [11:0] delta_ph_0_V_write_assign_fu_421_p3;
wire   [11:0] delta_ph_1_V_write_assign_fu_568_p3;
wire   [11:0] delta_ph_2_V_write_assign_fu_715_p3;
wire   [11:0] delta_ph_3_V_write_assign_fu_862_p3;
wire   [11:0] delta_ph_4_V_write_assign_fu_1009_p3;
wire   [11:0] delta_ph_5_V_write_assign_fu_1156_p3;

sp_best_delta_seg_ch call_ret200_sp_best_delta_seg_ch_fu_216(
    .dth_0_V_read(call_ret200_sp_best_delta_seg_ch_fu_216_dth_0_V_read),
    .dth_1_V_read(call_ret200_sp_best_delta_seg_ch_fu_216_dth_1_V_read),
    .dth_2_V_read(call_ret200_sp_best_delta_seg_ch_fu_216_dth_2_V_read),
    .dth_3_V_read(call_ret200_sp_best_delta_seg_ch_fu_216_dth_3_V_read),
    .sth_V(call_ret200_sp_best_delta_seg_ch_fu_216_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_0),
    .ap_return_1(call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_1),
    .ap_return_2(call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_2),
    .ap_return_3(call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_3)
);

sp_best_delta_seg_ch call_ret195_sp_best_delta_seg_ch_fu_227(
    .dth_0_V_read(call_ret195_sp_best_delta_seg_ch_fu_227_dth_0_V_read),
    .dth_1_V_read(call_ret195_sp_best_delta_seg_ch_fu_227_dth_1_V_read),
    .dth_2_V_read(call_ret195_sp_best_delta_seg_ch_fu_227_dth_2_V_read),
    .dth_3_V_read(call_ret195_sp_best_delta_seg_ch_fu_227_dth_3_V_read),
    .sth_V(call_ret195_sp_best_delta_seg_ch_fu_227_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_0),
    .ap_return_1(call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_1),
    .ap_return_2(call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_2),
    .ap_return_3(call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_3)
);

sp_best_delta_seg_ch call_ret190_sp_best_delta_seg_ch_fu_238(
    .dth_0_V_read(call_ret190_sp_best_delta_seg_ch_fu_238_dth_0_V_read),
    .dth_1_V_read(call_ret190_sp_best_delta_seg_ch_fu_238_dth_1_V_read),
    .dth_2_V_read(call_ret190_sp_best_delta_seg_ch_fu_238_dth_2_V_read),
    .dth_3_V_read(call_ret190_sp_best_delta_seg_ch_fu_238_dth_3_V_read),
    .sth_V(call_ret190_sp_best_delta_seg_ch_fu_238_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_0),
    .ap_return_1(call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_1),
    .ap_return_2(call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_2),
    .ap_return_3(call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_3)
);

sp_best_delta_seg_ch call_ret185_sp_best_delta_seg_ch_fu_249(
    .dth_0_V_read(call_ret185_sp_best_delta_seg_ch_fu_249_dth_0_V_read),
    .dth_1_V_read(call_ret185_sp_best_delta_seg_ch_fu_249_dth_1_V_read),
    .dth_2_V_read(call_ret185_sp_best_delta_seg_ch_fu_249_dth_2_V_read),
    .dth_3_V_read(call_ret185_sp_best_delta_seg_ch_fu_249_dth_3_V_read),
    .sth_V(call_ret185_sp_best_delta_seg_ch_fu_249_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_0),
    .ap_return_1(call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_1),
    .ap_return_2(call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_2),
    .ap_return_3(call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_3)
);

sp_best_delta_seg_ch call_ret180_sp_best_delta_seg_ch_fu_260(
    .dth_0_V_read(call_ret180_sp_best_delta_seg_ch_fu_260_dth_0_V_read),
    .dth_1_V_read(call_ret180_sp_best_delta_seg_ch_fu_260_dth_1_V_read),
    .dth_2_V_read(call_ret180_sp_best_delta_seg_ch_fu_260_dth_2_V_read),
    .dth_3_V_read(call_ret180_sp_best_delta_seg_ch_fu_260_dth_3_V_read),
    .sth_V(call_ret180_sp_best_delta_seg_ch_fu_260_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_0),
    .ap_return_1(call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_1),
    .ap_return_2(call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_2),
    .ap_return_3(call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_3)
);

sp_best_delta_seg_ch call_ret_sp_best_delta_seg_ch_fu_271(
    .dth_0_V_read(call_ret_sp_best_delta_seg_ch_fu_271_dth_0_V_read),
    .dth_1_V_read(call_ret_sp_best_delta_seg_ch_fu_271_dth_1_V_read),
    .dth_2_V_read(call_ret_sp_best_delta_seg_ch_fu_271_dth_2_V_read),
    .dth_3_V_read(call_ret_sp_best_delta_seg_ch_fu_271_dth_3_V_read),
    .sth_V(call_ret_sp_best_delta_seg_ch_fu_271_sth_V),
    .dvl_V(ap_const_lv4_0),
    .ap_return_0(call_ret_sp_best_delta_seg_ch_fu_271_ap_return_0),
    .ap_return_1(call_ret_sp_best_delta_seg_ch_fu_271_ap_return_1),
    .ap_return_2(call_ret_sp_best_delta_seg_ch_fu_271_ap_return_2),
    .ap_return_3(call_ret_sp_best_delta_seg_ch_fu_271_ap_return_3)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3465(
    .din1(th_match_0_0_V_read),
    .din2(th_match_0_1_V_read),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_fu_1598_p9),
    .dout(a_theta_V_fu_1598_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3466(
    .din1(th_match_0_0_V_read),
    .din2(th_match_0_1_V_read),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_15_fu_1648_p9),
    .dout(a_theta_V_15_fu_1648_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3467(
    .din1(th_match_0_0_V_read),
    .din2(th_match_0_1_V_read),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_16_fu_1686_p9),
    .dout(a_theta_V_16_fu_1686_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3468(
    .din1(th_match_0_0_V_read),
    .din2(th_match_0_1_V_read),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_17_fu_1728_p9),
    .dout(a_theta_V_17_fu_1728_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3469(
    .din1(th_match_0_0_V_read),
    .din2(th_match_0_1_V_read),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_18_fu_1770_p9),
    .dout(a_theta_V_18_fu_1770_p10)
);

sp_mux_8to1_sel4_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sp_mux_8to1_sel4_7_1_U3470(
    .din1(th_match_0_0_V_read),
    .din2(th_match_0_1_V_read),
    .din3(th_match_1_0_V_read),
    .din4(th_match_1_1_V_read),
    .din5(th_match_2_0_V_read),
    .din6(th_match_2_1_V_read),
    .din7(th_match_3_0_V_read),
    .din8(th_match_3_1_V_read),
    .din9(a_theta_V_19_fu_1808_p9),
    .dout(a_theta_V_19_fu_1808_p10)
);

assign a_phi_V_10_fu_1960_p3 = ((sel_tmp46_fu_1954_p2[0:0] === 1'b1) ? ph_match_3_V_read : a_phi_V_9_fu_1940_p3);

assign a_phi_V_6_fu_1874_p3 = ((sel_tmp20_fu_1868_p2[0:0] === 1'b1) ? ph_match_2_V_read : a_phi_V_fu_1860_p3);

assign a_phi_V_7_fu_1906_p3 = ((sel_tmp26_fu_1900_p2[0:0] === 1'b1) ? ph_match_3_V_read : a_phi_V_6_fu_1874_p3);

assign a_phi_V_8_fu_1926_p3 = ((sel_tmp33_fu_1920_p2[0:0] === 1'b1) ? ph_match_2_V_read : a_phi_V_7_fu_1906_p3);

assign a_phi_V_9_fu_1940_p3 = ((sel_tmp39_demorgan_fu_1934_p2[0:0] === 1'b1) ? a_phi_V_8_fu_1926_p3 : ap_const_lv12_0);

assign a_phi_V_fu_1860_p3 = ((sel_tmp16_fu_1854_p2[0:0] === 1'b1) ? ph_match_2_V_read : ph_match_1_V_read);

assign a_theta_V_15_fu_1648_p9 = tmp_241_fu_1636_p3;

assign a_theta_V_16_fu_1686_p9 = tmp_242_fu_1674_p3;

assign a_theta_V_17_fu_1728_p9 = tmp_243_fu_1716_p3;

assign a_theta_V_18_fu_1770_p9 = tmp_244_fu_1758_p3;

assign a_theta_V_19_fu_1808_p9 = tmp_245_fu_1796_p3;

assign a_theta_V_20_fu_1986_p3 = ((sel_tmp50_fu_1980_p2[0:0] === 1'b1) ? a_theta_V_15_fu_1648_p10 : ap_const_lv7_0);

assign a_theta_V_21_fu_2012_p3 = ((sel_tmp56_fu_2006_p2[0:0] === 1'b1) ? a_theta_V_17_fu_1728_p10 : a_theta_V_20_fu_1986_p3);

assign a_theta_V_22_fu_2026_p3 = ((sel_tmp58_fu_2020_p2[0:0] === 1'b1) ? a_theta_V_fu_1598_p10 : a_theta_V_21_fu_2012_p3);

assign a_theta_V_23_fu_2034_p3 = ((sel_tmp16_fu_1854_p2[0:0] === 1'b1) ? a_theta_V_18_fu_1770_p10 : a_theta_V_22_fu_2026_p3);

assign a_theta_V_24_fu_2042_p3 = ((sel_tmp20_fu_1868_p2[0:0] === 1'b1) ? a_theta_V_16_fu_1686_p10 : a_theta_V_23_fu_2034_p3);

assign a_theta_V_25_fu_2050_p3 = ((sel_tmp26_fu_1900_p2[0:0] === 1'b1) ? a_theta_V_19_fu_1808_p10 : a_theta_V_24_fu_2042_p3);

assign a_theta_V_26_fu_2058_p3 = ((sel_tmp33_fu_1920_p2[0:0] === 1'b1) ? ap_const_lv7_0 : a_theta_V_25_fu_2050_p3);

assign a_theta_V_27_fu_2066_p3 = ((sel_tmp39_demorgan_fu_1934_p2[0:0] === 1'b1) ? a_theta_V_26_fu_2058_p3 : ap_const_lv7_0);

assign a_theta_V_28_fu_2074_p3 = ((sel_tmp46_fu_1954_p2[0:0] === 1'b1) ? ap_const_lv7_0 : a_theta_V_27_fu_2066_p3);

assign a_theta_V_fu_1598_p9 = tmp_240_fu_1586_p3;

assign ap_return_0 = a_phi_V_10_fu_1960_p3;

assign ap_return_1 = a_theta_V_28_fu_2074_p3;

assign ap_return_10 = delta_ph_1_V_write_assign_fu_568_p3;

assign ap_return_11 = delta_ph_2_V_write_assign_fu_715_p3;

assign ap_return_12 = delta_ph_3_V_write_assign_fu_862_p3;

assign ap_return_13 = delta_ph_4_V_write_assign_fu_1009_p3;

assign ap_return_14 = delta_ph_5_V_write_assign_fu_1156_p3;

assign ap_return_15 = call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_0;

assign ap_return_16 = call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_0;

assign ap_return_17 = call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_0;

assign ap_return_18 = call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_0;

assign ap_return_19 = call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_0;

assign ap_return_2 = p_Result_s_fu_1534_p7;

assign ap_return_20 = call_ret_sp_best_delta_seg_ch_fu_271_ap_return_0;

assign ap_return_3 = p_Result_124_fu_1550_p7;

assign ap_return_4 = ssdm_int_V_write_assign_fu_2166_p3;

assign ap_return_5 = cpat_match_0_V_read;

assign ap_return_6 = cpat_match_1_V_read;

assign ap_return_7 = cpat_match_2_V_read;

assign ap_return_8 = cpat_match_3_V_read;

assign ap_return_9 = delta_ph_0_V_write_assign_fu_421_p3;

assign call_ret180_sp_best_delta_seg_ch_fu_260_dth_0_V_read = ((val_assign_1_1_fu_870_p2[0:0] === 1'b1) ? tmp_1095_1_1_fu_876_p2 : tmp_1096_1_1_fu_882_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_260_dth_1_V_read = ((val_assign_1_1_0_1_fu_897_p2[0:0] === 1'b1) ? tmp_1095_1_1_0_1_fu_903_p2 : tmp_1096_1_1_0_1_fu_909_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_260_dth_2_V_read = ((val_assign_1_1_1_fu_924_p2[0:0] === 1'b1) ? tmp_1095_1_1_1_fu_930_p2 : tmp_1096_1_1_1_fu_936_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_260_dth_3_V_read = ((val_assign_1_1_1_1_fu_951_p2[0:0] === 1'b1) ? tmp_1095_1_1_1_1_fu_957_p2 : tmp_1096_1_1_1_1_fu_963_p2);

assign call_ret180_sp_best_delta_seg_ch_fu_260_sth_V = {{{{val_assign_1_1_1_1_fu_951_p2}, {val_assign_1_1_1_fu_924_p2}}, {val_assign_1_1_0_1_fu_897_p2}}, {val_assign_1_1_fu_870_p2}};

assign call_ret185_sp_best_delta_seg_ch_fu_249_dth_0_V_read = ((val_assign_1_fu_723_p2[0:0] === 1'b1) ? tmp_1095_1_fu_729_p2 : tmp_1096_1_fu_735_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_249_dth_1_V_read = ((val_assign_1_0_0_1_fu_750_p2[0:0] === 1'b1) ? tmp_1095_1_0_0_1_fu_756_p2 : tmp_1096_1_0_0_1_fu_762_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_249_dth_2_V_read = ((val_assign_1_0_1_fu_777_p2[0:0] === 1'b1) ? tmp_1095_1_0_1_fu_783_p2 : tmp_1096_1_0_1_fu_789_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_249_dth_3_V_read = ((val_assign_1_0_1_1_fu_804_p2[0:0] === 1'b1) ? tmp_1095_1_0_1_1_fu_810_p2 : tmp_1096_1_0_1_1_fu_816_p2);

assign call_ret185_sp_best_delta_seg_ch_fu_249_sth_V = {{{{val_assign_1_0_1_1_fu_804_p2}, {val_assign_1_0_1_fu_777_p2}}, {val_assign_1_0_0_1_fu_750_p2}}, {val_assign_1_fu_723_p2}};

assign call_ret190_sp_best_delta_seg_ch_fu_238_dth_0_V_read = ((val_assign_0_2_fu_576_p2[0:0] === 1'b1) ? tmp_1095_0_2_fu_582_p2 : tmp_1096_0_2_fu_588_p2);

assign call_ret190_sp_best_delta_seg_ch_fu_238_dth_1_V_read = ((val_assign_0_2_0_1_fu_603_p2[0:0] === 1'b1) ? tmp_1095_0_2_0_1_fu_609_p2 : tmp_1096_0_2_0_1_fu_615_p2);

assign call_ret190_sp_best_delta_seg_ch_fu_238_dth_2_V_read = ((val_assign_0_2_1_fu_630_p2[0:0] === 1'b1) ? tmp_1095_0_2_1_fu_636_p2 : tmp_1096_0_2_1_fu_642_p2);

assign call_ret190_sp_best_delta_seg_ch_fu_238_dth_3_V_read = ((val_assign_0_2_1_1_fu_657_p2[0:0] === 1'b1) ? tmp_1095_0_2_1_1_fu_663_p2 : tmp_1096_0_2_1_1_fu_669_p2);

assign call_ret190_sp_best_delta_seg_ch_fu_238_sth_V = {{{{val_assign_0_2_1_1_fu_657_p2}, {val_assign_0_2_1_fu_630_p2}}, {val_assign_0_2_0_1_fu_603_p2}}, {val_assign_0_2_fu_576_p2}};

assign call_ret195_sp_best_delta_seg_ch_fu_227_dth_0_V_read = ((val_assign_0_1_fu_429_p2[0:0] === 1'b1) ? tmp_1095_0_1_fu_435_p2 : tmp_1096_0_1_fu_441_p2);

assign call_ret195_sp_best_delta_seg_ch_fu_227_dth_1_V_read = ((val_assign_0_1_0_1_fu_456_p2[0:0] === 1'b1) ? tmp_1095_0_1_0_1_fu_462_p2 : tmp_1096_0_1_0_1_fu_468_p2);

assign call_ret195_sp_best_delta_seg_ch_fu_227_dth_2_V_read = ((val_assign_0_1_1_fu_483_p2[0:0] === 1'b1) ? tmp_1095_0_1_1_fu_489_p2 : tmp_1096_0_1_1_fu_495_p2);

assign call_ret195_sp_best_delta_seg_ch_fu_227_dth_3_V_read = ((val_assign_0_1_1_1_fu_510_p2[0:0] === 1'b1) ? tmp_1095_0_1_1_1_fu_516_p2 : tmp_1096_0_1_1_1_fu_522_p2);

assign call_ret195_sp_best_delta_seg_ch_fu_227_sth_V = {{{{val_assign_0_1_1_1_fu_510_p2}, {val_assign_0_1_1_fu_483_p2}}, {val_assign_0_1_0_1_fu_456_p2}}, {val_assign_0_1_fu_429_p2}};

assign call_ret200_sp_best_delta_seg_ch_fu_216_dth_0_V_read = ((val_assign_fu_282_p2[0:0] === 1'b1) ? tmp_236_fu_288_p2 : tmp_237_fu_294_p2);

assign call_ret200_sp_best_delta_seg_ch_fu_216_dth_1_V_read = ((val_assign_0_0_0_1_fu_309_p2[0:0] === 1'b1) ? tmp_1095_0_0_0_1_fu_315_p2 : tmp_1096_0_0_0_1_fu_321_p2);

assign call_ret200_sp_best_delta_seg_ch_fu_216_dth_2_V_read = ((val_assign_0_0_1_fu_336_p2[0:0] === 1'b1) ? tmp_1095_0_0_1_fu_342_p2 : tmp_1096_0_0_1_fu_348_p2);

assign call_ret200_sp_best_delta_seg_ch_fu_216_dth_3_V_read = ((val_assign_0_0_1_1_fu_363_p2[0:0] === 1'b1) ? tmp_1095_0_0_1_1_fu_369_p2 : tmp_1096_0_0_1_1_fu_375_p2);

assign call_ret200_sp_best_delta_seg_ch_fu_216_sth_V = {{{{val_assign_0_0_1_1_fu_363_p2}, {val_assign_0_0_1_fu_336_p2}}, {val_assign_0_0_0_1_fu_309_p2}}, {val_assign_fu_282_p2}};

assign call_ret_sp_best_delta_seg_ch_fu_271_dth_0_V_read = ((val_assign_2_fu_1017_p2[0:0] === 1'b1) ? tmp_1095_2_fu_1023_p2 : tmp_1096_2_fu_1029_p2);

assign call_ret_sp_best_delta_seg_ch_fu_271_dth_1_V_read = ((val_assign_2_0_0_1_fu_1044_p2[0:0] === 1'b1) ? tmp_1095_2_0_0_1_fu_1050_p2 : tmp_1096_2_0_0_1_fu_1056_p2);

assign call_ret_sp_best_delta_seg_ch_fu_271_dth_2_V_read = ((val_assign_2_0_1_fu_1071_p2[0:0] === 1'b1) ? tmp_1095_2_0_1_fu_1077_p2 : tmp_1096_2_0_1_fu_1083_p2);

assign call_ret_sp_best_delta_seg_ch_fu_271_dth_3_V_read = ((val_assign_2_0_1_1_fu_1098_p2[0:0] === 1'b1) ? tmp_1095_2_0_1_1_fu_1104_p2 : tmp_1096_2_0_1_1_fu_1110_p2);

assign call_ret_sp_best_delta_seg_ch_fu_271_sth_V = {{{{val_assign_2_0_1_1_fu_1098_p2}, {val_assign_2_0_1_fu_1071_p2}}, {val_assign_2_0_0_1_fu_1044_p2}}, {val_assign_2_fu_1017_p2}};

assign delta_ph_0_V_write_assign_fu_421_p3 = ((sph12_V_fu_403_p2[0:0] === 1'b1) ? tmp_238_fu_409_p2 : tmp_239_fu_415_p2);

assign delta_ph_1_V_write_assign_fu_568_p3 = ((sph12_V_0_1_fu_550_p2[0:0] === 1'b1) ? tmp_1088_0_1_fu_556_p2 : tmp_1089_0_1_fu_562_p2);

assign delta_ph_2_V_write_assign_fu_715_p3 = ((sph12_V_0_2_fu_697_p2[0:0] === 1'b1) ? tmp_1088_0_2_fu_703_p2 : tmp_1089_0_2_fu_709_p2);

assign delta_ph_3_V_write_assign_fu_862_p3 = ((sph12_V_1_fu_844_p2[0:0] === 1'b1) ? tmp_1088_1_fu_850_p2 : tmp_1089_1_fu_856_p2);

assign delta_ph_4_V_write_assign_fu_1009_p3 = ((sph12_V_1_1_fu_991_p2[0:0] === 1'b1) ? tmp_1088_1_1_fu_997_p2 : tmp_1089_1_1_fu_1003_p2);

assign delta_ph_5_V_write_assign_fu_1156_p3 = ((sph12_V_2_fu_1138_p2[0:0] === 1'b1) ? tmp_1088_2_fu_1144_p2 : tmp_1089_2_fu_1150_p2);

assign not_tmp_fu_1260_p2 = ((call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_0 < ap_const_lv7_5) ? 1'b1 : 1'b0);

assign or_cond3_fu_1510_p2 = (tmp_102_fu_1498_p2 | tmp_103_fu_1504_p2);

assign or_cond_fu_1472_p2 = (tmp_99_fu_1460_p2 | tmp_100_fu_1466_p2);

assign p_01408_1_cast_fu_1310_p1 = p_01408_1_fu_1302_p3;

assign p_01408_1_fu_1302_p3 = ((tmp_s_fu_1280_p2[0:0] === 1'b1) ? p_10_cast_cast_fu_1272_p3 : p_0720_0_s_fu_1294_p3);

assign p_0645_0_s_fu_1406_p3 = ((call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_2[0:0] === 1'b1) ? vmask2_V_fu_1398_p3 : p_11_cast_fu_1382_p1);

assign p_0695_0_01408_1_fu_1334_p3 = ((call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_2[0:0] === 1'b1) ? vmask1_V_2_fu_1326_p3 : p_01408_1_cast_fu_1310_p1);

assign p_0720_0_s_fu_1294_p3 = ((call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_2[0:0] === 1'b1) ? vmask1_V_fu_1286_p3 : p_10_cast_cast_fu_1272_p3);

assign p_10_cast_cast_fu_1272_p3 = ((p_s_fu_1266_p2[0:0] === 1'b1) ? ap_const_lv3_3 : ap_const_lv3_0);

assign p_11_cast1_fu_1378_p1 = $signed(p_2_fu_1370_p3);

assign p_11_cast_fu_1382_p1 = $unsigned(p_11_cast1_fu_1378_p1);

assign p_2_fu_1370_p3 = ((tmp_fu_1364_p2[0:0] === 1'b1) ? p_8_fu_1356_p3 : ap_const_lv2_0);

assign p_8_fu_1356_p3 = ((tmp_96_fu_1350_p2[0:0] === 1'b1) ? ap_const_lv2_0 : ap_const_lv2_2);

assign p_9_fu_1428_p3 = ((tmp_98_fu_1422_p2[0:0] === 1'b1) ? ap_const_lv3_0 : ap_const_lv3_4);

assign p_Result_124_fu_1550_p7 = {{{{{{call_ret_sp_best_delta_seg_ch_fu_271_ap_return_1}, {call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_1}}, {call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_1}}, {call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_1}}, {call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_1}}, {call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_1}};

assign p_Result_125_fu_2096_p7 = {{{{{{{{{{1'b0}, {tmp_1134_fu_2082_p1}}}, {1'b0}}}, {tmp_1125_fu_1566_p3}}}, {1'b0}}}, {tmp_246_fu_2086_p4}};

assign p_Result_s_fu_1534_p7 = {{{{{{sph12_V_2_fu_1138_p2}, {sph12_V_1_1_fu_991_p2}}, {sph12_V_1_fu_844_p2}}, {sph12_V_0_2_fu_697_p2}}, {sph12_V_0_1_fu_550_p2}}, {sph12_V_fu_403_p2}};

assign p_s_fu_1266_p2 = (call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_2 & not_tmp_fu_1260_p2);

assign r_V_2_fu_1492_p2 = (rhs_V_2_cast_fu_1450_p1 & vstat_V_3_fu_1486_p2);

assign r_V_fu_1454_p2 = (rhs_V_fu_1414_p3 & vstat_V_fu_1342_p3);

assign rhs_V_2_cast_fu_1450_p1 = $signed(rhs_V_2_fu_1442_p3);

assign rhs_V_2_fu_1442_p3 = ((tmp_206_fu_1436_p2[0:0] === 1'b1) ? p_9_fu_1428_p3 : ap_const_lv3_0);

assign rhs_V_fu_1414_p3 = ((tmp_97_fu_1386_p2[0:0] === 1'b1) ? p_11_cast_fu_1382_p1 : p_0645_0_s_fu_1406_p3);

assign sel_tmp100_fu_2136_p2 = ((vstat_V_4_fu_1528_p2 == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign sel_tmp104_fu_2160_p2 = (tmp22_fu_2154_p2 | tmp21_fu_2142_p2);

assign sel_tmp12_fu_1830_p2 = (tmp_1125_fu_1566_p3 ^ 1'b1);

assign sel_tmp13_fu_1836_p2 = (tmp_1126_fu_1574_p3 & sel_tmp12_fu_1830_p2);

assign sel_tmp14_fu_1842_p2 = (call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_2 ^ 1'b1);

assign sel_tmp15_fu_1848_p2 = (sel_tmp13_fu_1836_p2 & sel_tmp14_fu_1842_p2);

assign sel_tmp16_fu_1854_p2 = (sel_tmp15_fu_1848_p2 & call_ret_sp_best_delta_seg_ch_fu_271_ap_return_2);

assign sel_tmp20_fu_1868_p2 = (sel_tmp13_fu_1836_p2 & call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_2);

assign sel_tmp24_demorgan_fu_1882_p2 = (tmp_1125_fu_1566_p3 | tmp_1126_fu_1574_p3);

assign sel_tmp24_fu_1888_p2 = (sel_tmp24_demorgan_fu_1882_p2 ^ 1'b1);

assign sel_tmp25_fu_1894_p2 = (tmp_1128_fu_1620_p3 & sel_tmp24_fu_1888_p2);

assign sel_tmp26_fu_1900_p2 = (sel_tmp25_fu_1894_p2 & call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_2);

assign sel_tmp32_fu_1914_p2 = (call_ret_sp_best_delta_seg_ch_fu_271_ap_return_2 ^ 1'b1);

assign sel_tmp33_fu_1920_p2 = (sel_tmp15_fu_1848_p2 & sel_tmp32_fu_1914_p2);

assign sel_tmp39_demorgan_fu_1934_p2 = (sel_tmp24_demorgan_fu_1882_p2 | tmp_1128_fu_1620_p3);

assign sel_tmp45_fu_1948_p2 = (call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_2 ^ 1'b1);

assign sel_tmp46_fu_1954_p2 = (sel_tmp25_fu_1894_p2 & sel_tmp45_fu_1948_p2);

assign sel_tmp48_fu_1968_p2 = (call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_2 ^ 1'b1);

assign sel_tmp49_fu_1974_p2 = (tmp_1125_fu_1566_p3 & sel_tmp48_fu_1968_p2);

assign sel_tmp50_fu_1980_p2 = (sel_tmp49_fu_1974_p2 & call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_2);

assign sel_tmp54_fu_1994_p2 = (call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_2 ^ 1'b1);

assign sel_tmp56_fu_2006_p2 = (tmp20_fu_2000_p2 & sel_tmp49_fu_1974_p2);

assign sel_tmp58_fu_2020_p2 = (tmp_1125_fu_1566_p3 & call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_2);

assign sel_tmp96_fu_2112_p2 = ((vstat_V_4_fu_1528_p2 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign sel_tmp97_fu_2118_p2 = ((vstat_V_4_fu_1528_p2 == ap_const_lv4_4) ? 1'b1 : 1'b0);

assign sel_tmp98_fu_2124_p2 = ((vstat_V_4_fu_1528_p2 == ap_const_lv4_2) ? 1'b1 : 1'b0);

assign sel_tmp99_fu_2130_p2 = ((vstat_V_4_fu_1528_p2 == ap_const_lv4_1) ? 1'b1 : 1'b0);

assign sph12_V_0_1_fu_550_p2 = ((ph_match_0_V_read > ph_match_2_V_read) ? 1'b1 : 1'b0);

assign sph12_V_0_2_fu_697_p2 = ((ph_match_0_V_read > ph_match_3_V_read) ? 1'b1 : 1'b0);

assign sph12_V_1_1_fu_991_p2 = ((ph_match_1_V_read > ph_match_3_V_read) ? 1'b1 : 1'b0);

assign sph12_V_1_fu_844_p2 = ((ph_match_1_V_read > ph_match_2_V_read) ? 1'b1 : 1'b0);

assign sph12_V_2_fu_1138_p2 = ((ph_match_2_V_read > ph_match_3_V_read) ? 1'b1 : 1'b0);

assign sph12_V_fu_403_p2 = ((ph_match_0_V_read > ph_match_1_V_read) ? 1'b1 : 1'b0);

assign ssdm_int_V_write_assign_fu_2166_p3 = ((sel_tmp104_fu_2160_p2[0:0] === 1'b1) ? ap_const_lv7_0 : p_Result_125_fu_2096_p7);

assign tmp20_fu_2000_p2 = (call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_2 & sel_tmp54_fu_1994_p2);

assign tmp21_fu_2142_p2 = (sel_tmp96_fu_2112_p2 | sel_tmp97_fu_2118_p2);

assign tmp22_fu_2154_p2 = (tmp23_fu_2148_p2 | sel_tmp98_fu_2124_p2);

assign tmp23_fu_2148_p2 = (sel_tmp99_fu_2130_p2 | sel_tmp100_fu_2136_p2);

assign tmp_100_fu_1466_p2 = ((vstat_V_fu_1342_p3 == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_101_fu_1478_p3 = ((or_cond_fu_1472_p2[0:0] === 1'b1) ? rhs_V_fu_1414_p3 : ap_const_lv4_0);

assign tmp_102_fu_1498_p2 = ((r_V_2_fu_1492_p2 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_103_fu_1504_p2 = ((vstat_V_3_fu_1486_p2 == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_104_cast_fu_1524_p1 = $signed(tmp_104_fu_1516_p3);

assign tmp_104_fu_1516_p3 = ((or_cond3_fu_1510_p2[0:0] === 1'b1) ? rhs_V_2_fu_1442_p3 : ap_const_lv3_0);

assign tmp_1088_0_1_fu_556_p2 = (ph_match_0_V_read - ph_match_2_V_read);

assign tmp_1088_0_2_fu_703_p2 = (ph_match_0_V_read - ph_match_3_V_read);

assign tmp_1088_1_1_fu_997_p2 = (ph_match_1_V_read - ph_match_3_V_read);

assign tmp_1088_1_fu_850_p2 = (ph_match_1_V_read - ph_match_2_V_read);

assign tmp_1088_2_fu_1144_p2 = (ph_match_2_V_read - ph_match_3_V_read);

assign tmp_1089_0_1_fu_562_p2 = (ph_match_2_V_read - ph_match_0_V_read);

assign tmp_1089_0_2_fu_709_p2 = (ph_match_3_V_read - ph_match_0_V_read);

assign tmp_1089_1_1_fu_1003_p2 = (ph_match_3_V_read - ph_match_1_V_read);

assign tmp_1089_1_fu_856_p2 = (ph_match_2_V_read - ph_match_1_V_read);

assign tmp_1089_2_fu_1150_p2 = (ph_match_3_V_read - ph_match_2_V_read);

assign tmp_1095_0_0_0_1_fu_315_p2 = (th_match_0_0_V_read - th_match_1_1_V_read);

assign tmp_1095_0_0_1_1_fu_369_p2 = (th_match_0_1_V_read - th_match_1_1_V_read);

assign tmp_1095_0_0_1_fu_342_p2 = (th_match_0_1_V_read - th_match_1_0_V_read);

assign tmp_1095_0_1_0_1_fu_462_p2 = (th_match_0_0_V_read - th_match_2_1_V_read);

assign tmp_1095_0_1_1_1_fu_516_p2 = (th_match_0_1_V_read - th_match_2_1_V_read);

assign tmp_1095_0_1_1_fu_489_p2 = (th_match_0_1_V_read - th_match_2_0_V_read);

assign tmp_1095_0_1_fu_435_p2 = (th_match_0_0_V_read - th_match_2_0_V_read);

assign tmp_1095_0_2_0_1_fu_609_p2 = (th_match_0_0_V_read - th_match_3_1_V_read);

assign tmp_1095_0_2_1_1_fu_663_p2 = (th_match_0_1_V_read - th_match_3_1_V_read);

assign tmp_1095_0_2_1_fu_636_p2 = (th_match_0_1_V_read - th_match_3_0_V_read);

assign tmp_1095_0_2_fu_582_p2 = (th_match_0_0_V_read - th_match_3_0_V_read);

assign tmp_1095_1_0_0_1_fu_756_p2 = (th_match_1_0_V_read - th_match_2_1_V_read);

assign tmp_1095_1_0_1_1_fu_810_p2 = (th_match_1_1_V_read - th_match_2_1_V_read);

assign tmp_1095_1_0_1_fu_783_p2 = (th_match_1_1_V_read - th_match_2_0_V_read);

assign tmp_1095_1_1_0_1_fu_903_p2 = (th_match_1_0_V_read - th_match_3_1_V_read);

assign tmp_1095_1_1_1_1_fu_957_p2 = (th_match_1_1_V_read - th_match_3_1_V_read);

assign tmp_1095_1_1_1_fu_930_p2 = (th_match_1_1_V_read - th_match_3_0_V_read);

assign tmp_1095_1_1_fu_876_p2 = (th_match_1_0_V_read - th_match_3_0_V_read);

assign tmp_1095_1_fu_729_p2 = (th_match_1_0_V_read - th_match_2_0_V_read);

assign tmp_1095_2_0_0_1_fu_1050_p2 = (th_match_2_0_V_read - th_match_3_1_V_read);

assign tmp_1095_2_0_1_1_fu_1104_p2 = (th_match_2_1_V_read - th_match_3_1_V_read);

assign tmp_1095_2_0_1_fu_1077_p2 = (th_match_2_1_V_read - th_match_3_0_V_read);

assign tmp_1095_2_fu_1023_p2 = (th_match_2_0_V_read - th_match_3_0_V_read);

assign tmp_1096_0_0_0_1_fu_321_p2 = (th_match_1_1_V_read - th_match_0_0_V_read);

assign tmp_1096_0_0_1_1_fu_375_p2 = (th_match_1_1_V_read - th_match_0_1_V_read);

assign tmp_1096_0_0_1_fu_348_p2 = (th_match_1_0_V_read - th_match_0_1_V_read);

assign tmp_1096_0_1_0_1_fu_468_p2 = (th_match_2_1_V_read - th_match_0_0_V_read);

assign tmp_1096_0_1_1_1_fu_522_p2 = (th_match_2_1_V_read - th_match_0_1_V_read);

assign tmp_1096_0_1_1_fu_495_p2 = (th_match_2_0_V_read - th_match_0_1_V_read);

assign tmp_1096_0_1_fu_441_p2 = (th_match_2_0_V_read - th_match_0_0_V_read);

assign tmp_1096_0_2_0_1_fu_615_p2 = (th_match_3_1_V_read - th_match_0_0_V_read);

assign tmp_1096_0_2_1_1_fu_669_p2 = (th_match_3_1_V_read - th_match_0_1_V_read);

assign tmp_1096_0_2_1_fu_642_p2 = (th_match_3_0_V_read - th_match_0_1_V_read);

assign tmp_1096_0_2_fu_588_p2 = (th_match_3_0_V_read - th_match_0_0_V_read);

assign tmp_1096_1_0_0_1_fu_762_p2 = (th_match_2_1_V_read - th_match_1_0_V_read);

assign tmp_1096_1_0_1_1_fu_816_p2 = (th_match_2_1_V_read - th_match_1_1_V_read);

assign tmp_1096_1_0_1_fu_789_p2 = (th_match_2_0_V_read - th_match_1_1_V_read);

assign tmp_1096_1_1_0_1_fu_909_p2 = (th_match_3_1_V_read - th_match_1_0_V_read);

assign tmp_1096_1_1_1_1_fu_963_p2 = (th_match_3_1_V_read - th_match_1_1_V_read);

assign tmp_1096_1_1_1_fu_936_p2 = (th_match_3_0_V_read - th_match_1_1_V_read);

assign tmp_1096_1_1_fu_882_p2 = (th_match_3_0_V_read - th_match_1_0_V_read);

assign tmp_1096_1_fu_735_p2 = (th_match_2_0_V_read - th_match_1_0_V_read);

assign tmp_1096_2_0_0_1_fu_1056_p2 = (th_match_3_1_V_read - th_match_2_0_V_read);

assign tmp_1096_2_0_1_1_fu_1110_p2 = (th_match_3_1_V_read - th_match_2_1_V_read);

assign tmp_1096_2_0_1_fu_1083_p2 = (th_match_3_0_V_read - th_match_2_1_V_read);

assign tmp_1096_2_fu_1029_p2 = (th_match_3_0_V_read - th_match_2_0_V_read);

assign tmp_1125_fu_1566_p3 = vstat_V_4_fu_1528_p2[ap_const_lv32_1];

assign tmp_1126_fu_1574_p3 = vstat_V_4_fu_1528_p2[ap_const_lv32_2];

assign tmp_1127_fu_1582_p1 = call_ret200_sp_best_delta_seg_ch_fu_216_ap_return_3[0:0];

assign tmp_1128_fu_1620_p3 = vstat_V_4_fu_1528_p2[ap_const_lv32_3];

assign tmp_1129_fu_1628_p3 = call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_3[ap_const_lv32_1];

assign tmp_1130_fu_1670_p1 = call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_3[0:0];

assign tmp_1131_fu_1708_p3 = call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_3[ap_const_lv32_1];

assign tmp_1132_fu_1750_p3 = call_ret_sp_best_delta_seg_ch_fu_271_ap_return_3[ap_const_lv32_1];

assign tmp_1133_fu_1792_p1 = call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_3[0:0];

assign tmp_1134_fu_2082_p1 = vstat_V_3_fu_1486_p2[0:0];

assign tmp_206_fu_1436_p2 = (tmp_98_fu_1422_p2 | call_ret_sp_best_delta_seg_ch_fu_271_ap_return_2);

assign tmp_236_fu_288_p2 = (th_match_0_0_V_read - th_match_1_0_V_read);

assign tmp_237_fu_294_p2 = (th_match_1_0_V_read - th_match_0_0_V_read);

assign tmp_238_fu_409_p2 = (ph_match_0_V_read - ph_match_1_V_read);

assign tmp_239_fu_415_p2 = (ph_match_1_V_read - ph_match_0_V_read);

assign tmp_240_fu_1586_p3 = {{1'b1}, {tmp_1127_fu_1582_p1}};

assign tmp_241_fu_1636_p3 = {{1'b1}, {tmp_1129_fu_1628_p3}};

assign tmp_242_fu_1674_p3 = {{ap_const_lv2_2}, {tmp_1130_fu_1670_p1}};

assign tmp_243_fu_1716_p3 = {{1'b1}, {tmp_1131_fu_1708_p3}};

assign tmp_244_fu_1758_p3 = {{ap_const_lv2_2}, {tmp_1132_fu_1750_p3}};

assign tmp_245_fu_1796_p3 = {{ap_const_lv2_3}, {tmp_1133_fu_1792_p1}};

integer ap_tvar_int_0;

always @ (vstat_V_4_fu_1528_p2) begin
    for (ap_tvar_int_0 = 2 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > ap_const_lv32_3 - ap_const_lv32_2) begin
            tmp_246_fu_2086_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_246_fu_2086_p4[ap_tvar_int_0] = vstat_V_4_fu_1528_p2[ap_const_lv32_3 - ap_tvar_int_0];
        end
    end
end

assign tmp_54_fu_1320_p2 = (p_01408_1_fu_1302_p3 | ap_const_lv3_1);

assign tmp_55_fu_1392_p2 = (p_11_cast1_fu_1378_p1 | ap_const_lv3_2);

assign tmp_95_fu_1314_p2 = ((call_ret190_sp_best_delta_seg_ch_fu_238_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_96_fu_1350_p2 = ((call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_97_fu_1386_p2 = ((call_ret180_sp_best_delta_seg_ch_fu_260_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_98_fu_1422_p2 = ((call_ret_sp_best_delta_seg_ch_fu_271_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign tmp_99_fu_1460_p2 = ((r_V_fu_1454_p2 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_fu_1364_p2 = (tmp_96_fu_1350_p2 | call_ret185_sp_best_delta_seg_ch_fu_249_ap_return_2);

assign tmp_s_fu_1280_p2 = ((call_ret195_sp_best_delta_seg_ch_fu_227_ap_return_0 > ap_const_lv7_4) ? 1'b1 : 1'b0);

assign val_assign_0_0_0_1_fu_309_p2 = ((th_match_0_0_V_read > th_match_1_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_1_1_fu_363_p2 = ((th_match_0_1_V_read > th_match_1_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_0_1_fu_336_p2 = ((th_match_0_1_V_read > th_match_1_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_0_1_fu_456_p2 = ((th_match_0_0_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_1_1_fu_510_p2 = ((th_match_0_1_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_1_fu_483_p2 = ((th_match_0_1_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_1_fu_429_p2 = ((th_match_0_0_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_0_1_fu_603_p2 = ((th_match_0_0_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_1_1_fu_657_p2 = ((th_match_0_1_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_1_fu_630_p2 = ((th_match_0_1_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_0_2_fu_576_p2 = ((th_match_0_0_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_0_0_1_fu_750_p2 = ((th_match_1_0_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_0_1_1_fu_804_p2 = ((th_match_1_1_V_read > th_match_2_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_0_1_fu_777_p2 = ((th_match_1_1_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_0_1_fu_897_p2 = ((th_match_1_0_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_1_1_fu_951_p2 = ((th_match_1_1_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_1_fu_924_p2 = ((th_match_1_1_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_1_fu_870_p2 = ((th_match_1_0_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_1_fu_723_p2 = ((th_match_1_0_V_read > th_match_2_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_0_0_1_fu_1044_p2 = ((th_match_2_0_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_0_1_1_fu_1098_p2 = ((th_match_2_1_V_read > th_match_3_1_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_0_1_fu_1071_p2 = ((th_match_2_1_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_2_fu_1017_p2 = ((th_match_2_0_V_read > th_match_3_0_V_read) ? 1'b1 : 1'b0);

assign val_assign_fu_282_p2 = ((th_match_0_0_V_read > th_match_1_0_V_read) ? 1'b1 : 1'b0);

assign vmask1_V_2_fu_1326_p3 = {{1'b1}, {tmp_54_fu_1320_p2}};

assign vmask1_V_fu_1286_p3 = ((p_s_fu_1266_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_5);

assign vmask2_V_fu_1398_p3 = {{1'b1}, {tmp_55_fu_1392_p2}};

assign vstat_V_3_fu_1486_p2 = (tmp_101_fu_1478_p3 | vstat_V_fu_1342_p3);

assign vstat_V_4_fu_1528_p2 = (tmp_104_cast_fu_1524_p1 | vstat_V_3_fu_1486_p2);

assign vstat_V_fu_1342_p3 = ((tmp_95_fu_1314_p2[0:0] === 1'b1) ? p_01408_1_cast_fu_1310_p1 : p_0695_0_01408_1_fu_1334_p3);

endmodule //sp_deltas_m0
