// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sp_ph_pattern_exec (
        ph_pattern_0_bx_V_read,
        ph_pattern_1_bx_V_read,
        ph_pattern_2_bx_V_read,
        ph_pattern_3_bx_V_read,
        ph_pattern_4_bx_V_read,
        ph_pattern_5_bx_V_read,
        ph_pattern_6_bx_V_read,
        ph_pattern_7_bx_V_read,
        ph_pattern_8_bx_V_read,
        st1_V,
        st2_V,
        st3_V,
        st4_V,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_6 = 3'b110;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv4_8 = 4'b1000;

input  [2:0] ph_pattern_0_bx_V_read;
input  [2:0] ph_pattern_1_bx_V_read;
input  [2:0] ph_pattern_2_bx_V_read;
input  [2:0] ph_pattern_3_bx_V_read;
input  [2:0] ph_pattern_4_bx_V_read;
input  [2:0] ph_pattern_5_bx_V_read;
input  [2:0] ph_pattern_6_bx_V_read;
input  [2:0] ph_pattern_7_bx_V_read;
input  [2:0] ph_pattern_8_bx_V_read;
input  [30:0] st1_V;
input  [0:0] st2_V;
input  [14:0] st3_V;
input  [14:0] st4_V;
output  [5:0] ap_return_0;
output  [2:0] ap_return_1;
output  [2:0] ap_return_2;
output  [2:0] ap_return_3;
output  [2:0] ap_return_4;
output  [2:0] ap_return_5;
output  [2:0] ap_return_6;
output  [2:0] ap_return_7;
output  [2:0] ap_return_8;
output  [2:0] ap_return_9;

wire   [7:0] tmp_1105_fu_220_p1;
wire   [7:0] p_Result_s_fu_224_p4;
wire   [3:0] a_st4_V_fu_234_p4;
wire   [0:0] tmp_209_fu_256_p2;
wire   [0:0] tmp_208_fu_250_p2;
wire   [0:0] tmp_207_fu_244_p2;
wire   [0:0] tmp_210_fu_262_p2;
wire   [2:0] p_Result_149_fu_268_p4;
wire   [0:0] tmp_211_fu_278_p2;
wire   [0:0] not_tmp_1_fu_296_p2;
wire   [0:0] tmp_212_fu_284_p2;
wire   [0:0] tmp_171_fu_310_p2;
wire   [2:0] p_tmp_cast_fu_302_p3;
wire   [2:0] tmp_213_fu_290_p2;
wire   [2:0] ph_pattern_0_bx_V_write_assig_fu_316_p3;
wire   [0:0] sel_tmp_fu_346_p2;
wire   [0:0] sel_tmp1_fu_352_p2;
wire   [0:0] sel_tmp2_fu_358_p2;
wire   [0:0] tmp35_fu_370_p2;
wire   [0:0] tmp_fu_364_p2;
wire   [0:0] sel_tmp6_fu_376_p2;
wire   [0:0] tmp_214_fu_324_p2;
wire   [0:0] sel_tmp7_fu_382_p2;
wire   [5:0] qcode_p_0_V_fu_330_p7;
wire   [5:0] sel_tmp35_fu_388_p3;
wire   [7:0] p_Result_881_1_fu_404_p4;
wire   [7:0] tmp_1106_fu_414_p1;
wire   [3:0] tmp_1107_fu_418_p1;
wire   [0:0] tmp_731_1_fu_434_p2;
wire   [0:0] tmp_729_1_fu_428_p2;
wire   [0:0] tmp_728_1_fu_422_p2;
wire   [0:0] tmp_215_fu_440_p2;
wire   [2:0] p_Result_886_1_fu_446_p4;
wire   [0:0] tmp_774_1_fu_456_p2;
wire   [0:0] not_tmp_774_1_fu_474_p2;
wire   [0:0] tmp_775_1_fu_462_p2;
wire   [0:0] tmp_173_fu_488_p2;
wire   [2:0] p_tmp_776_1_cast_fu_480_p3;
wire   [2:0] tmp_776_1_fu_468_p2;
wire   [2:0] ph_pattern_1_bx_V_write_assig_fu_494_p3;
wire   [0:0] sel_tmp77_fu_524_p2;
wire   [0:0] sel_tmp78_fu_530_p2;
wire   [0:0] sel_tmp79_fu_536_p2;
wire   [0:0] tmp37_fu_548_p2;
wire   [0:0] tmp36_fu_542_p2;
wire   [0:0] sel_tmp83_fu_554_p2;
wire   [0:0] tmp_777_1_fu_502_p2;
wire   [0:0] sel_tmp84_fu_560_p2;
wire   [5:0] qcode_p_1_V_fu_508_p7;
wire   [5:0] sel_tmp112_fu_566_p3;
wire   [3:0] p_Result_887_2_fu_582_p4;
wire   [0:0] tmp_734_2_fu_592_p2;
wire   [2:0] p_Result_892_2_fu_598_p4;
wire   [0:0] tmp_774_2_fu_608_p2;
wire   [0:0] not_tmp_774_2_fu_626_p2;
wire   [0:0] tmp_775_2_fu_614_p2;
wire   [0:0] tmp_176_fu_640_p2;
wire   [2:0] p_tmp_776_2_cast_fu_632_p3;
wire   [2:0] tmp_776_2_fu_620_p2;
wire   [2:0] ph_pattern_2_bx_V_write_assig_fu_646_p3;
wire   [0:0] sel_tmp154_fu_676_p2;
wire   [0:0] sel_tmp155_fu_682_p2;
wire   [0:0] sel_tmp156_fu_688_p2;
wire   [0:0] tmp39_fu_700_p2;
wire   [0:0] tmp38_fu_694_p2;
wire   [0:0] sel_tmp160_fu_706_p2;
wire   [0:0] tmp_777_2_fu_654_p2;
wire   [0:0] sel_tmp161_fu_712_p2;
wire   [5:0] qcode_p_2_V_fu_660_p7;
wire   [5:0] sel_tmp167_fu_718_p3;
wire   [3:0] p_Result_893_3_fu_734_p4;
wire   [0:0] tmp_740_3_fu_744_p2;
wire   [2:0] p_Result_898_3_fu_750_p4;
wire   [0:0] tmp_774_3_fu_760_p2;
wire   [0:0] not_tmp_774_3_fu_778_p2;
wire   [0:0] tmp_775_3_fu_766_p2;
wire   [0:0] tmp_179_fu_792_p2;
wire   [2:0] p_tmp_776_3_cast_fu_784_p3;
wire   [2:0] tmp_776_3_fu_772_p2;
wire   [2:0] ph_pattern_3_bx_V_write_assig_fu_798_p3;
wire   [0:0] sel_tmp168_fu_828_p2;
wire   [0:0] sel_tmp169_fu_834_p2;
wire   [0:0] sel_tmp170_fu_840_p2;
wire   [0:0] tmp41_fu_852_p2;
wire   [0:0] tmp40_fu_846_p2;
wire   [0:0] sel_tmp171_fu_858_p2;
wire   [0:0] tmp_777_3_fu_806_p2;
wire   [0:0] sel_tmp172_fu_864_p2;
wire   [5:0] qcode_p_3_V_fu_812_p7;
wire   [5:0] sel_tmp173_fu_870_p3;
wire   [1:0] p_Result_899_4_fu_886_p4;
wire   [3:0] p_Result_900_4_fu_896_p4;
wire   [3:0] tmp_216_fu_912_p2;
wire   [0:0] tmp_746_4_fu_906_p2;
wire   [0:0] tmp_217_fu_918_p2;
wire   [2:0] p_Result_904_4_fu_924_p4;
wire   [0:0] tmp_774_4_fu_934_p2;
wire   [0:0] not_tmp_774_4_fu_952_p2;
wire   [0:0] tmp_775_4_fu_940_p2;
wire   [0:0] tmp_182_fu_966_p2;
wire   [2:0] p_tmp_776_4_cast_fu_958_p3;
wire   [2:0] tmp_776_4_fu_946_p2;
wire   [2:0] ph_pattern_4_bx_V_write_assig_fu_972_p3;
wire   [0:0] sel_tmp174_fu_1002_p2;
wire   [0:0] sel_tmp175_fu_1008_p2;
wire   [0:0] sel_tmp176_fu_1014_p2;
wire   [0:0] tmp43_fu_1026_p2;
wire   [0:0] tmp42_fu_1020_p2;
wire   [0:0] sel_tmp177_fu_1032_p2;
wire   [0:0] tmp_777_4_fu_980_p2;
wire   [0:0] sel_tmp178_fu_1038_p2;
wire   [5:0] qcode_p_4_V_fu_986_p7;
wire   [5:0] sel_tmp179_fu_1044_p3;
wire   [1:0] p_Result_905_5_fu_1060_p4;
wire   [2:0] p_Result_907_5_fu_1080_p4;
wire   [2:0] p_Result_906_5_fu_1070_p4;
wire   [2:0] tmp_218_fu_1096_p2;
wire   [0:0] tmp_752_5_fu_1090_p2;
wire   [0:0] tmp_219_fu_1102_p2;
wire   [2:0] p_Result_910_5_fu_1108_p4;
wire   [0:0] tmp_774_5_fu_1118_p2;
wire   [0:0] not_tmp_774_5_fu_1136_p2;
wire   [0:0] tmp_775_5_fu_1124_p2;
wire   [0:0] tmp_185_fu_1150_p2;
wire   [2:0] p_tmp_776_5_cast_fu_1142_p3;
wire   [2:0] tmp_776_5_fu_1130_p2;
wire   [2:0] ph_pattern_5_bx_V_write_assig_fu_1156_p3;
wire   [0:0] sel_tmp180_fu_1186_p2;
wire   [0:0] sel_tmp181_fu_1192_p2;
wire   [0:0] sel_tmp182_fu_1198_p2;
wire   [0:0] tmp45_fu_1210_p2;
wire   [0:0] tmp44_fu_1204_p2;
wire   [0:0] sel_tmp183_fu_1216_p2;
wire   [0:0] tmp_777_5_fu_1164_p2;
wire   [0:0] sel_tmp184_fu_1222_p2;
wire   [5:0] qcode_p_5_V_fu_1170_p7;
wire   [5:0] sel_tmp185_fu_1228_p3;
wire   [1:0] p_Result_912_6_fu_1254_p4;
wire   [1:0] p_Result_911_6_fu_1244_p4;
wire   [1:0] tmp_220_fu_1272_p2;
wire   [0:0] tmp_1108_fu_1264_p3;
wire   [0:0] tmp_221_fu_1278_p2;
wire   [2:0] p_Result_915_6_fu_1284_p4;
wire   [0:0] tmp_774_6_fu_1294_p2;
wire   [0:0] not_tmp_774_6_fu_1312_p2;
wire   [0:0] tmp_775_6_fu_1300_p2;
wire   [0:0] tmp_188_fu_1326_p2;
wire   [2:0] p_tmp_776_6_cast_fu_1318_p3;
wire   [2:0] tmp_776_6_fu_1306_p2;
wire   [2:0] ph_pattern_6_bx_V_write_assig_fu_1332_p3;
wire   [0:0] sel_tmp186_fu_1362_p2;
wire   [0:0] sel_tmp187_fu_1368_p2;
wire   [0:0] sel_tmp188_fu_1374_p2;
wire   [0:0] tmp47_fu_1386_p2;
wire   [0:0] tmp46_fu_1380_p2;
wire   [0:0] sel_tmp189_fu_1392_p2;
wire   [0:0] tmp_777_6_fu_1340_p2;
wire   [0:0] sel_tmp190_fu_1398_p2;
wire   [5:0] qcode_p_6_V_fu_1346_p7;
wire   [5:0] sel_tmp191_fu_1404_p3;
wire   [1:0] p_Result_917_7_fu_1430_p4;
wire   [1:0] p_Result_916_7_fu_1420_p4;
wire   [1:0] tmp_222_fu_1448_p2;
wire   [0:0] tmp_1109_fu_1440_p3;
wire   [0:0] tmp_223_fu_1454_p2;
wire   [2:0] p_Result_920_7_fu_1460_p4;
wire   [0:0] tmp_774_7_fu_1470_p2;
wire   [0:0] not_tmp_774_7_fu_1488_p2;
wire   [0:0] tmp_775_7_fu_1476_p2;
wire   [0:0] tmp_191_fu_1502_p2;
wire   [2:0] p_tmp_776_7_cast_fu_1494_p3;
wire   [2:0] tmp_776_7_fu_1482_p2;
wire   [2:0] ph_pattern_7_bx_V_write_assig_fu_1508_p3;
wire   [0:0] sel_tmp192_fu_1538_p2;
wire   [0:0] sel_tmp193_fu_1544_p2;
wire   [0:0] sel_tmp194_fu_1550_p2;
wire   [0:0] tmp49_fu_1562_p2;
wire   [0:0] tmp48_fu_1556_p2;
wire   [0:0] sel_tmp195_fu_1568_p2;
wire   [0:0] tmp_777_7_fu_1516_p2;
wire   [0:0] sel_tmp196_fu_1574_p2;
wire   [5:0] qcode_p_7_V_fu_1522_p7;
wire   [5:0] sel_tmp197_fu_1580_p3;
wire   [0:0] tmp_1112_fu_1612_p3;
wire   [0:0] tmp_1111_fu_1604_p3;
wire   [0:0] tmp_1110_fu_1596_p3;
wire   [0:0] tmp_224_fu_1620_p2;
wire   [2:0] p_Result_923_8_fu_1626_p4;
wire   [0:0] tmp_774_8_fu_1636_p2;
wire   [0:0] not_tmp_774_8_fu_1654_p2;
wire   [0:0] tmp_775_8_fu_1642_p2;
wire   [0:0] tmp_194_fu_1668_p2;
wire   [2:0] p_tmp_776_8_cast_fu_1660_p3;
wire   [2:0] tmp_776_8_fu_1648_p2;
wire   [2:0] ph_pattern_8_bx_V_write_assig_fu_1674_p3;
wire   [0:0] sel_tmp198_fu_1704_p2;
wire   [0:0] sel_tmp199_fu_1710_p2;
wire   [0:0] sel_tmp200_fu_1716_p2;
wire   [0:0] tmp51_fu_1728_p2;
wire   [0:0] tmp50_fu_1722_p2;
wire   [0:0] sel_tmp201_fu_1734_p2;
wire   [0:0] tmp_777_8_fu_1682_p2;
wire   [0:0] sel_tmp202_fu_1740_p2;
wire   [5:0] qcode_p_8_V_fu_1688_p7;
wire   [5:0] sel_tmp203_fu_1746_p3;
wire   [5:0] qcode_p_0_V1_fu_396_p3;
wire   [5:0] qcode_p_1_V1_fu_574_p3;
wire   [0:0] tmp_s_fu_1762_p2;
wire   [0:0] not_tmp_s_fu_1768_p2;
wire   [5:0] qcode_p_2_V1_fu_726_p3;
wire   [5:0] qcode_p_3_V1_fu_878_p3;
wire   [0:0] tmp_72_fu_1786_p2;
wire   [5:0] qcode_p_4_V1_fu_1052_p3;
wire   [5:0] qcode_p_5_V1_fu_1236_p3;
wire   [0:0] tmp_74_fu_1808_p2;
wire   [5:0] qcode_p_6_V1_fu_1412_p3;
wire   [5:0] qcode_p_7_V1_fu_1588_p3;
wire   [0:0] tmp_76_fu_1830_p2;
wire   [5:0] p_phi1_fu_1778_p3;
wire   [5:0] p_phi2_fu_1800_p3;
wire   [0:0] tmp_78_fu_1852_p2;
wire   [1:0] tmp_71_cast_fu_1774_p1;
wire   [1:0] tmp_73_fu_1792_p3;
wire   [1:0] tmp_79_fu_1858_p3;
wire   [0:0] sel_tmp204_fu_1870_p2;
wire   [0:0] sel_tmp206_fu_1884_p2;
wire   [5:0] sel_tmp205_fu_1876_p3;
wire   [0:0] sel_tmp208_fu_1898_p2;
wire   [5:0] sel_tmp207_fu_1890_p3;
wire   [5:0] p_phi3_fu_1822_p3;
wire   [5:0] p_phi4_fu_1844_p3;
wire   [0:0] tmp_80_fu_1912_p2;
wire   [2:0] tmp_75_fu_1814_p3;
wire   [2:0] tmp_77_cast_cast_fu_1836_p3;
wire   [2:0] tmp_81_fu_1918_p3;
wire   [0:0] sel_tmp209_fu_1926_p2;
wire   [0:0] sel_tmp211_fu_1940_p2;
wire   [5:0] sel_tmp210_fu_1932_p3;
wire   [0:0] sel_tmp213_fu_1954_p2;
wire   [5:0] sel_tmp212_fu_1946_p3;
wire   [5:0] p_phi5_fu_1904_p3;
wire   [5:0] p_phi6_fu_1960_p3;
wire   [0:0] tmp_82_fu_1968_p2;
wire   [2:0] tmp_79_cast_fu_1866_p1;
wire   [2:0] p_v_fu_1974_p3;
wire   [0:0] sel_tmp214_fu_1986_p2;
wire   [0:0] sel_tmp216_fu_2000_p2;
wire   [5:0] sel_tmp215_fu_1992_p3;
wire   [0:0] sel_tmp218_fu_2014_p2;
wire   [5:0] sel_tmp217_fu_2006_p3;
wire   [0:0] sel_tmp220_fu_2028_p2;
wire   [5:0] sel_tmp219_fu_2020_p3;
wire   [0:0] sel_tmp222_fu_2042_p2;
wire   [5:0] sel_tmp221_fu_2034_p3;
wire   [0:0] sel_tmp224_fu_2056_p2;
wire   [5:0] sel_tmp223_fu_2048_p3;
wire   [0:0] sel_tmp226_fu_2070_p2;
wire   [5:0] sel_tmp225_fu_2062_p3;
wire   [5:0] comp3_V_fu_2076_p3;
wire   [5:0] qcode_p_8_V1_fu_1754_p3;
wire   [0:0] tmp_83_fu_2084_p2;
wire   [3:0] tmp_197_fu_1982_p1;
wire   [3:0] a_qcode_V_fu_2098_p10;
wire   [5:0] a_qcode_V_fu_2098_p11;

sp_mux_9to1_sel4_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 6 ),
    .din4_WIDTH( 6 ),
    .din5_WIDTH( 6 ),
    .din6_WIDTH( 6 ),
    .din7_WIDTH( 6 ),
    .din8_WIDTH( 6 ),
    .din9_WIDTH( 6 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 6 ))
sp_mux_9to1_sel4_6_1_U2602(
    .din1(qcode_p_0_V1_fu_396_p3),
    .din2(qcode_p_1_V1_fu_574_p3),
    .din3(qcode_p_2_V1_fu_726_p3),
    .din4(qcode_p_3_V1_fu_878_p3),
    .din5(qcode_p_4_V1_fu_1052_p3),
    .din6(qcode_p_5_V1_fu_1236_p3),
    .din7(qcode_p_6_V1_fu_1412_p3),
    .din8(qcode_p_7_V1_fu_1588_p3),
    .din9(qcode_p_8_V1_fu_1754_p3),
    .din10(a_qcode_V_fu_2098_p10),
    .dout(a_qcode_V_fu_2098_p11)
);

assign a_qcode_V_fu_2098_p10 = ((tmp_83_fu_2084_p2[0:0] === 1'b1) ? tmp_197_fu_1982_p1 : ap_const_lv4_8);

assign a_st4_V_fu_234_p4 = {{st4_V[ap_const_lv32_A : ap_const_lv32_7]}};

assign ap_return_0 = a_qcode_V_fu_2098_p11;

assign ap_return_1 = ph_pattern_0_bx_V_write_assig_fu_316_p3;

assign ap_return_2 = ph_pattern_1_bx_V_write_assig_fu_494_p3;

assign ap_return_3 = ph_pattern_2_bx_V_write_assig_fu_646_p3;

assign ap_return_4 = ph_pattern_3_bx_V_write_assig_fu_798_p3;

assign ap_return_5 = ph_pattern_4_bx_V_write_assig_fu_972_p3;

assign ap_return_6 = ph_pattern_5_bx_V_write_assig_fu_1156_p3;

assign ap_return_7 = ph_pattern_6_bx_V_write_assig_fu_1332_p3;

assign ap_return_8 = ph_pattern_7_bx_V_write_assig_fu_1508_p3;

assign ap_return_9 = ph_pattern_8_bx_V_write_assig_fu_1674_p3;

assign comp3_V_fu_2076_p3 = ((sel_tmp226_fu_2070_p2[0:0] === 1'b1) ? qcode_p_0_V1_fu_396_p3 : sel_tmp225_fu_2062_p3);

assign not_tmp_1_fu_296_p2 = (tmp_211_fu_278_p2 ^ 1'b1);

assign not_tmp_774_1_fu_474_p2 = (tmp_774_1_fu_456_p2 ^ 1'b1);

assign not_tmp_774_2_fu_626_p2 = (tmp_774_2_fu_608_p2 ^ 1'b1);

assign not_tmp_774_3_fu_778_p2 = (tmp_774_3_fu_760_p2 ^ 1'b1);

assign not_tmp_774_4_fu_952_p2 = (tmp_774_4_fu_934_p2 ^ 1'b1);

assign not_tmp_774_5_fu_1136_p2 = (tmp_774_5_fu_1118_p2 ^ 1'b1);

assign not_tmp_774_6_fu_1312_p2 = (tmp_774_6_fu_1294_p2 ^ 1'b1);

assign not_tmp_774_7_fu_1488_p2 = (tmp_774_7_fu_1470_p2 ^ 1'b1);

assign not_tmp_774_8_fu_1654_p2 = (tmp_774_8_fu_1636_p2 ^ 1'b1);

assign not_tmp_s_fu_1768_p2 = (tmp_s_fu_1762_p2 ^ 1'b1);

assign p_Result_149_fu_268_p4 = {{{tmp_207_fu_244_p2}, {st2_V}}, {tmp_210_fu_262_p2}};

assign p_Result_881_1_fu_404_p4 = {{st1_V[ap_const_lv32_1E : ap_const_lv32_17]}};

assign p_Result_886_1_fu_446_p4 = {{{tmp_728_1_fu_422_p2}, {st2_V}}, {tmp_215_fu_440_p2}};

assign p_Result_887_2_fu_582_p4 = {{st1_V[ap_const_lv32_B : ap_const_lv32_8]}};

assign p_Result_892_2_fu_598_p4 = {{{tmp_734_2_fu_592_p2}, {st2_V}}, {tmp_210_fu_262_p2}};

assign p_Result_893_3_fu_734_p4 = {{st1_V[ap_const_lv32_16 : ap_const_lv32_13]}};

assign p_Result_898_3_fu_750_p4 = {{{tmp_740_3_fu_744_p2}, {st2_V}}, {tmp_215_fu_440_p2}};

assign p_Result_899_4_fu_886_p4 = {{st1_V[ap_const_lv32_D : ap_const_lv32_C]}};

assign p_Result_900_4_fu_896_p4 = {{st3_V[ap_const_lv32_A : ap_const_lv32_7]}};

assign p_Result_904_4_fu_924_p4 = {{{tmp_746_4_fu_906_p2}, {st2_V}}, {tmp_217_fu_918_p2}};

assign p_Result_905_5_fu_1060_p4 = {{st1_V[ap_const_lv32_12 : ap_const_lv32_11]}};

assign p_Result_906_5_fu_1070_p4 = {{st3_V[ap_const_lv32_7 : ap_const_lv32_5]}};

assign p_Result_907_5_fu_1080_p4 = {{st4_V[ap_const_lv32_7 : ap_const_lv32_5]}};

assign p_Result_910_5_fu_1108_p4 = {{{tmp_752_5_fu_1090_p2}, {st2_V}}, {tmp_219_fu_1102_p2}};

assign p_Result_911_6_fu_1244_p4 = {{st3_V[ap_const_lv32_8 : ap_const_lv32_7]}};

assign p_Result_912_6_fu_1254_p4 = {{st4_V[ap_const_lv32_8 : ap_const_lv32_7]}};

assign p_Result_915_6_fu_1284_p4 = {{{tmp_1108_fu_1264_p3}, {st2_V}}, {tmp_221_fu_1278_p2}};

assign p_Result_916_7_fu_1420_p4 = {{st3_V[ap_const_lv32_7 : ap_const_lv32_6]}};

assign p_Result_917_7_fu_1430_p4 = {{st4_V[ap_const_lv32_7 : ap_const_lv32_6]}};

assign p_Result_920_7_fu_1460_p4 = {{{tmp_1109_fu_1440_p3}, {st2_V}}, {tmp_223_fu_1454_p2}};

assign p_Result_923_8_fu_1626_p4 = {{{tmp_1110_fu_1596_p3}, {st2_V}}, {tmp_224_fu_1620_p2}};

assign p_Result_s_fu_224_p4 = {{st3_V[ap_const_lv32_E : ap_const_lv32_7]}};

assign p_phi1_fu_1778_p3 = ((tmp_s_fu_1762_p2[0:0] === 1'b1) ? qcode_p_0_V1_fu_396_p3 : qcode_p_1_V1_fu_574_p3);

assign p_phi2_fu_1800_p3 = ((tmp_72_fu_1786_p2[0:0] === 1'b1) ? qcode_p_2_V1_fu_726_p3 : qcode_p_3_V1_fu_878_p3);

assign p_phi3_fu_1822_p3 = ((tmp_74_fu_1808_p2[0:0] === 1'b1) ? qcode_p_4_V1_fu_1052_p3 : qcode_p_5_V1_fu_1236_p3);

assign p_phi4_fu_1844_p3 = ((tmp_76_fu_1830_p2[0:0] === 1'b1) ? qcode_p_6_V1_fu_1412_p3 : qcode_p_7_V1_fu_1588_p3);

assign p_phi5_fu_1904_p3 = ((sel_tmp208_fu_1898_p2[0:0] === 1'b1) ? qcode_p_0_V1_fu_396_p3 : sel_tmp207_fu_1890_p3);

assign p_phi6_fu_1960_p3 = ((sel_tmp213_fu_1954_p2[0:0] === 1'b1) ? qcode_p_4_V1_fu_1052_p3 : sel_tmp212_fu_1946_p3);

assign p_tmp_776_1_cast_fu_480_p3 = ((not_tmp_774_1_fu_474_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_2_cast_fu_632_p3 = ((not_tmp_774_2_fu_626_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_3_cast_fu_784_p3 = ((not_tmp_774_3_fu_778_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_4_cast_fu_958_p3 = ((not_tmp_774_4_fu_952_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_5_cast_fu_1142_p3 = ((not_tmp_774_5_fu_1136_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_6_cast_fu_1318_p3 = ((not_tmp_774_6_fu_1312_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_7_cast_fu_1494_p3 = ((not_tmp_774_7_fu_1488_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_776_8_cast_fu_1660_p3 = ((not_tmp_774_8_fu_1654_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_tmp_cast_fu_302_p3 = ((not_tmp_1_fu_296_p2[0:0] === 1'b1) ? ap_const_lv3_7 : ap_const_lv3_0);

assign p_v_fu_1974_p3 = ((tmp_82_fu_1968_p2[0:0] === 1'b1) ? tmp_79_cast_fu_1866_p1 : tmp_81_fu_1918_p3);

assign ph_pattern_0_bx_V_write_assig_fu_316_p3 = ((tmp_171_fu_310_p2[0:0] === 1'b1) ? p_tmp_cast_fu_302_p3 : tmp_213_fu_290_p2);

assign ph_pattern_1_bx_V_write_assig_fu_494_p3 = ((tmp_173_fu_488_p2[0:0] === 1'b1) ? p_tmp_776_1_cast_fu_480_p3 : tmp_776_1_fu_468_p2);

assign ph_pattern_2_bx_V_write_assig_fu_646_p3 = ((tmp_176_fu_640_p2[0:0] === 1'b1) ? p_tmp_776_2_cast_fu_632_p3 : tmp_776_2_fu_620_p2);

assign ph_pattern_3_bx_V_write_assig_fu_798_p3 = ((tmp_179_fu_792_p2[0:0] === 1'b1) ? p_tmp_776_3_cast_fu_784_p3 : tmp_776_3_fu_772_p2);

assign ph_pattern_4_bx_V_write_assig_fu_972_p3 = ((tmp_182_fu_966_p2[0:0] === 1'b1) ? p_tmp_776_4_cast_fu_958_p3 : tmp_776_4_fu_946_p2);

assign ph_pattern_5_bx_V_write_assig_fu_1156_p3 = ((tmp_185_fu_1150_p2[0:0] === 1'b1) ? p_tmp_776_5_cast_fu_1142_p3 : tmp_776_5_fu_1130_p2);

assign ph_pattern_6_bx_V_write_assig_fu_1332_p3 = ((tmp_188_fu_1326_p2[0:0] === 1'b1) ? p_tmp_776_6_cast_fu_1318_p3 : tmp_776_6_fu_1306_p2);

assign ph_pattern_7_bx_V_write_assig_fu_1508_p3 = ((tmp_191_fu_1502_p2[0:0] === 1'b1) ? p_tmp_776_7_cast_fu_1494_p3 : tmp_776_7_fu_1482_p2);

assign ph_pattern_8_bx_V_write_assig_fu_1674_p3 = ((tmp_194_fu_1668_p2[0:0] === 1'b1) ? p_tmp_776_8_cast_fu_1660_p3 : tmp_776_8_fu_1648_p2);

assign qcode_p_0_V1_fu_396_p3 = ((tmp_214_fu_324_p2[0:0] === 1'b1) ? sel_tmp35_fu_388_p3 : ap_const_lv6_0);

assign qcode_p_0_V_fu_330_p7 = {{{{{{{{{{1'b0}, {tmp_207_fu_244_p2}}}, {1'b0}}}, {st2_V}}}, {1'b0}}}, {tmp_210_fu_262_p2}};

assign qcode_p_1_V1_fu_574_p3 = ((tmp_777_1_fu_502_p2[0:0] === 1'b1) ? sel_tmp112_fu_566_p3 : ap_const_lv6_0);

assign qcode_p_1_V_fu_508_p7 = {{{{{{{{{{1'b0}, {tmp_728_1_fu_422_p2}}}, {1'b0}}}, {st2_V}}}, {1'b0}}}, {tmp_215_fu_440_p2}};

assign qcode_p_2_V1_fu_726_p3 = ((tmp_777_2_fu_654_p2[0:0] === 1'b1) ? sel_tmp167_fu_718_p3 : ap_const_lv6_0);

assign qcode_p_2_V_fu_660_p7 = {{{{{{{{{{1'b0}, {tmp_734_2_fu_592_p2}}}, {1'b0}}}, {st2_V}}}, {1'b1}}}, {tmp_210_fu_262_p2}};

assign qcode_p_3_V1_fu_878_p3 = ((tmp_777_3_fu_806_p2[0:0] === 1'b1) ? sel_tmp173_fu_870_p3 : ap_const_lv6_0);

assign qcode_p_3_V_fu_812_p7 = {{{{{{{{{{1'b0}, {tmp_740_3_fu_744_p2}}}, {1'b0}}}, {st2_V}}}, {1'b1}}}, {tmp_215_fu_440_p2}};

assign qcode_p_4_V1_fu_1052_p3 = ((tmp_777_4_fu_980_p2[0:0] === 1'b1) ? sel_tmp179_fu_1044_p3 : ap_const_lv6_0);

assign qcode_p_4_V_fu_986_p7 = {{{{{{{{{{1'b0}, {tmp_746_4_fu_906_p2}}}, {1'b1}}}, {st2_V}}}, {1'b0}}}, {tmp_217_fu_918_p2}};

assign qcode_p_5_V1_fu_1236_p3 = ((tmp_777_5_fu_1164_p2[0:0] === 1'b1) ? sel_tmp185_fu_1228_p3 : ap_const_lv6_0);

assign qcode_p_5_V_fu_1170_p7 = {{{{{{{{{{1'b0}, {tmp_752_5_fu_1090_p2}}}, {1'b1}}}, {st2_V}}}, {1'b0}}}, {tmp_219_fu_1102_p2}};

assign qcode_p_6_V1_fu_1412_p3 = ((tmp_777_6_fu_1340_p2[0:0] === 1'b1) ? sel_tmp191_fu_1404_p3 : ap_const_lv6_0);

assign qcode_p_6_V_fu_1346_p7 = {{{{{{{{{{1'b0}, {tmp_1108_fu_1264_p3}}}, {1'b1}}}, {st2_V}}}, {1'b1}}}, {tmp_221_fu_1278_p2}};

assign qcode_p_7_V1_fu_1588_p3 = ((tmp_777_7_fu_1516_p2[0:0] === 1'b1) ? sel_tmp197_fu_1580_p3 : ap_const_lv6_0);

assign qcode_p_7_V_fu_1522_p7 = {{{{{{{{{{1'b0}, {tmp_1109_fu_1440_p3}}}, {1'b1}}}, {st2_V}}}, {1'b1}}}, {tmp_223_fu_1454_p2}};

assign qcode_p_8_V1_fu_1754_p3 = ((tmp_777_8_fu_1682_p2[0:0] === 1'b1) ? sel_tmp203_fu_1746_p3 : ap_const_lv6_0);

assign qcode_p_8_V_fu_1688_p7 = {{{{{{{{{{1'b1}, {tmp_1110_fu_1596_p3}}}, {1'b0}}}, {st2_V}}}, {1'b0}}}, {tmp_224_fu_1620_p2}};

assign sel_tmp112_fu_566_p3 = ((sel_tmp84_fu_560_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_1_V_fu_508_p7);

assign sel_tmp154_fu_676_p2 = ((p_Result_892_2_fu_598_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp155_fu_682_p2 = ((p_Result_892_2_fu_598_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp156_fu_688_p2 = ((p_Result_892_2_fu_598_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp160_fu_706_p2 = (tmp39_fu_700_p2 | tmp38_fu_694_p2);

assign sel_tmp161_fu_712_p2 = (sel_tmp160_fu_706_p2 & tmp_777_2_fu_654_p2);

assign sel_tmp167_fu_718_p3 = ((sel_tmp161_fu_712_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_2_V_fu_660_p7);

assign sel_tmp168_fu_828_p2 = ((p_Result_898_3_fu_750_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp169_fu_834_p2 = ((p_Result_898_3_fu_750_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp170_fu_840_p2 = ((p_Result_898_3_fu_750_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp171_fu_858_p2 = (tmp41_fu_852_p2 | tmp40_fu_846_p2);

assign sel_tmp172_fu_864_p2 = (sel_tmp171_fu_858_p2 & tmp_777_3_fu_806_p2);

assign sel_tmp173_fu_870_p3 = ((sel_tmp172_fu_864_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_3_V_fu_812_p7);

assign sel_tmp174_fu_1002_p2 = ((p_Result_904_4_fu_924_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp175_fu_1008_p2 = ((p_Result_904_4_fu_924_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp176_fu_1014_p2 = ((p_Result_904_4_fu_924_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp177_fu_1032_p2 = (tmp43_fu_1026_p2 | tmp42_fu_1020_p2);

assign sel_tmp178_fu_1038_p2 = (sel_tmp177_fu_1032_p2 & tmp_777_4_fu_980_p2);

assign sel_tmp179_fu_1044_p3 = ((sel_tmp178_fu_1038_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_4_V_fu_986_p7);

assign sel_tmp180_fu_1186_p2 = ((p_Result_910_5_fu_1108_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp181_fu_1192_p2 = ((p_Result_910_5_fu_1108_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp182_fu_1198_p2 = ((p_Result_910_5_fu_1108_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp183_fu_1216_p2 = (tmp45_fu_1210_p2 | tmp44_fu_1204_p2);

assign sel_tmp184_fu_1222_p2 = (sel_tmp183_fu_1216_p2 & tmp_777_5_fu_1164_p2);

assign sel_tmp185_fu_1228_p3 = ((sel_tmp184_fu_1222_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_5_V_fu_1170_p7);

assign sel_tmp186_fu_1362_p2 = ((p_Result_915_6_fu_1284_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp187_fu_1368_p2 = ((p_Result_915_6_fu_1284_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp188_fu_1374_p2 = ((p_Result_915_6_fu_1284_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp189_fu_1392_p2 = (tmp47_fu_1386_p2 | tmp46_fu_1380_p2);

assign sel_tmp190_fu_1398_p2 = (sel_tmp189_fu_1392_p2 & tmp_777_6_fu_1340_p2);

assign sel_tmp191_fu_1404_p3 = ((sel_tmp190_fu_1398_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_6_V_fu_1346_p7);

assign sel_tmp192_fu_1538_p2 = ((p_Result_920_7_fu_1460_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp193_fu_1544_p2 = ((p_Result_920_7_fu_1460_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp194_fu_1550_p2 = ((p_Result_920_7_fu_1460_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp195_fu_1568_p2 = (tmp49_fu_1562_p2 | tmp48_fu_1556_p2);

assign sel_tmp196_fu_1574_p2 = (sel_tmp195_fu_1568_p2 & tmp_777_7_fu_1516_p2);

assign sel_tmp197_fu_1580_p3 = ((sel_tmp196_fu_1574_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_7_V_fu_1522_p7);

assign sel_tmp198_fu_1704_p2 = ((p_Result_923_8_fu_1626_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp199_fu_1710_p2 = ((p_Result_923_8_fu_1626_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp1_fu_352_p2 = ((p_Result_149_fu_268_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp200_fu_1716_p2 = ((p_Result_923_8_fu_1626_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp201_fu_1734_p2 = (tmp51_fu_1728_p2 | tmp50_fu_1722_p2);

assign sel_tmp202_fu_1740_p2 = (sel_tmp201_fu_1734_p2 & tmp_777_8_fu_1682_p2);

assign sel_tmp203_fu_1746_p3 = ((sel_tmp202_fu_1740_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_8_V_fu_1688_p7);

assign sel_tmp204_fu_1870_p2 = ((tmp_79_fu_1858_p3 == ap_const_lv2_1) ? 1'b1 : 1'b0);

assign sel_tmp205_fu_1876_p3 = ((sel_tmp204_fu_1870_p2[0:0] === 1'b1) ? qcode_p_1_V1_fu_574_p3 : qcode_p_3_V1_fu_878_p3);

assign sel_tmp206_fu_1884_p2 = ((tmp_79_fu_1858_p3 == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign sel_tmp207_fu_1890_p3 = ((sel_tmp206_fu_1884_p2[0:0] === 1'b1) ? qcode_p_2_V1_fu_726_p3 : sel_tmp205_fu_1876_p3);

assign sel_tmp208_fu_1898_p2 = ((tmp_79_fu_1858_p3 == ap_const_lv2_0) ? 1'b1 : 1'b0);

assign sel_tmp209_fu_1926_p2 = ((tmp_81_fu_1918_p3 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign sel_tmp210_fu_1932_p3 = ((sel_tmp209_fu_1926_p2[0:0] === 1'b1) ? qcode_p_5_V1_fu_1236_p3 : qcode_p_7_V1_fu_1588_p3);

assign sel_tmp211_fu_1940_p2 = ((tmp_81_fu_1918_p3 == ap_const_lv3_6) ? 1'b1 : 1'b0);

assign sel_tmp212_fu_1946_p3 = ((sel_tmp211_fu_1940_p2[0:0] === 1'b1) ? qcode_p_6_V1_fu_1412_p3 : sel_tmp210_fu_1932_p3);

assign sel_tmp213_fu_1954_p2 = ((tmp_81_fu_1918_p3 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp214_fu_1986_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp215_fu_1992_p3 = ((sel_tmp214_fu_1986_p2[0:0] === 1'b1) ? qcode_p_1_V1_fu_574_p3 : qcode_p_7_V1_fu_1588_p3);

assign sel_tmp216_fu_2000_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp217_fu_2006_p3 = ((sel_tmp216_fu_2000_p2[0:0] === 1'b1) ? qcode_p_2_V1_fu_726_p3 : sel_tmp215_fu_1992_p3);

assign sel_tmp218_fu_2014_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign sel_tmp219_fu_2020_p3 = ((sel_tmp218_fu_2014_p2[0:0] === 1'b1) ? qcode_p_3_V1_fu_878_p3 : sel_tmp217_fu_2006_p3);

assign sel_tmp220_fu_2028_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp221_fu_2034_p3 = ((sel_tmp220_fu_2028_p2[0:0] === 1'b1) ? qcode_p_4_V1_fu_1052_p3 : sel_tmp219_fu_2020_p3);

assign sel_tmp222_fu_2042_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign sel_tmp223_fu_2048_p3 = ((sel_tmp222_fu_2042_p2[0:0] === 1'b1) ? qcode_p_5_V1_fu_1236_p3 : sel_tmp221_fu_2034_p3);

assign sel_tmp224_fu_2056_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_6) ? 1'b1 : 1'b0);

assign sel_tmp225_fu_2062_p3 = ((sel_tmp224_fu_2056_p2[0:0] === 1'b1) ? qcode_p_6_V1_fu_1412_p3 : sel_tmp223_fu_2048_p3);

assign sel_tmp226_fu_2070_p2 = ((p_v_fu_1974_p3 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_358_p2 = ((p_Result_149_fu_268_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp35_fu_388_p3 = ((sel_tmp7_fu_382_p2[0:0] === 1'b1) ? ap_const_lv6_0 : qcode_p_0_V_fu_330_p7);

assign sel_tmp6_fu_376_p2 = (tmp35_fu_370_p2 | tmp_fu_364_p2);

assign sel_tmp77_fu_524_p2 = ((p_Result_886_1_fu_446_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp78_fu_530_p2 = ((p_Result_886_1_fu_446_p4 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp79_fu_536_p2 = ((p_Result_886_1_fu_446_p4 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp7_fu_382_p2 = (sel_tmp6_fu_376_p2 & tmp_214_fu_324_p2);

assign sel_tmp83_fu_554_p2 = (tmp37_fu_548_p2 | tmp36_fu_542_p2);

assign sel_tmp84_fu_560_p2 = (sel_tmp83_fu_554_p2 & tmp_777_1_fu_502_p2);

assign sel_tmp_fu_346_p2 = ((p_Result_149_fu_268_p4 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign tmp35_fu_370_p2 = (sel_tmp2_fu_358_p2 | tmp_211_fu_278_p2);

assign tmp36_fu_542_p2 = (sel_tmp77_fu_524_p2 | sel_tmp78_fu_530_p2);

assign tmp37_fu_548_p2 = (sel_tmp79_fu_536_p2 | tmp_774_1_fu_456_p2);

assign tmp38_fu_694_p2 = (sel_tmp154_fu_676_p2 | sel_tmp155_fu_682_p2);

assign tmp39_fu_700_p2 = (sel_tmp156_fu_688_p2 | tmp_774_2_fu_608_p2);

assign tmp40_fu_846_p2 = (sel_tmp168_fu_828_p2 | sel_tmp169_fu_834_p2);

assign tmp41_fu_852_p2 = (sel_tmp170_fu_840_p2 | tmp_774_3_fu_760_p2);

assign tmp42_fu_1020_p2 = (sel_tmp174_fu_1002_p2 | sel_tmp175_fu_1008_p2);

assign tmp43_fu_1026_p2 = (sel_tmp176_fu_1014_p2 | tmp_774_4_fu_934_p2);

assign tmp44_fu_1204_p2 = (sel_tmp180_fu_1186_p2 | sel_tmp181_fu_1192_p2);

assign tmp45_fu_1210_p2 = (sel_tmp182_fu_1198_p2 | tmp_774_5_fu_1118_p2);

assign tmp46_fu_1380_p2 = (sel_tmp186_fu_1362_p2 | sel_tmp187_fu_1368_p2);

assign tmp47_fu_1386_p2 = (sel_tmp188_fu_1374_p2 | tmp_774_6_fu_1294_p2);

assign tmp48_fu_1556_p2 = (sel_tmp192_fu_1538_p2 | sel_tmp193_fu_1544_p2);

assign tmp49_fu_1562_p2 = (sel_tmp194_fu_1550_p2 | tmp_774_7_fu_1470_p2);

assign tmp50_fu_1722_p2 = (sel_tmp198_fu_1704_p2 | sel_tmp199_fu_1710_p2);

assign tmp51_fu_1728_p2 = (sel_tmp200_fu_1716_p2 | tmp_774_8_fu_1636_p2);

assign tmp_1105_fu_220_p1 = st1_V[7:0];

assign tmp_1106_fu_414_p1 = st3_V[7:0];

assign tmp_1107_fu_418_p1 = st4_V[3:0];

assign tmp_1108_fu_1264_p3 = st1_V[ap_const_lv32_E];

assign tmp_1109_fu_1440_p3 = st1_V[ap_const_lv32_10];

assign tmp_1110_fu_1596_p3 = st1_V[ap_const_lv32_F];

assign tmp_1111_fu_1604_p3 = st3_V[ap_const_lv32_7];

assign tmp_1112_fu_1612_p3 = st4_V[ap_const_lv32_7];

assign tmp_171_fu_310_p2 = (tmp_211_fu_278_p2 | tmp_212_fu_284_p2);

assign tmp_173_fu_488_p2 = (tmp_774_1_fu_456_p2 | tmp_775_1_fu_462_p2);

assign tmp_176_fu_640_p2 = (tmp_774_2_fu_608_p2 | tmp_775_2_fu_614_p2);

assign tmp_179_fu_792_p2 = (tmp_774_3_fu_760_p2 | tmp_775_3_fu_766_p2);

assign tmp_182_fu_966_p2 = (tmp_774_4_fu_934_p2 | tmp_775_4_fu_940_p2);

assign tmp_185_fu_1150_p2 = (tmp_774_5_fu_1118_p2 | tmp_775_5_fu_1124_p2);

assign tmp_188_fu_1326_p2 = (tmp_774_6_fu_1294_p2 | tmp_775_6_fu_1300_p2);

assign tmp_191_fu_1502_p2 = (tmp_774_7_fu_1470_p2 | tmp_775_7_fu_1476_p2);

assign tmp_194_fu_1668_p2 = (tmp_774_8_fu_1636_p2 | tmp_775_8_fu_1642_p2);

assign tmp_197_fu_1982_p1 = p_v_fu_1974_p3;

assign tmp_207_fu_244_p2 = ((tmp_1105_fu_220_p1 != ap_const_lv8_0) ? 1'b1 : 1'b0);

assign tmp_208_fu_250_p2 = ((p_Result_s_fu_224_p4 != ap_const_lv8_0) ? 1'b1 : 1'b0);

assign tmp_209_fu_256_p2 = ((a_st4_V_fu_234_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_210_fu_262_p2 = (tmp_209_fu_256_p2 | tmp_208_fu_250_p2);

assign tmp_211_fu_278_p2 = ((p_Result_149_fu_268_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_212_fu_284_p2 = ((ph_pattern_0_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_213_fu_290_p2 = (ap_const_lv3_1 + ph_pattern_0_bx_V_read);

assign tmp_214_fu_324_p2 = ((ph_pattern_0_bx_V_write_assig_fu_316_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_215_fu_440_p2 = (tmp_731_1_fu_434_p2 | tmp_729_1_fu_428_p2);

assign tmp_216_fu_912_p2 = (a_st4_V_fu_234_p4 | p_Result_900_4_fu_896_p4);

assign tmp_217_fu_918_p2 = ((tmp_216_fu_912_p2 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_218_fu_1096_p2 = (p_Result_907_5_fu_1080_p4 | p_Result_906_5_fu_1070_p4);

assign tmp_219_fu_1102_p2 = ((tmp_218_fu_1096_p2 != ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_220_fu_1272_p2 = (p_Result_912_6_fu_1254_p4 | p_Result_911_6_fu_1244_p4);

assign tmp_221_fu_1278_p2 = ((tmp_220_fu_1272_p2 != ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_222_fu_1448_p2 = (p_Result_917_7_fu_1430_p4 | p_Result_916_7_fu_1420_p4);

assign tmp_223_fu_1454_p2 = ((tmp_222_fu_1448_p2 != ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_224_fu_1620_p2 = (tmp_1112_fu_1612_p3 | tmp_1111_fu_1604_p3);

assign tmp_71_cast_fu_1774_p1 = not_tmp_s_fu_1768_p2;

assign tmp_728_1_fu_422_p2 = ((p_Result_881_1_fu_404_p4 != ap_const_lv8_0) ? 1'b1 : 1'b0);

assign tmp_729_1_fu_428_p2 = ((tmp_1106_fu_414_p1 != ap_const_lv8_0) ? 1'b1 : 1'b0);

assign tmp_72_fu_1786_p2 = ((qcode_p_2_V1_fu_726_p3 > qcode_p_3_V1_fu_878_p3) ? 1'b1 : 1'b0);

assign tmp_731_1_fu_434_p2 = ((tmp_1107_fu_418_p1 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_734_2_fu_592_p2 = ((p_Result_887_2_fu_582_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_73_fu_1792_p3 = ((tmp_72_fu_1786_p2[0:0] === 1'b1) ? ap_const_lv2_2 : ap_const_lv2_3);

assign tmp_740_3_fu_744_p2 = ((p_Result_893_3_fu_734_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_746_4_fu_906_p2 = ((p_Result_899_4_fu_886_p4 != ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_74_fu_1808_p2 = ((qcode_p_4_V1_fu_1052_p3 > qcode_p_5_V1_fu_1236_p3) ? 1'b1 : 1'b0);

assign tmp_752_5_fu_1090_p2 = ((p_Result_905_5_fu_1060_p4 != ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_75_fu_1814_p3 = ((tmp_74_fu_1808_p2[0:0] === 1'b1) ? ap_const_lv3_4 : ap_const_lv3_5);

assign tmp_76_fu_1830_p2 = ((qcode_p_6_V1_fu_1412_p3 > qcode_p_7_V1_fu_1588_p3) ? 1'b1 : 1'b0);

assign tmp_774_1_fu_456_p2 = ((p_Result_886_1_fu_446_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_2_fu_608_p2 = ((p_Result_892_2_fu_598_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_3_fu_760_p2 = ((p_Result_898_3_fu_750_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_4_fu_934_p2 = ((p_Result_904_4_fu_924_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_5_fu_1118_p2 = ((p_Result_910_5_fu_1108_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_6_fu_1294_p2 = ((p_Result_915_6_fu_1284_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_7_fu_1470_p2 = ((p_Result_920_7_fu_1460_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_774_8_fu_1636_p2 = ((p_Result_923_8_fu_1626_p4 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_775_1_fu_462_p2 = ((ph_pattern_1_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_2_fu_614_p2 = ((ph_pattern_2_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_3_fu_766_p2 = ((ph_pattern_3_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_4_fu_940_p2 = ((ph_pattern_4_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_5_fu_1124_p2 = ((ph_pattern_5_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_6_fu_1300_p2 = ((ph_pattern_6_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_7_fu_1476_p2 = ((ph_pattern_7_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_775_8_fu_1642_p2 = ((ph_pattern_8_bx_V_read == ap_const_lv3_7) ? 1'b1 : 1'b0);

assign tmp_776_1_fu_468_p2 = (ap_const_lv3_1 + ph_pattern_1_bx_V_read);

assign tmp_776_2_fu_620_p2 = (ap_const_lv3_1 + ph_pattern_2_bx_V_read);

assign tmp_776_3_fu_772_p2 = (ap_const_lv3_1 + ph_pattern_3_bx_V_read);

assign tmp_776_4_fu_946_p2 = (ap_const_lv3_1 + ph_pattern_4_bx_V_read);

assign tmp_776_5_fu_1130_p2 = (ap_const_lv3_1 + ph_pattern_5_bx_V_read);

assign tmp_776_6_fu_1306_p2 = (ap_const_lv3_1 + ph_pattern_6_bx_V_read);

assign tmp_776_7_fu_1482_p2 = (ap_const_lv3_1 + ph_pattern_7_bx_V_read);

assign tmp_776_8_fu_1648_p2 = (ap_const_lv3_1 + ph_pattern_8_bx_V_read);

assign tmp_777_1_fu_502_p2 = ((ph_pattern_1_bx_V_write_assig_fu_494_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_2_fu_654_p2 = ((ph_pattern_2_bx_V_write_assig_fu_646_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_3_fu_806_p2 = ((ph_pattern_3_bx_V_write_assig_fu_798_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_4_fu_980_p2 = ((ph_pattern_4_bx_V_write_assig_fu_972_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_5_fu_1164_p2 = ((ph_pattern_5_bx_V_write_assig_fu_1156_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_6_fu_1340_p2 = ((ph_pattern_6_bx_V_write_assig_fu_1332_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_7_fu_1516_p2 = ((ph_pattern_7_bx_V_write_assig_fu_1508_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_777_8_fu_1682_p2 = ((ph_pattern_8_bx_V_write_assig_fu_1674_p3 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign tmp_77_cast_cast_fu_1836_p3 = ((tmp_76_fu_1830_p2[0:0] === 1'b1) ? ap_const_lv3_6 : ap_const_lv3_7);

assign tmp_78_fu_1852_p2 = ((p_phi1_fu_1778_p3 > p_phi2_fu_1800_p3) ? 1'b1 : 1'b0);

assign tmp_79_cast_fu_1866_p1 = tmp_79_fu_1858_p3;

assign tmp_79_fu_1858_p3 = ((tmp_78_fu_1852_p2[0:0] === 1'b1) ? tmp_71_cast_fu_1774_p1 : tmp_73_fu_1792_p3);

assign tmp_80_fu_1912_p2 = ((p_phi3_fu_1822_p3 > p_phi4_fu_1844_p3) ? 1'b1 : 1'b0);

assign tmp_81_fu_1918_p3 = ((tmp_80_fu_1912_p2[0:0] === 1'b1) ? tmp_75_fu_1814_p3 : tmp_77_cast_cast_fu_1836_p3);

assign tmp_82_fu_1968_p2 = ((p_phi5_fu_1904_p3 > p_phi6_fu_1960_p3) ? 1'b1 : 1'b0);

assign tmp_83_fu_2084_p2 = ((comp3_V_fu_2076_p3 > qcode_p_8_V1_fu_1754_p3) ? 1'b1 : 1'b0);

assign tmp_fu_364_p2 = (sel_tmp_fu_346_p2 | sel_tmp1_fu_352_p2);

assign tmp_s_fu_1762_p2 = ((qcode_p_0_V1_fu_396_p3 > qcode_p_1_V1_fu_574_p3) ? 1'b1 : 1'b0);

endmodule //sp_ph_pattern_exec
