// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sp_prim_conv1 (
        primitive_0_params_V_read,
        primitive_1_params_V_read,
        primitive_2_params_V_read,
        primitive_0_th_mem_V_read,
        primitive_1_th_mem_V_read,
        primitive_2_th_mem_V_read,
        primitive_3_th_mem_V_read,
        primitive_4_th_mem_V_read,
        primitive_5_th_mem_V_read,
        primitive_6_th_mem_V_read,
        primitive_7_th_mem_V_read,
        primitive_8_th_mem_V_read,
        primitive_9_th_mem_V_read,
        primitive_10_th_mem_V_read,
        primitive_11_th_mem_V_read,
        primitive_12_th_mem_V_read,
        primitive_13_th_mem_V_read,
        primitive_14_th_mem_V_read,
        primitive_15_th_mem_V_read,
        primitive_16_th_mem_V_read,
        primitive_17_th_mem_V_read,
        primitive_18_th_mem_V_read,
        primitive_19_th_mem_V_read,
        primitive_20_th_mem_V_read,
        primitive_21_th_mem_V_read,
        primitive_22_th_mem_V_read,
        primitive_23_th_mem_V_read,
        primitive_24_th_mem_V_read,
        primitive_25_th_mem_V_read,
        primitive_26_th_mem_V_read,
        primitive_27_th_mem_V_read,
        primitive_28_th_mem_V_read,
        primitive_29_th_mem_V_read,
        primitive_30_th_mem_V_read,
        primitive_31_th_mem_V_read,
        primitive_32_th_mem_V_read,
        primitive_33_th_mem_V_read,
        primitive_34_th_mem_V_read,
        primitive_35_th_mem_V_read,
        primitive_36_th_mem_V_read,
        primitive_37_th_mem_V_read,
        primitive_38_th_mem_V_read,
        primitive_39_th_mem_V_read,
        primitive_40_th_mem_V_read,
        primitive_41_th_mem_V_read,
        primitive_42_th_mem_V_read,
        primitive_43_th_mem_V_read,
        primitive_44_th_mem_V_read,
        primitive_45_th_mem_V_read,
        primitive_46_th_mem_V_read,
        primitive_47_th_mem_V_read,
        primitive_48_th_mem_V_read,
        primitive_49_th_mem_V_read,
        primitive_50_th_mem_V_read,
        primitive_51_th_mem_V_read,
        primitive_52_th_mem_V_read,
        primitive_53_th_mem_V_read,
        primitive_54_th_mem_V_read,
        primitive_55_th_mem_V_read,
        primitive_56_th_mem_V_read,
        primitive_57_th_mem_V_read,
        primitive_58_th_mem_V_read,
        primitive_59_th_mem_V_read,
        primitive_60_th_mem_V_read,
        primitive_61_th_mem_V_read,
        primitive_62_th_mem_V_read,
        primitive_63_th_mem_V_read,
        primitive_64_th_mem_V_read,
        primitive_65_th_mem_V_read,
        primitive_66_th_mem_V_read,
        primitive_67_th_mem_V_read,
        primitive_68_th_mem_V_read,
        primitive_69_th_mem_V_read,
        primitive_70_th_mem_V_read,
        primitive_71_th_mem_V_read,
        primitive_72_th_mem_V_read,
        primitive_73_th_mem_V_read,
        primitive_74_th_mem_V_read,
        primitive_75_th_mem_V_read,
        primitive_76_th_mem_V_read,
        primitive_77_th_mem_V_read,
        primitive_78_th_mem_V_read,
        primitive_79_th_mem_V_read,
        primitive_80_th_mem_V_read,
        primitive_81_th_mem_V_read,
        primitive_82_th_mem_V_read,
        primitive_83_th_mem_V_read,
        primitive_84_th_mem_V_read,
        primitive_85_th_mem_V_read,
        primitive_86_th_mem_V_read,
        primitive_87_th_mem_V_read,
        primitive_88_th_mem_V_read,
        primitive_89_th_mem_V_read,
        primitive_90_th_mem_V_read,
        primitive_91_th_mem_V_read,
        primitive_92_th_mem_V_read,
        primitive_93_th_mem_V_read,
        primitive_94_th_mem_V_read,
        primitive_95_th_mem_V_read,
        primitive_96_th_mem_V_read,
        primitive_97_th_mem_V_read,
        primitive_98_th_mem_V_read,
        primitive_99_th_mem_V_read,
        primitive_100_th_mem_V_read,
        primitive_101_th_mem_V_read,
        primitive_102_th_mem_V_read,
        primitive_103_th_mem_V_read,
        primitive_104_th_mem_V_read,
        primitive_105_th_mem_V_read,
        primitive_106_th_mem_V_read,
        primitive_107_th_mem_V_read,
        primitive_108_th_mem_V_read,
        primitive_109_th_mem_V_read,
        primitive_110_th_mem_V_read,
        primitive_111_th_mem_V_read,
        primitive_112_th_mem_V_read,
        primitive_113_th_mem_V_read,
        primitive_114_th_mem_V_read,
        primitive_115_th_mem_V_read,
        primitive_116_th_mem_V_read,
        primitive_117_th_mem_V_read,
        primitive_118_th_mem_V_read,
        primitive_119_th_mem_V_read,
        primitive_120_th_mem_V_read,
        primitive_121_th_mem_V_read,
        primitive_122_th_mem_V_read,
        primitive_123_th_mem_V_read,
        primitive_124_th_mem_V_read,
        primitive_125_th_mem_V_read,
        primitive_126_th_mem_V_read,
        primitive_127_th_mem_V_read,
        quality_0_V_read,
        quality_1_V_read,
        wiregroup_0_V_read,
        wiregroup_1_V_read,
        hstrip_0_V_read,
        hstrip_1_V_read,
        clctpat_0_V_read,
        clctpat_1_V_read,
        station_V,
        cscid_V,
        endcap_V,
        lat_test_V,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_const_lv4_5 = 4'b101;
parameter    ap_const_lv8_F = 8'b1111;
parameter    ap_const_lv8_14 = 8'b10100;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_7 = 4'b111;
parameter    ap_const_lv4_6 = 4'b110;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv12_800 = 12'b100000000000;
parameter    ap_const_lv44_0 = 44'b00000000000000000000000000000000000000000000;
parameter    ap_const_lv44_400000 = 44'b10000000000000000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv7_7D = 7'b1111101;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv7_7E = 7'b1111110;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv22_3B3 = 22'b1110110011;

input  [11:0] primitive_0_params_V_read;
input  [11:0] primitive_1_params_V_read;
input  [11:0] primitive_2_params_V_read;
input  [11:0] primitive_0_th_mem_V_read;
input  [11:0] primitive_1_th_mem_V_read;
input  [11:0] primitive_2_th_mem_V_read;
input  [11:0] primitive_3_th_mem_V_read;
input  [11:0] primitive_4_th_mem_V_read;
input  [11:0] primitive_5_th_mem_V_read;
input  [11:0] primitive_6_th_mem_V_read;
input  [11:0] primitive_7_th_mem_V_read;
input  [11:0] primitive_8_th_mem_V_read;
input  [11:0] primitive_9_th_mem_V_read;
input  [11:0] primitive_10_th_mem_V_read;
input  [11:0] primitive_11_th_mem_V_read;
input  [11:0] primitive_12_th_mem_V_read;
input  [11:0] primitive_13_th_mem_V_read;
input  [11:0] primitive_14_th_mem_V_read;
input  [11:0] primitive_15_th_mem_V_read;
input  [11:0] primitive_16_th_mem_V_read;
input  [11:0] primitive_17_th_mem_V_read;
input  [11:0] primitive_18_th_mem_V_read;
input  [11:0] primitive_19_th_mem_V_read;
input  [11:0] primitive_20_th_mem_V_read;
input  [11:0] primitive_21_th_mem_V_read;
input  [11:0] primitive_22_th_mem_V_read;
input  [11:0] primitive_23_th_mem_V_read;
input  [11:0] primitive_24_th_mem_V_read;
input  [11:0] primitive_25_th_mem_V_read;
input  [11:0] primitive_26_th_mem_V_read;
input  [11:0] primitive_27_th_mem_V_read;
input  [11:0] primitive_28_th_mem_V_read;
input  [11:0] primitive_29_th_mem_V_read;
input  [11:0] primitive_30_th_mem_V_read;
input  [11:0] primitive_31_th_mem_V_read;
input  [11:0] primitive_32_th_mem_V_read;
input  [11:0] primitive_33_th_mem_V_read;
input  [11:0] primitive_34_th_mem_V_read;
input  [11:0] primitive_35_th_mem_V_read;
input  [11:0] primitive_36_th_mem_V_read;
input  [11:0] primitive_37_th_mem_V_read;
input  [11:0] primitive_38_th_mem_V_read;
input  [11:0] primitive_39_th_mem_V_read;
input  [11:0] primitive_40_th_mem_V_read;
input  [11:0] primitive_41_th_mem_V_read;
input  [11:0] primitive_42_th_mem_V_read;
input  [11:0] primitive_43_th_mem_V_read;
input  [11:0] primitive_44_th_mem_V_read;
input  [11:0] primitive_45_th_mem_V_read;
input  [11:0] primitive_46_th_mem_V_read;
input  [11:0] primitive_47_th_mem_V_read;
input  [11:0] primitive_48_th_mem_V_read;
input  [11:0] primitive_49_th_mem_V_read;
input  [11:0] primitive_50_th_mem_V_read;
input  [11:0] primitive_51_th_mem_V_read;
input  [11:0] primitive_52_th_mem_V_read;
input  [11:0] primitive_53_th_mem_V_read;
input  [11:0] primitive_54_th_mem_V_read;
input  [11:0] primitive_55_th_mem_V_read;
input  [11:0] primitive_56_th_mem_V_read;
input  [11:0] primitive_57_th_mem_V_read;
input  [11:0] primitive_58_th_mem_V_read;
input  [11:0] primitive_59_th_mem_V_read;
input  [11:0] primitive_60_th_mem_V_read;
input  [11:0] primitive_61_th_mem_V_read;
input  [11:0] primitive_62_th_mem_V_read;
input  [11:0] primitive_63_th_mem_V_read;
input  [11:0] primitive_64_th_mem_V_read;
input  [11:0] primitive_65_th_mem_V_read;
input  [11:0] primitive_66_th_mem_V_read;
input  [11:0] primitive_67_th_mem_V_read;
input  [11:0] primitive_68_th_mem_V_read;
input  [11:0] primitive_69_th_mem_V_read;
input  [11:0] primitive_70_th_mem_V_read;
input  [11:0] primitive_71_th_mem_V_read;
input  [11:0] primitive_72_th_mem_V_read;
input  [11:0] primitive_73_th_mem_V_read;
input  [11:0] primitive_74_th_mem_V_read;
input  [11:0] primitive_75_th_mem_V_read;
input  [11:0] primitive_76_th_mem_V_read;
input  [11:0] primitive_77_th_mem_V_read;
input  [11:0] primitive_78_th_mem_V_read;
input  [11:0] primitive_79_th_mem_V_read;
input  [11:0] primitive_80_th_mem_V_read;
input  [11:0] primitive_81_th_mem_V_read;
input  [11:0] primitive_82_th_mem_V_read;
input  [11:0] primitive_83_th_mem_V_read;
input  [11:0] primitive_84_th_mem_V_read;
input  [11:0] primitive_85_th_mem_V_read;
input  [11:0] primitive_86_th_mem_V_read;
input  [11:0] primitive_87_th_mem_V_read;
input  [11:0] primitive_88_th_mem_V_read;
input  [11:0] primitive_89_th_mem_V_read;
input  [11:0] primitive_90_th_mem_V_read;
input  [11:0] primitive_91_th_mem_V_read;
input  [11:0] primitive_92_th_mem_V_read;
input  [11:0] primitive_93_th_mem_V_read;
input  [11:0] primitive_94_th_mem_V_read;
input  [11:0] primitive_95_th_mem_V_read;
input  [11:0] primitive_96_th_mem_V_read;
input  [11:0] primitive_97_th_mem_V_read;
input  [11:0] primitive_98_th_mem_V_read;
input  [11:0] primitive_99_th_mem_V_read;
input  [11:0] primitive_100_th_mem_V_read;
input  [11:0] primitive_101_th_mem_V_read;
input  [11:0] primitive_102_th_mem_V_read;
input  [11:0] primitive_103_th_mem_V_read;
input  [11:0] primitive_104_th_mem_V_read;
input  [11:0] primitive_105_th_mem_V_read;
input  [11:0] primitive_106_th_mem_V_read;
input  [11:0] primitive_107_th_mem_V_read;
input  [11:0] primitive_108_th_mem_V_read;
input  [11:0] primitive_109_th_mem_V_read;
input  [11:0] primitive_110_th_mem_V_read;
input  [11:0] primitive_111_th_mem_V_read;
input  [11:0] primitive_112_th_mem_V_read;
input  [11:0] primitive_113_th_mem_V_read;
input  [11:0] primitive_114_th_mem_V_read;
input  [11:0] primitive_115_th_mem_V_read;
input  [11:0] primitive_116_th_mem_V_read;
input  [11:0] primitive_117_th_mem_V_read;
input  [11:0] primitive_118_th_mem_V_read;
input  [11:0] primitive_119_th_mem_V_read;
input  [11:0] primitive_120_th_mem_V_read;
input  [11:0] primitive_121_th_mem_V_read;
input  [11:0] primitive_122_th_mem_V_read;
input  [11:0] primitive_123_th_mem_V_read;
input  [11:0] primitive_124_th_mem_V_read;
input  [11:0] primitive_125_th_mem_V_read;
input  [11:0] primitive_126_th_mem_V_read;
input  [11:0] primitive_127_th_mem_V_read;
input  [3:0] quality_0_V_read;
input  [3:0] quality_1_V_read;
input  [6:0] wiregroup_0_V_read;
input  [6:0] wiregroup_1_V_read;
input  [7:0] hstrip_0_V_read;
input  [7:0] hstrip_1_V_read;
input  [3:0] clctpat_0_V_read;
input  [3:0] clctpat_1_V_read;
input  [0:0] station_V;
input  [3:0] cscid_V;
input  [0:0] endcap_V;
input  [0:0] lat_test_V;
output  [2:0] ap_return_0;
output  [43:0] ap_return_1;
output  [11:0] ap_return_2;
output  [11:0] ap_return_3;
output  [3:0] ap_return_4;
output  [3:0] ap_return_5;

wire   [0:0] tmp_66tmp_fu_1250_p2;
wire   [0:0] tmp_64_fu_1244_p2;
wire   [0:0] sel_tmp49_fu_1312_p2;
wire   [0:0] sel_tmp47_fu_1306_p2;
wire   [0:0] sel_tmp45_fu_1300_p2;
wire   [0:0] sel_tmp43_fu_1294_p2;
wire   [0:0] sel_tmp41_fu_1288_p2;
wire   [0:0] sel_tmp39_fu_1282_p2;
wire   [0:0] sel_tmp37_fu_1276_p2;
wire   [0:0] sel_tmp35_fu_1270_p2;
wire   [0:0] or_cond_fu_1318_p2;
wire   [0:0] or_cond14_fu_1324_p2;
wire   [0:0] or_cond15_fu_1330_p2;
wire   [0:0] newSel_fu_1336_p2;
wire   [0:0] newSel22_fu_1348_p2;
wire   [0:0] or_cond16_fu_1342_p2;
wire   [1:0] newSel139_cast_fu_1354_p1;
wire   [0:0] sel_tmp58_fu_1366_p2;
wire   [0:0] not_sel_tmp_fu_1372_p2;
wire   [0:0] sel_tmp60_fu_1378_p2;
wire   [0:0] sel_tmp62_fu_1384_p2;
wire   [0:0] not_sel_tmp4_fu_1390_p2;
wire   [0:0] sel_tmp64_fu_1396_p2;
wire   [1:0] newSel23_fu_1358_p3;
wire   [11:0] p_Result_s_fu_1408_p4;
wire   [11:0] tmp_s_fu_1418_p1;
wire   [0:0] p_s_fu_1402_p2;
wire   [11:0] tmp_199_fu_1422_p2;
wire   [11:0] tmp_200_fu_1428_p2;
wire   [0:0] tmp_630_not_fu_1454_p2;
wire   [0:0] lat_test_V_not_fu_1448_p2;
wire   [0:0] brmerge_fu_1460_p2;
wire   [0:0] tmp_630_not_not_fu_1474_p2;
wire   [0:0] not_brmerge_fu_1480_p2;
wire   [11:0] sel_tmp71_fu_1434_p3;
wire   [21:0] mt_fu_2691_p2;
wire   [21:0] tmp_33_fu_1502_p3;
wire   [21:0] r_V_6_fu_1510_p3;
wire   [11:0] ph_tmp_V_fu_1517_p4;
wire   [6:0] p_Result_146_fu_1533_p4;
wire   [7:0] lhs_V_3_cast_cast_fu_1262_p3;
wire   [7:0] rhs_V_cast_fu_1543_p1;
wire   [7:0] r_V_7_fu_1547_p2;
wire   [6:0] p_Result_147_fu_1553_p4;
wire   [8:0] rhs_V_3_cast_fu_1567_p1;
wire  signed [8:0] lhs_V_cast_fu_1563_p1;
wire   [7:0] rhs_V_4_cast_fu_1583_p1;
wire   [7:0] r_V_9_fu_1587_p2;
wire   [0:0] ph_reverse_V_fu_1256_p2;
wire   [11:0] tmp_202_fu_1527_p2;
wire   [11:0] tmp_203_fu_1577_p2;
wire   [8:0] r_V_8_fu_1571_p2;
wire   [8:0] i_assign_1_cast_fu_1593_p1;
wire   [8:0] tmp_fu_1605_p3;
wire  signed [31:0] tmp_cast_fu_1613_p1;
wire   [11:0] tmp_131_fu_1627_p130;
wire   [6:0] tmp_530_fu_1889_p1;
wire   [6:0] tmp_531_fu_1893_p1;
wire   [6:0] tmp_204_fu_1897_p2;
wire   [0:0] tmp_205_fu_1903_p2;
wire   [2:0] p_Val2_5_fu_1909_p3;
wire   [0:0] tmp_201_fu_1442_p2;
wire   [11:0] p_2_fu_1466_p3;
wire   [11:0] fph_V_load_s_fu_1597_p3;
wire   [0:0] tmp_206_fu_1917_p2;
wire   [0:0] sel_tmp86_fu_1949_p2;
wire   [0:0] sel_tmp87_fu_1955_p2;
reg   [2:0] tmp_532_fu_1923_p4;
wire   [2:0] p_3_cast_fu_1486_p1;
wire   [2:0] sel_tmp88_fu_1961_p3;
wire   [43:0] p_4_cast_cast_fu_1490_p3;
reg   [43:0] tmp_529_fu_1617_p4;
wire   [0:0] sel_tmp108_fu_2027_p2;
wire   [0:0] sel_tmp106_fu_2021_p2;
wire   [0:0] sel_tmp104_fu_2015_p2;
wire   [0:0] sel_tmp102_fu_2009_p2;
wire   [0:0] sel_tmp100_fu_2003_p2;
wire   [0:0] sel_tmp98_fu_1997_p2;
wire   [0:0] sel_tmp96_fu_1991_p2;
wire   [0:0] sel_tmp94_fu_1985_p2;
wire   [0:0] or_cond17_fu_2033_p2;
wire   [0:0] or_cond18_fu_2039_p2;
wire   [0:0] or_cond19_fu_2045_p2;
wire   [0:0] newSel24_fu_2051_p2;
wire   [0:0] newSel25_fu_2063_p2;
wire   [0:0] or_cond20_fu_2057_p2;
wire   [1:0] newSel153_cast_fu_2069_p1;
wire   [0:0] sel_tmp117_fu_2081_p2;
wire   [0:0] not_sel_tmp5_fu_2087_p2;
wire   [0:0] sel_tmp119_fu_2093_p2;
wire   [0:0] sel_tmp121_fu_2099_p2;
wire   [0:0] not_sel_tmp6_fu_2105_p2;
wire   [0:0] sel_tmp123_fu_2111_p2;
wire   [1:0] newSel26_fu_2073_p3;
wire   [11:0] p_Result_739_1_fu_2123_p4;
wire   [11:0] tmp_638_1_fu_2133_p1;
wire   [0:0] p_18_1_fu_2117_p2;
wire   [11:0] tmp_639_1_fu_2137_p2;
wire   [11:0] tmp_641_1_fu_2143_p2;
wire   [11:0] sel_tmp130_fu_2149_p3;
wire   [21:0] mt3_fu_2684_p2;
wire   [21:0] tmp_34_fu_2167_p3;
wire   [21:0] r_V_140_1_fu_2175_p3;
wire   [11:0] ph_tmp_V_1_fu_2182_p4;
wire   [6:0] p_Result_744_1_fu_2198_p4;
wire   [7:0] rhs_V_162_1_cast_fu_2208_p1;
wire   [7:0] r_V_136_1_fu_2212_p2;
wire  signed [8:0] lhs_V_69_1_cast_fu_2218_p1;
wire   [7:0] r_V_138_1_fu_2234_p2;
wire   [11:0] tmp_649_1_fu_2192_p2;
wire   [11:0] tmp_650_1_fu_2228_p2;
wire   [8:0] r_V_137_1_fu_2222_p2;
wire   [8:0] i_assign_1_1_cast_fu_2240_p1;
wire   [8:0] tmp_132_fu_2252_p3;
wire   [43:0] p_01142_3_fu_1977_p3;
wire  signed [31:0] tmp_132_cast_fu_2260_p1;
wire   [11:0] tmp_134_fu_2274_p130;
wire   [6:0] tmp_534_fu_2536_p1;
wire   [2:0] p_01130_5_fu_1969_p3;
wire   [6:0] tmp_653_1_fu_2540_p2;
reg   [2:0] tmp_535_fu_2546_p4;
wire   [0:0] tmp_656_1_fu_2556_p2;
reg   [2:0] tmp_536_fu_2562_p4;
wire   [2:0] p_Val2_248_1_fu_2572_p3;
wire   [0:0] tmp_646_1_fu_2157_p2;
wire   [11:0] fph_V_load_3_fu_2244_p3;
wire   [0:0] tmp_657_1_fu_2580_p2;
wire   [0:0] sel_tmp146_fu_2612_p2;
wire   [0:0] sel_tmp147_fu_2618_p2;
reg   [2:0] tmp_537_fu_2586_p4;
wire   [2:0] sel_tmp148_fu_2624_p3;
reg   [43:0] tmp_533_fu_2264_p4;
wire   [2:0] p_01130_5_1_fu_2632_p3;
wire   [43:0] p_01142_3_1_fu_2640_p3;
wire   [11:0] ph_0_V_write_assign_fu_1941_p3;
wire   [11:0] ph_1_V_write_assign_fu_2604_p3;
wire   [3:0] clctpat_r_0_V_write_assign_fu_1933_p3;
wire   [3:0] clctpat_r_1_V_write_assign_fu_2596_p3;
wire   [10:0] mt3_fu_2684_p0;
wire   [11:0] mt3_fu_2684_p1;
wire   [10:0] mt_fu_2691_p0;
wire   [11:0] mt_fu_2691_p1;
wire   [21:0] mt3_fu_2684_p10;
wire   [21:0] mt_fu_2691_p10;

sp_mux_128to1_sel7_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 12 ),
    .din4_WIDTH( 12 ),
    .din5_WIDTH( 12 ),
    .din6_WIDTH( 12 ),
    .din7_WIDTH( 12 ),
    .din8_WIDTH( 12 ),
    .din9_WIDTH( 12 ),
    .din10_WIDTH( 12 ),
    .din11_WIDTH( 12 ),
    .din12_WIDTH( 12 ),
    .din13_WIDTH( 12 ),
    .din14_WIDTH( 12 ),
    .din15_WIDTH( 12 ),
    .din16_WIDTH( 12 ),
    .din17_WIDTH( 12 ),
    .din18_WIDTH( 12 ),
    .din19_WIDTH( 12 ),
    .din20_WIDTH( 12 ),
    .din21_WIDTH( 12 ),
    .din22_WIDTH( 12 ),
    .din23_WIDTH( 12 ),
    .din24_WIDTH( 12 ),
    .din25_WIDTH( 12 ),
    .din26_WIDTH( 12 ),
    .din27_WIDTH( 12 ),
    .din28_WIDTH( 12 ),
    .din29_WIDTH( 12 ),
    .din30_WIDTH( 12 ),
    .din31_WIDTH( 12 ),
    .din32_WIDTH( 12 ),
    .din33_WIDTH( 12 ),
    .din34_WIDTH( 12 ),
    .din35_WIDTH( 12 ),
    .din36_WIDTH( 12 ),
    .din37_WIDTH( 12 ),
    .din38_WIDTH( 12 ),
    .din39_WIDTH( 12 ),
    .din40_WIDTH( 12 ),
    .din41_WIDTH( 12 ),
    .din42_WIDTH( 12 ),
    .din43_WIDTH( 12 ),
    .din44_WIDTH( 12 ),
    .din45_WIDTH( 12 ),
    .din46_WIDTH( 12 ),
    .din47_WIDTH( 12 ),
    .din48_WIDTH( 12 ),
    .din49_WIDTH( 12 ),
    .din50_WIDTH( 12 ),
    .din51_WIDTH( 12 ),
    .din52_WIDTH( 12 ),
    .din53_WIDTH( 12 ),
    .din54_WIDTH( 12 ),
    .din55_WIDTH( 12 ),
    .din56_WIDTH( 12 ),
    .din57_WIDTH( 12 ),
    .din58_WIDTH( 12 ),
    .din59_WIDTH( 12 ),
    .din60_WIDTH( 12 ),
    .din61_WIDTH( 12 ),
    .din62_WIDTH( 12 ),
    .din63_WIDTH( 12 ),
    .din64_WIDTH( 12 ),
    .din65_WIDTH( 12 ),
    .din66_WIDTH( 12 ),
    .din67_WIDTH( 12 ),
    .din68_WIDTH( 12 ),
    .din69_WIDTH( 12 ),
    .din70_WIDTH( 12 ),
    .din71_WIDTH( 12 ),
    .din72_WIDTH( 12 ),
    .din73_WIDTH( 12 ),
    .din74_WIDTH( 12 ),
    .din75_WIDTH( 12 ),
    .din76_WIDTH( 12 ),
    .din77_WIDTH( 12 ),
    .din78_WIDTH( 12 ),
    .din79_WIDTH( 12 ),
    .din80_WIDTH( 12 ),
    .din81_WIDTH( 12 ),
    .din82_WIDTH( 12 ),
    .din83_WIDTH( 12 ),
    .din84_WIDTH( 12 ),
    .din85_WIDTH( 12 ),
    .din86_WIDTH( 12 ),
    .din87_WIDTH( 12 ),
    .din88_WIDTH( 12 ),
    .din89_WIDTH( 12 ),
    .din90_WIDTH( 12 ),
    .din91_WIDTH( 12 ),
    .din92_WIDTH( 12 ),
    .din93_WIDTH( 12 ),
    .din94_WIDTH( 12 ),
    .din95_WIDTH( 12 ),
    .din96_WIDTH( 12 ),
    .din97_WIDTH( 12 ),
    .din98_WIDTH( 12 ),
    .din99_WIDTH( 12 ),
    .din100_WIDTH( 12 ),
    .din101_WIDTH( 12 ),
    .din102_WIDTH( 12 ),
    .din103_WIDTH( 12 ),
    .din104_WIDTH( 12 ),
    .din105_WIDTH( 12 ),
    .din106_WIDTH( 12 ),
    .din107_WIDTH( 12 ),
    .din108_WIDTH( 12 ),
    .din109_WIDTH( 12 ),
    .din110_WIDTH( 12 ),
    .din111_WIDTH( 12 ),
    .din112_WIDTH( 12 ),
    .din113_WIDTH( 12 ),
    .din114_WIDTH( 12 ),
    .din115_WIDTH( 12 ),
    .din116_WIDTH( 12 ),
    .din117_WIDTH( 12 ),
    .din118_WIDTH( 12 ),
    .din119_WIDTH( 12 ),
    .din120_WIDTH( 12 ),
    .din121_WIDTH( 12 ),
    .din122_WIDTH( 12 ),
    .din123_WIDTH( 12 ),
    .din124_WIDTH( 12 ),
    .din125_WIDTH( 12 ),
    .din126_WIDTH( 12 ),
    .din127_WIDTH( 12 ),
    .din128_WIDTH( 12 ),
    .din129_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
sp_mux_128to1_sel7_12_1_U819(
    .din1(primitive_0_th_mem_V_read),
    .din2(primitive_1_th_mem_V_read),
    .din3(primitive_2_th_mem_V_read),
    .din4(primitive_3_th_mem_V_read),
    .din5(primitive_4_th_mem_V_read),
    .din6(primitive_5_th_mem_V_read),
    .din7(primitive_6_th_mem_V_read),
    .din8(primitive_7_th_mem_V_read),
    .din9(primitive_8_th_mem_V_read),
    .din10(primitive_9_th_mem_V_read),
    .din11(primitive_10_th_mem_V_read),
    .din12(primitive_11_th_mem_V_read),
    .din13(primitive_12_th_mem_V_read),
    .din14(primitive_13_th_mem_V_read),
    .din15(primitive_14_th_mem_V_read),
    .din16(primitive_15_th_mem_V_read),
    .din17(primitive_16_th_mem_V_read),
    .din18(primitive_17_th_mem_V_read),
    .din19(primitive_18_th_mem_V_read),
    .din20(primitive_19_th_mem_V_read),
    .din21(primitive_20_th_mem_V_read),
    .din22(primitive_21_th_mem_V_read),
    .din23(primitive_22_th_mem_V_read),
    .din24(primitive_23_th_mem_V_read),
    .din25(primitive_24_th_mem_V_read),
    .din26(primitive_25_th_mem_V_read),
    .din27(primitive_26_th_mem_V_read),
    .din28(primitive_27_th_mem_V_read),
    .din29(primitive_28_th_mem_V_read),
    .din30(primitive_29_th_mem_V_read),
    .din31(primitive_30_th_mem_V_read),
    .din32(primitive_31_th_mem_V_read),
    .din33(primitive_32_th_mem_V_read),
    .din34(primitive_33_th_mem_V_read),
    .din35(primitive_34_th_mem_V_read),
    .din36(primitive_35_th_mem_V_read),
    .din37(primitive_36_th_mem_V_read),
    .din38(primitive_37_th_mem_V_read),
    .din39(primitive_38_th_mem_V_read),
    .din40(primitive_39_th_mem_V_read),
    .din41(primitive_40_th_mem_V_read),
    .din42(primitive_41_th_mem_V_read),
    .din43(primitive_42_th_mem_V_read),
    .din44(primitive_43_th_mem_V_read),
    .din45(primitive_44_th_mem_V_read),
    .din46(primitive_45_th_mem_V_read),
    .din47(primitive_46_th_mem_V_read),
    .din48(primitive_47_th_mem_V_read),
    .din49(primitive_48_th_mem_V_read),
    .din50(primitive_49_th_mem_V_read),
    .din51(primitive_50_th_mem_V_read),
    .din52(primitive_51_th_mem_V_read),
    .din53(primitive_52_th_mem_V_read),
    .din54(primitive_53_th_mem_V_read),
    .din55(primitive_54_th_mem_V_read),
    .din56(primitive_55_th_mem_V_read),
    .din57(primitive_56_th_mem_V_read),
    .din58(primitive_57_th_mem_V_read),
    .din59(primitive_58_th_mem_V_read),
    .din60(primitive_59_th_mem_V_read),
    .din61(primitive_60_th_mem_V_read),
    .din62(primitive_61_th_mem_V_read),
    .din63(primitive_62_th_mem_V_read),
    .din64(primitive_63_th_mem_V_read),
    .din65(primitive_64_th_mem_V_read),
    .din66(primitive_65_th_mem_V_read),
    .din67(primitive_66_th_mem_V_read),
    .din68(primitive_67_th_mem_V_read),
    .din69(primitive_68_th_mem_V_read),
    .din70(primitive_69_th_mem_V_read),
    .din71(primitive_70_th_mem_V_read),
    .din72(primitive_71_th_mem_V_read),
    .din73(primitive_72_th_mem_V_read),
    .din74(primitive_73_th_mem_V_read),
    .din75(primitive_74_th_mem_V_read),
    .din76(primitive_75_th_mem_V_read),
    .din77(primitive_76_th_mem_V_read),
    .din78(primitive_77_th_mem_V_read),
    .din79(primitive_78_th_mem_V_read),
    .din80(primitive_79_th_mem_V_read),
    .din81(primitive_80_th_mem_V_read),
    .din82(primitive_81_th_mem_V_read),
    .din83(primitive_82_th_mem_V_read),
    .din84(primitive_83_th_mem_V_read),
    .din85(primitive_84_th_mem_V_read),
    .din86(primitive_85_th_mem_V_read),
    .din87(primitive_86_th_mem_V_read),
    .din88(primitive_87_th_mem_V_read),
    .din89(primitive_88_th_mem_V_read),
    .din90(primitive_89_th_mem_V_read),
    .din91(primitive_90_th_mem_V_read),
    .din92(primitive_91_th_mem_V_read),
    .din93(primitive_92_th_mem_V_read),
    .din94(primitive_93_th_mem_V_read),
    .din95(primitive_94_th_mem_V_read),
    .din96(primitive_95_th_mem_V_read),
    .din97(primitive_96_th_mem_V_read),
    .din98(primitive_97_th_mem_V_read),
    .din99(primitive_98_th_mem_V_read),
    .din100(primitive_99_th_mem_V_read),
    .din101(primitive_100_th_mem_V_read),
    .din102(primitive_101_th_mem_V_read),
    .din103(primitive_102_th_mem_V_read),
    .din104(primitive_103_th_mem_V_read),
    .din105(primitive_104_th_mem_V_read),
    .din106(primitive_105_th_mem_V_read),
    .din107(primitive_106_th_mem_V_read),
    .din108(primitive_107_th_mem_V_read),
    .din109(primitive_108_th_mem_V_read),
    .din110(primitive_109_th_mem_V_read),
    .din111(primitive_110_th_mem_V_read),
    .din112(primitive_111_th_mem_V_read),
    .din113(primitive_112_th_mem_V_read),
    .din114(primitive_113_th_mem_V_read),
    .din115(primitive_114_th_mem_V_read),
    .din116(primitive_115_th_mem_V_read),
    .din117(primitive_116_th_mem_V_read),
    .din118(primitive_117_th_mem_V_read),
    .din119(primitive_118_th_mem_V_read),
    .din120(primitive_119_th_mem_V_read),
    .din121(primitive_120_th_mem_V_read),
    .din122(primitive_121_th_mem_V_read),
    .din123(primitive_122_th_mem_V_read),
    .din124(primitive_123_th_mem_V_read),
    .din125(primitive_124_th_mem_V_read),
    .din126(primitive_125_th_mem_V_read),
    .din127(primitive_126_th_mem_V_read),
    .din128(primitive_127_th_mem_V_read),
    .din129(wiregroup_0_V_read),
    .dout(tmp_131_fu_1627_p130)
);

sp_mux_128to1_sel7_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 12 ),
    .din4_WIDTH( 12 ),
    .din5_WIDTH( 12 ),
    .din6_WIDTH( 12 ),
    .din7_WIDTH( 12 ),
    .din8_WIDTH( 12 ),
    .din9_WIDTH( 12 ),
    .din10_WIDTH( 12 ),
    .din11_WIDTH( 12 ),
    .din12_WIDTH( 12 ),
    .din13_WIDTH( 12 ),
    .din14_WIDTH( 12 ),
    .din15_WIDTH( 12 ),
    .din16_WIDTH( 12 ),
    .din17_WIDTH( 12 ),
    .din18_WIDTH( 12 ),
    .din19_WIDTH( 12 ),
    .din20_WIDTH( 12 ),
    .din21_WIDTH( 12 ),
    .din22_WIDTH( 12 ),
    .din23_WIDTH( 12 ),
    .din24_WIDTH( 12 ),
    .din25_WIDTH( 12 ),
    .din26_WIDTH( 12 ),
    .din27_WIDTH( 12 ),
    .din28_WIDTH( 12 ),
    .din29_WIDTH( 12 ),
    .din30_WIDTH( 12 ),
    .din31_WIDTH( 12 ),
    .din32_WIDTH( 12 ),
    .din33_WIDTH( 12 ),
    .din34_WIDTH( 12 ),
    .din35_WIDTH( 12 ),
    .din36_WIDTH( 12 ),
    .din37_WIDTH( 12 ),
    .din38_WIDTH( 12 ),
    .din39_WIDTH( 12 ),
    .din40_WIDTH( 12 ),
    .din41_WIDTH( 12 ),
    .din42_WIDTH( 12 ),
    .din43_WIDTH( 12 ),
    .din44_WIDTH( 12 ),
    .din45_WIDTH( 12 ),
    .din46_WIDTH( 12 ),
    .din47_WIDTH( 12 ),
    .din48_WIDTH( 12 ),
    .din49_WIDTH( 12 ),
    .din50_WIDTH( 12 ),
    .din51_WIDTH( 12 ),
    .din52_WIDTH( 12 ),
    .din53_WIDTH( 12 ),
    .din54_WIDTH( 12 ),
    .din55_WIDTH( 12 ),
    .din56_WIDTH( 12 ),
    .din57_WIDTH( 12 ),
    .din58_WIDTH( 12 ),
    .din59_WIDTH( 12 ),
    .din60_WIDTH( 12 ),
    .din61_WIDTH( 12 ),
    .din62_WIDTH( 12 ),
    .din63_WIDTH( 12 ),
    .din64_WIDTH( 12 ),
    .din65_WIDTH( 12 ),
    .din66_WIDTH( 12 ),
    .din67_WIDTH( 12 ),
    .din68_WIDTH( 12 ),
    .din69_WIDTH( 12 ),
    .din70_WIDTH( 12 ),
    .din71_WIDTH( 12 ),
    .din72_WIDTH( 12 ),
    .din73_WIDTH( 12 ),
    .din74_WIDTH( 12 ),
    .din75_WIDTH( 12 ),
    .din76_WIDTH( 12 ),
    .din77_WIDTH( 12 ),
    .din78_WIDTH( 12 ),
    .din79_WIDTH( 12 ),
    .din80_WIDTH( 12 ),
    .din81_WIDTH( 12 ),
    .din82_WIDTH( 12 ),
    .din83_WIDTH( 12 ),
    .din84_WIDTH( 12 ),
    .din85_WIDTH( 12 ),
    .din86_WIDTH( 12 ),
    .din87_WIDTH( 12 ),
    .din88_WIDTH( 12 ),
    .din89_WIDTH( 12 ),
    .din90_WIDTH( 12 ),
    .din91_WIDTH( 12 ),
    .din92_WIDTH( 12 ),
    .din93_WIDTH( 12 ),
    .din94_WIDTH( 12 ),
    .din95_WIDTH( 12 ),
    .din96_WIDTH( 12 ),
    .din97_WIDTH( 12 ),
    .din98_WIDTH( 12 ),
    .din99_WIDTH( 12 ),
    .din100_WIDTH( 12 ),
    .din101_WIDTH( 12 ),
    .din102_WIDTH( 12 ),
    .din103_WIDTH( 12 ),
    .din104_WIDTH( 12 ),
    .din105_WIDTH( 12 ),
    .din106_WIDTH( 12 ),
    .din107_WIDTH( 12 ),
    .din108_WIDTH( 12 ),
    .din109_WIDTH( 12 ),
    .din110_WIDTH( 12 ),
    .din111_WIDTH( 12 ),
    .din112_WIDTH( 12 ),
    .din113_WIDTH( 12 ),
    .din114_WIDTH( 12 ),
    .din115_WIDTH( 12 ),
    .din116_WIDTH( 12 ),
    .din117_WIDTH( 12 ),
    .din118_WIDTH( 12 ),
    .din119_WIDTH( 12 ),
    .din120_WIDTH( 12 ),
    .din121_WIDTH( 12 ),
    .din122_WIDTH( 12 ),
    .din123_WIDTH( 12 ),
    .din124_WIDTH( 12 ),
    .din125_WIDTH( 12 ),
    .din126_WIDTH( 12 ),
    .din127_WIDTH( 12 ),
    .din128_WIDTH( 12 ),
    .din129_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
sp_mux_128to1_sel7_12_1_U820(
    .din1(primitive_0_th_mem_V_read),
    .din2(primitive_1_th_mem_V_read),
    .din3(primitive_2_th_mem_V_read),
    .din4(primitive_3_th_mem_V_read),
    .din5(primitive_4_th_mem_V_read),
    .din6(primitive_5_th_mem_V_read),
    .din7(primitive_6_th_mem_V_read),
    .din8(primitive_7_th_mem_V_read),
    .din9(primitive_8_th_mem_V_read),
    .din10(primitive_9_th_mem_V_read),
    .din11(primitive_10_th_mem_V_read),
    .din12(primitive_11_th_mem_V_read),
    .din13(primitive_12_th_mem_V_read),
    .din14(primitive_13_th_mem_V_read),
    .din15(primitive_14_th_mem_V_read),
    .din16(primitive_15_th_mem_V_read),
    .din17(primitive_16_th_mem_V_read),
    .din18(primitive_17_th_mem_V_read),
    .din19(primitive_18_th_mem_V_read),
    .din20(primitive_19_th_mem_V_read),
    .din21(primitive_20_th_mem_V_read),
    .din22(primitive_21_th_mem_V_read),
    .din23(primitive_22_th_mem_V_read),
    .din24(primitive_23_th_mem_V_read),
    .din25(primitive_24_th_mem_V_read),
    .din26(primitive_25_th_mem_V_read),
    .din27(primitive_26_th_mem_V_read),
    .din28(primitive_27_th_mem_V_read),
    .din29(primitive_28_th_mem_V_read),
    .din30(primitive_29_th_mem_V_read),
    .din31(primitive_30_th_mem_V_read),
    .din32(primitive_31_th_mem_V_read),
    .din33(primitive_32_th_mem_V_read),
    .din34(primitive_33_th_mem_V_read),
    .din35(primitive_34_th_mem_V_read),
    .din36(primitive_35_th_mem_V_read),
    .din37(primitive_36_th_mem_V_read),
    .din38(primitive_37_th_mem_V_read),
    .din39(primitive_38_th_mem_V_read),
    .din40(primitive_39_th_mem_V_read),
    .din41(primitive_40_th_mem_V_read),
    .din42(primitive_41_th_mem_V_read),
    .din43(primitive_42_th_mem_V_read),
    .din44(primitive_43_th_mem_V_read),
    .din45(primitive_44_th_mem_V_read),
    .din46(primitive_45_th_mem_V_read),
    .din47(primitive_46_th_mem_V_read),
    .din48(primitive_47_th_mem_V_read),
    .din49(primitive_48_th_mem_V_read),
    .din50(primitive_49_th_mem_V_read),
    .din51(primitive_50_th_mem_V_read),
    .din52(primitive_51_th_mem_V_read),
    .din53(primitive_52_th_mem_V_read),
    .din54(primitive_53_th_mem_V_read),
    .din55(primitive_54_th_mem_V_read),
    .din56(primitive_55_th_mem_V_read),
    .din57(primitive_56_th_mem_V_read),
    .din58(primitive_57_th_mem_V_read),
    .din59(primitive_58_th_mem_V_read),
    .din60(primitive_59_th_mem_V_read),
    .din61(primitive_60_th_mem_V_read),
    .din62(primitive_61_th_mem_V_read),
    .din63(primitive_62_th_mem_V_read),
    .din64(primitive_63_th_mem_V_read),
    .din65(primitive_64_th_mem_V_read),
    .din66(primitive_65_th_mem_V_read),
    .din67(primitive_66_th_mem_V_read),
    .din68(primitive_67_th_mem_V_read),
    .din69(primitive_68_th_mem_V_read),
    .din70(primitive_69_th_mem_V_read),
    .din71(primitive_70_th_mem_V_read),
    .din72(primitive_71_th_mem_V_read),
    .din73(primitive_72_th_mem_V_read),
    .din74(primitive_73_th_mem_V_read),
    .din75(primitive_74_th_mem_V_read),
    .din76(primitive_75_th_mem_V_read),
    .din77(primitive_76_th_mem_V_read),
    .din78(primitive_77_th_mem_V_read),
    .din79(primitive_78_th_mem_V_read),
    .din80(primitive_79_th_mem_V_read),
    .din81(primitive_80_th_mem_V_read),
    .din82(primitive_81_th_mem_V_read),
    .din83(primitive_82_th_mem_V_read),
    .din84(primitive_83_th_mem_V_read),
    .din85(primitive_84_th_mem_V_read),
    .din86(primitive_85_th_mem_V_read),
    .din87(primitive_86_th_mem_V_read),
    .din88(primitive_87_th_mem_V_read),
    .din89(primitive_88_th_mem_V_read),
    .din90(primitive_89_th_mem_V_read),
    .din91(primitive_90_th_mem_V_read),
    .din92(primitive_91_th_mem_V_read),
    .din93(primitive_92_th_mem_V_read),
    .din94(primitive_93_th_mem_V_read),
    .din95(primitive_94_th_mem_V_read),
    .din96(primitive_95_th_mem_V_read),
    .din97(primitive_96_th_mem_V_read),
    .din98(primitive_97_th_mem_V_read),
    .din99(primitive_98_th_mem_V_read),
    .din100(primitive_99_th_mem_V_read),
    .din101(primitive_100_th_mem_V_read),
    .din102(primitive_101_th_mem_V_read),
    .din103(primitive_102_th_mem_V_read),
    .din104(primitive_103_th_mem_V_read),
    .din105(primitive_104_th_mem_V_read),
    .din106(primitive_105_th_mem_V_read),
    .din107(primitive_106_th_mem_V_read),
    .din108(primitive_107_th_mem_V_read),
    .din109(primitive_108_th_mem_V_read),
    .din110(primitive_109_th_mem_V_read),
    .din111(primitive_110_th_mem_V_read),
    .din112(primitive_111_th_mem_V_read),
    .din113(primitive_112_th_mem_V_read),
    .din114(primitive_113_th_mem_V_read),
    .din115(primitive_114_th_mem_V_read),
    .din116(primitive_115_th_mem_V_read),
    .din117(primitive_116_th_mem_V_read),
    .din118(primitive_117_th_mem_V_read),
    .din119(primitive_118_th_mem_V_read),
    .din120(primitive_119_th_mem_V_read),
    .din121(primitive_120_th_mem_V_read),
    .din122(primitive_121_th_mem_V_read),
    .din123(primitive_122_th_mem_V_read),
    .din124(primitive_123_th_mem_V_read),
    .din125(primitive_124_th_mem_V_read),
    .din126(primitive_125_th_mem_V_read),
    .din127(primitive_126_th_mem_V_read),
    .din128(primitive_127_th_mem_V_read),
    .din129(wiregroup_1_V_read),
    .dout(tmp_134_fu_2274_p130)
);

sp_mul_mul_11ns_12ns_22_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
sp_mul_mul_11ns_12ns_22_1_U821(
    .din0(mt3_fu_2684_p0),
    .din1(mt3_fu_2684_p1),
    .dout(mt3_fu_2684_p2)
);

sp_mul_mul_11ns_12ns_22_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
sp_mul_mul_11ns_12ns_22_1_U822(
    .din0(mt_fu_2691_p0),
    .din1(mt_fu_2691_p1),
    .dout(mt_fu_2691_p2)
);

assign ap_return_0 = p_01130_5_1_fu_2632_p3;

assign ap_return_1 = p_01142_3_1_fu_2640_p3;

assign ap_return_2 = ph_0_V_write_assign_fu_1941_p3;

assign ap_return_3 = ph_1_V_write_assign_fu_2604_p3;

assign ap_return_4 = clctpat_r_0_V_write_assign_fu_1933_p3;

assign ap_return_5 = clctpat_r_1_V_write_assign_fu_2596_p3;

assign brmerge_fu_1460_p2 = (tmp_630_not_fu_1454_p2 | lat_test_V_not_fu_1448_p2);

assign clctpat_r_0_V_write_assign_fu_1933_p3 = ((tmp_201_fu_1442_p2[0:0] === 1'b1) ? ap_const_lv4_0 : clctpat_0_V_read);

assign clctpat_r_1_V_write_assign_fu_2596_p3 = ((tmp_646_1_fu_2157_p2[0:0] === 1'b1) ? ap_const_lv4_0 : clctpat_1_V_read);

assign fph_V_load_3_fu_2244_p3 = ((ph_reverse_V_fu_1256_p2[0:0] === 1'b1) ? tmp_649_1_fu_2192_p2 : tmp_650_1_fu_2228_p2);

assign fph_V_load_s_fu_1597_p3 = ((ph_reverse_V_fu_1256_p2[0:0] === 1'b1) ? tmp_202_fu_1527_p2 : tmp_203_fu_1577_p2);

assign i_assign_1_1_cast_fu_2240_p1 = r_V_138_1_fu_2234_p2;

assign i_assign_1_cast_fu_1593_p1 = r_V_9_fu_1587_p2;

assign lat_test_V_not_fu_1448_p2 = (lat_test_V ^ 1'b1);

assign lhs_V_3_cast_cast_fu_1262_p3 = ((tmp_64_fu_1244_p2[0:0] === 1'b1) ? ap_const_lv8_F : ap_const_lv8_14);

assign lhs_V_69_1_cast_fu_2218_p1 = $signed(r_V_136_1_fu_2212_p2);

assign lhs_V_cast_fu_1563_p1 = $signed(r_V_7_fu_1547_p2);

assign mt3_fu_2684_p0 = ap_const_lv22_3B3;

assign mt3_fu_2684_p1 = mt3_fu_2684_p10;

assign mt3_fu_2684_p10 = sel_tmp130_fu_2149_p3;

assign mt_fu_2691_p0 = ap_const_lv22_3B3;

assign mt_fu_2691_p1 = mt_fu_2691_p10;

assign mt_fu_2691_p10 = sel_tmp71_fu_1434_p3;

assign newSel139_cast_fu_1354_p1 = newSel22_fu_1348_p2;

assign newSel153_cast_fu_2069_p1 = newSel25_fu_2063_p2;

assign newSel22_fu_1348_p2 = (or_cond15_fu_1330_p2 | newSel_fu_1336_p2);

assign newSel23_fu_1358_p3 = ((or_cond16_fu_1342_p2[0:0] === 1'b1) ? ap_const_lv2_2 : newSel139_cast_fu_1354_p1);

assign newSel24_fu_2051_p2 = (sel_tmp96_fu_1991_p2 | sel_tmp94_fu_1985_p2);

assign newSel25_fu_2063_p2 = (or_cond19_fu_2045_p2 | newSel24_fu_2051_p2);

assign newSel26_fu_2073_p3 = ((or_cond20_fu_2057_p2[0:0] === 1'b1) ? ap_const_lv2_2 : newSel153_cast_fu_2069_p1);

assign newSel_fu_1336_p2 = (sel_tmp37_fu_1276_p2 | sel_tmp35_fu_1270_p2);

assign not_brmerge_fu_1480_p2 = (lat_test_V & tmp_630_not_not_fu_1474_p2);

assign not_sel_tmp4_fu_1390_p2 = ((clctpat_0_V_read != ap_const_lv4_3) ? 1'b1 : 1'b0);

assign not_sel_tmp5_fu_2087_p2 = ((clctpat_1_V_read != ap_const_lv4_5) ? 1'b1 : 1'b0);

assign not_sel_tmp6_fu_2105_p2 = ((clctpat_1_V_read != ap_const_lv4_3) ? 1'b1 : 1'b0);

assign not_sel_tmp_fu_1372_p2 = ((clctpat_0_V_read != ap_const_lv4_5) ? 1'b1 : 1'b0);

assign or_cond14_fu_1324_p2 = (sel_tmp45_fu_1300_p2 | sel_tmp43_fu_1294_p2);

assign or_cond15_fu_1330_p2 = (sel_tmp41_fu_1288_p2 | sel_tmp39_fu_1282_p2);

assign or_cond16_fu_1342_p2 = (or_cond_fu_1318_p2 | or_cond14_fu_1324_p2);

assign or_cond17_fu_2033_p2 = (sel_tmp108_fu_2027_p2 | sel_tmp106_fu_2021_p2);

assign or_cond18_fu_2039_p2 = (sel_tmp104_fu_2015_p2 | sel_tmp102_fu_2009_p2);

assign or_cond19_fu_2045_p2 = (sel_tmp100_fu_2003_p2 | sel_tmp98_fu_1997_p2);

assign or_cond20_fu_2057_p2 = (or_cond17_fu_2033_p2 | or_cond18_fu_2039_p2);

assign or_cond_fu_1318_p2 = (sel_tmp49_fu_1312_p2 | sel_tmp47_fu_1306_p2);

assign p_01130_5_1_fu_2632_p3 = ((tmp_646_1_fu_2157_p2[0:0] === 1'b1) ? p_01130_5_fu_1969_p3 : sel_tmp148_fu_2624_p3);

assign p_01130_5_fu_1969_p3 = ((tmp_201_fu_1442_p2[0:0] === 1'b1) ? p_3_cast_fu_1486_p1 : sel_tmp88_fu_1961_p3);

assign p_01142_3_1_fu_2640_p3 = ((tmp_646_1_fu_2157_p2[0:0] === 1'b1) ? p_01142_3_fu_1977_p3 : tmp_533_fu_2264_p4);

assign p_01142_3_fu_1977_p3 = ((tmp_201_fu_1442_p2[0:0] === 1'b1) ? p_4_cast_cast_fu_1490_p3 : tmp_529_fu_1617_p4);

assign p_18_1_fu_2117_p2 = (sel_tmp108_fu_2027_p2 | sel_tmp123_fu_2111_p2);

assign p_2_fu_1466_p3 = ((brmerge_fu_1460_p2[0:0] === 1'b1) ? ap_const_lv12_0 : ap_const_lv12_800);

assign p_3_cast_fu_1486_p1 = not_brmerge_fu_1480_p2;

assign p_4_cast_cast_fu_1490_p3 = ((brmerge_fu_1460_p2[0:0] === 1'b1) ? ap_const_lv44_0 : ap_const_lv44_400000);

assign p_Result_146_fu_1533_p4 = {{r_V_6_fu_1510_p3[ap_const_lv32_15 : ap_const_lv32_F]}};

assign p_Result_147_fu_1553_p4 = {{primitive_2_params_V_read[ap_const_lv32_7 : ap_const_lv32_1]}};

assign p_Result_739_1_fu_2123_p4 = {{{{ap_const_lv2_0}, {hstrip_1_V_read}}}, {ap_const_lv2_0}};

assign p_Result_744_1_fu_2198_p4 = {{r_V_140_1_fu_2175_p3[ap_const_lv32_15 : ap_const_lv32_F]}};

assign p_Result_s_fu_1408_p4 = {{{{ap_const_lv2_0}, {hstrip_0_V_read}}}, {ap_const_lv2_0}};

assign p_Val2_248_1_fu_2572_p3 = ((tmp_656_1_fu_2556_p2[0:0] === 1'b1) ? tmp_536_fu_2562_p4 : tmp_535_fu_2546_p4);

assign p_Val2_5_fu_1909_p3 = ((tmp_205_fu_1903_p2[0:0] === 1'b1) ? ap_const_lv3_5 : ap_const_lv3_1);

assign p_s_fu_1402_p2 = (sel_tmp49_fu_1312_p2 | sel_tmp64_fu_1396_p2);

assign ph_0_V_write_assign_fu_1941_p3 = ((tmp_201_fu_1442_p2[0:0] === 1'b1) ? p_2_fu_1466_p3 : fph_V_load_s_fu_1597_p3);

assign ph_1_V_write_assign_fu_2604_p3 = ((tmp_646_1_fu_2157_p2[0:0] === 1'b1) ? ap_const_lv12_0 : fph_V_load_3_fu_2244_p3);

assign ph_reverse_V_fu_1256_p2 = (endcap_V & tmp_66tmp_fu_1250_p2);

assign ph_tmp_V_1_fu_2182_p4 = {{r_V_140_1_fu_2175_p3[ap_const_lv32_15 : ap_const_lv32_A]}};

assign ph_tmp_V_fu_1517_p4 = {{r_V_6_fu_1510_p3[ap_const_lv32_15 : ap_const_lv32_A]}};

assign r_V_136_1_fu_2212_p2 = (lhs_V_3_cast_cast_fu_1262_p3 - rhs_V_162_1_cast_fu_2208_p1);

assign r_V_137_1_fu_2222_p2 = ($signed(rhs_V_3_cast_fu_1567_p1) + $signed(lhs_V_69_1_cast_fu_2218_p1));

assign r_V_138_1_fu_2234_p2 = (rhs_V_4_cast_fu_1583_p1 + rhs_V_162_1_cast_fu_2208_p1);

assign r_V_140_1_fu_2175_p3 = ((tmp_64_fu_1244_p2[0:0] === 1'b1) ? mt3_fu_2684_p2 : tmp_34_fu_2167_p3);

assign r_V_6_fu_1510_p3 = ((tmp_64_fu_1244_p2[0:0] === 1'b1) ? mt_fu_2691_p2 : tmp_33_fu_1502_p3);

assign r_V_7_fu_1547_p2 = (lhs_V_3_cast_cast_fu_1262_p3 - rhs_V_cast_fu_1543_p1);

assign r_V_8_fu_1571_p2 = ($signed(rhs_V_3_cast_fu_1567_p1) + $signed(lhs_V_cast_fu_1563_p1));

assign r_V_9_fu_1587_p2 = (rhs_V_4_cast_fu_1583_p1 + rhs_V_cast_fu_1543_p1);

assign rhs_V_162_1_cast_fu_2208_p1 = p_Result_744_1_fu_2198_p4;

assign rhs_V_3_cast_fu_1567_p1 = p_Result_147_fu_1553_p4;

assign rhs_V_4_cast_fu_1583_p1 = p_Result_147_fu_1553_p4;

assign rhs_V_cast_fu_1543_p1 = p_Result_146_fu_1533_p4;

assign sel_tmp100_fu_2003_p2 = ((clctpat_1_V_read == ap_const_lv4_6) ? 1'b1 : 1'b0);

assign sel_tmp102_fu_2009_p2 = ((clctpat_1_V_read == ap_const_lv4_5) ? 1'b1 : 1'b0);

assign sel_tmp104_fu_2015_p2 = ((clctpat_1_V_read == ap_const_lv4_4) ? 1'b1 : 1'b0);

assign sel_tmp106_fu_2021_p2 = ((clctpat_1_V_read == ap_const_lv4_3) ? 1'b1 : 1'b0);

assign sel_tmp108_fu_2027_p2 = ((clctpat_1_V_read == ap_const_lv4_2) ? 1'b1 : 1'b0);

assign sel_tmp117_fu_2081_p2 = (sel_tmp100_fu_2003_p2 | sel_tmp96_fu_1991_p2);

assign sel_tmp119_fu_2093_p2 = (sel_tmp117_fu_2081_p2 & not_sel_tmp5_fu_2087_p2);

assign sel_tmp121_fu_2099_p2 = (sel_tmp104_fu_2015_p2 | sel_tmp119_fu_2093_p2);

assign sel_tmp123_fu_2111_p2 = (sel_tmp121_fu_2099_p2 & not_sel_tmp6_fu_2105_p2);

assign sel_tmp130_fu_2149_p3 = ((p_18_1_fu_2117_p2[0:0] === 1'b1) ? tmp_639_1_fu_2137_p2 : tmp_641_1_fu_2143_p2);

assign sel_tmp146_fu_2612_p2 = (tmp_646_1_fu_2157_p2 ^ 1'b1);

assign sel_tmp147_fu_2618_p2 = (tmp_657_1_fu_2580_p2 & sel_tmp146_fu_2612_p2);

assign sel_tmp148_fu_2624_p3 = ((sel_tmp147_fu_2618_p2[0:0] === 1'b1) ? p_Val2_248_1_fu_2572_p3 : tmp_537_fu_2586_p4);

assign sel_tmp35_fu_1270_p2 = ((clctpat_0_V_read == ap_const_lv4_9) ? 1'b1 : 1'b0);

assign sel_tmp37_fu_1276_p2 = ((clctpat_0_V_read == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign sel_tmp39_fu_1282_p2 = ((clctpat_0_V_read == ap_const_lv4_7) ? 1'b1 : 1'b0);

assign sel_tmp41_fu_1288_p2 = ((clctpat_0_V_read == ap_const_lv4_6) ? 1'b1 : 1'b0);

assign sel_tmp43_fu_1294_p2 = ((clctpat_0_V_read == ap_const_lv4_5) ? 1'b1 : 1'b0);

assign sel_tmp45_fu_1300_p2 = ((clctpat_0_V_read == ap_const_lv4_4) ? 1'b1 : 1'b0);

assign sel_tmp47_fu_1306_p2 = ((clctpat_0_V_read == ap_const_lv4_3) ? 1'b1 : 1'b0);

assign sel_tmp49_fu_1312_p2 = ((clctpat_0_V_read == ap_const_lv4_2) ? 1'b1 : 1'b0);

assign sel_tmp58_fu_1366_p2 = (sel_tmp41_fu_1288_p2 | sel_tmp37_fu_1276_p2);

assign sel_tmp60_fu_1378_p2 = (sel_tmp58_fu_1366_p2 & not_sel_tmp_fu_1372_p2);

assign sel_tmp62_fu_1384_p2 = (sel_tmp45_fu_1300_p2 | sel_tmp60_fu_1378_p2);

assign sel_tmp64_fu_1396_p2 = (sel_tmp62_fu_1384_p2 & not_sel_tmp4_fu_1390_p2);

assign sel_tmp71_fu_1434_p3 = ((p_s_fu_1402_p2[0:0] === 1'b1) ? tmp_199_fu_1422_p2 : tmp_200_fu_1428_p2);

assign sel_tmp86_fu_1949_p2 = (tmp_201_fu_1442_p2 ^ 1'b1);

assign sel_tmp87_fu_1955_p2 = (tmp_206_fu_1917_p2 & sel_tmp86_fu_1949_p2);

assign sel_tmp88_fu_1961_p3 = ((sel_tmp87_fu_1955_p2[0:0] === 1'b1) ? p_Val2_5_fu_1909_p3 : tmp_532_fu_1923_p4);

assign sel_tmp94_fu_1985_p2 = ((clctpat_1_V_read == ap_const_lv4_9) ? 1'b1 : 1'b0);

assign sel_tmp96_fu_1991_p2 = ((clctpat_1_V_read == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign sel_tmp98_fu_1997_p2 = ((clctpat_1_V_read == ap_const_lv4_7) ? 1'b1 : 1'b0);

assign tmp_132_cast_fu_2260_p1 = $signed(tmp_132_fu_2252_p3);

assign tmp_132_fu_2252_p3 = ((ph_reverse_V_fu_1256_p2[0:0] === 1'b1) ? r_V_137_1_fu_2222_p2 : i_assign_1_1_cast_fu_2240_p1);

assign tmp_199_fu_1422_p2 = (p_Result_s_fu_1408_p4 - tmp_s_fu_1418_p1);

assign tmp_200_fu_1428_p2 = (tmp_s_fu_1418_p1 + p_Result_s_fu_1408_p4);

assign tmp_201_fu_1442_p2 = ((quality_0_V_read == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_202_fu_1527_p2 = (primitive_0_params_V_read - ph_tmp_V_fu_1517_p4);

assign tmp_203_fu_1577_p2 = (ph_tmp_V_fu_1517_p4 + primitive_0_params_V_read);

assign tmp_204_fu_1897_p2 = (tmp_530_fu_1889_p1 + tmp_531_fu_1893_p1);

assign tmp_205_fu_1903_p2 = ((tmp_204_fu_1897_p2 > ap_const_lv7_7D) ? 1'b1 : 1'b0);

assign tmp_206_fu_1917_p2 = ((tmp_204_fu_1897_p2 < ap_const_lv7_7E) ? 1'b1 : 1'b0);

assign tmp_33_fu_1502_p3 = {{sel_tmp71_fu_1434_p3}, {ap_const_lv10_0}};

assign tmp_34_fu_2167_p3 = {{sel_tmp130_fu_2149_p3}, {ap_const_lv10_0}};

always @ (*) begin
    tmp_529_fu_1617_p4 = ap_const_lv44_0;
    tmp_529_fu_1617_p4[tmp_cast_fu_1613_p1] = |(1'b1);
end

assign tmp_530_fu_1889_p1 = tmp_131_fu_1627_p130[6:0];

assign tmp_531_fu_1893_p1 = primitive_1_params_V_read[6:0];

always @ (*) begin
    tmp_532_fu_1923_p4 = p_Val2_5_fu_1909_p3;
    tmp_532_fu_1923_p4[ap_const_lv32_1] = |(1'b1);
end

always @ (*) begin
    tmp_533_fu_2264_p4 = p_01142_3_fu_1977_p3;
    tmp_533_fu_2264_p4[tmp_132_cast_fu_2260_p1] = |(1'b1);
end

assign tmp_534_fu_2536_p1 = tmp_134_fu_2274_p130[6:0];

always @ (*) begin
    tmp_535_fu_2546_p4 = p_01130_5_fu_1969_p3;
    tmp_535_fu_2546_p4[ap_const_lv32_0] = |(1'b1);
end

always @ (*) begin
    tmp_536_fu_2562_p4 = tmp_535_fu_2546_p4;
    tmp_536_fu_2562_p4[ap_const_lv32_2] = |(1'b1);
end

always @ (*) begin
    tmp_537_fu_2586_p4 = p_Val2_248_1_fu_2572_p3;
    tmp_537_fu_2586_p4[ap_const_lv32_1] = |(1'b1);
end

assign tmp_630_not_fu_1454_p2 = ((cscid_V != ap_const_lv4_1) ? 1'b1 : 1'b0);

assign tmp_630_not_not_fu_1474_p2 = (tmp_630_not_fu_1454_p2 ^ 1'b1);

assign tmp_638_1_fu_2133_p1 = newSel26_fu_2073_p3;

assign tmp_639_1_fu_2137_p2 = (p_Result_739_1_fu_2123_p4 - tmp_638_1_fu_2133_p1);

assign tmp_641_1_fu_2143_p2 = (tmp_638_1_fu_2133_p1 + p_Result_739_1_fu_2123_p4);

assign tmp_646_1_fu_2157_p2 = ((quality_1_V_read == ap_const_lv4_0) ? 1'b1 : 1'b0);

assign tmp_649_1_fu_2192_p2 = (primitive_0_params_V_read - ph_tmp_V_1_fu_2182_p4);

assign tmp_64_fu_1244_p2 = ((cscid_V > ap_const_lv4_5) ? 1'b1 : 1'b0);

assign tmp_650_1_fu_2228_p2 = (ph_tmp_V_1_fu_2182_p4 + primitive_0_params_V_read);

assign tmp_653_1_fu_2540_p2 = (tmp_534_fu_2536_p1 + tmp_531_fu_1893_p1);

assign tmp_656_1_fu_2556_p2 = ((tmp_653_1_fu_2540_p2 > ap_const_lv7_7D) ? 1'b1 : 1'b0);

assign tmp_657_1_fu_2580_p2 = ((tmp_653_1_fu_2540_p2 < ap_const_lv7_7E) ? 1'b1 : 1'b0);

assign tmp_66tmp_fu_1250_p2 = (station_V ^ 1'b1);

assign tmp_cast_fu_1613_p1 = $signed(tmp_fu_1605_p3);

assign tmp_fu_1605_p3 = ((ph_reverse_V_fu_1256_p2[0:0] === 1'b1) ? r_V_8_fu_1571_p2 : i_assign_1_cast_fu_1593_p1);

assign tmp_s_fu_1418_p1 = newSel23_fu_1358_p3;

endmodule //sp_prim_conv1
