// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sp_sort_sector (
        ap_clk,
        ap_rst,
        ph_rank_0_0_V_read,
        ph_rank_0_1_V_read,
        ph_rank_0_2_V_read,
        ph_rank_0_3_V_read,
        ph_rank_0_4_V_read,
        ph_rank_0_5_V_read,
        ph_rank_0_6_V_read,
        ph_rank_0_7_V_read,
        ph_rank_0_8_V_read,
        ph_rank_0_9_V_read,
        ph_rank_0_10_V_read,
        ph_rank_0_11_V_read,
        ph_rank_0_12_V_read,
        ph_rank_0_13_V_read,
        ph_rank_0_14_V_read,
        ph_rank_0_15_V_read,
        ph_rank_0_16_V_read,
        ph_rank_0_17_V_read,
        ph_rank_0_18_V_read,
        ph_rank_0_19_V_read,
        ph_rank_0_20_V_read,
        ph_rank_0_21_V_read,
        ph_rank_0_22_V_read,
        ph_rank_0_23_V_read,
        ph_rank_0_24_V_read,
        ph_rank_0_25_V_read,
        ph_rank_0_26_V_read,
        ph_rank_0_27_V_read,
        ph_rank_0_28_V_read,
        ph_rank_0_29_V_read,
        ph_rank_0_30_V_read,
        ph_rank_0_31_V_read,
        ph_rank_0_32_V_read,
        ph_rank_0_33_V_read,
        ph_rank_0_34_V_read,
        ph_rank_0_35_V_read,
        ph_rank_0_36_V_read,
        ph_rank_0_37_V_read,
        ph_rank_0_38_V_read,
        ph_rank_0_39_V_read,
        ph_rank_0_40_V_read,
        ph_rank_0_41_V_read,
        ph_rank_0_42_V_read,
        ph_rank_0_43_V_read,
        ph_rank_0_44_V_read,
        ph_rank_0_45_V_read,
        ph_rank_0_46_V_read,
        ph_rank_0_47_V_read,
        ph_rank_0_48_V_read,
        ph_rank_0_49_V_read,
        ph_rank_0_50_V_read,
        ph_rank_0_51_V_read,
        ph_rank_0_52_V_read,
        ph_rank_0_53_V_read,
        ph_rank_0_54_V_read,
        ph_rank_0_55_V_read,
        ph_rank_0_56_V_read,
        ph_rank_0_57_V_read,
        ph_rank_0_58_V_read,
        ph_rank_0_59_V_read,
        ph_rank_0_60_V_read,
        ph_rank_0_61_V_read,
        ph_rank_0_62_V_read,
        ph_rank_0_63_V_read,
        ph_rank_0_64_V_read,
        ph_rank_0_65_V_read,
        ph_rank_0_66_V_read,
        ph_rank_0_67_V_read,
        ph_rank_0_68_V_read,
        ph_rank_0_69_V_read,
        ph_rank_0_70_V_read,
        ph_rank_0_71_V_read,
        ph_rank_0_72_V_read,
        ph_rank_0_73_V_read,
        ph_rank_0_74_V_read,
        ph_rank_0_75_V_read,
        ph_rank_0_76_V_read,
        ph_rank_0_77_V_read,
        ph_rank_0_78_V_read,
        ph_rank_0_79_V_read,
        ph_rank_0_80_V_read,
        ph_rank_0_81_V_read,
        ph_rank_0_82_V_read,
        ph_rank_0_83_V_read,
        ph_rank_0_84_V_read,
        ph_rank_0_85_V_read,
        ph_rank_0_86_V_read,
        ph_rank_0_87_V_read,
        ph_rank_0_88_V_read,
        ph_rank_0_89_V_read,
        ph_rank_0_90_V_read,
        ph_rank_0_91_V_read,
        ph_rank_0_92_V_read,
        ph_rank_0_93_V_read,
        ph_rank_0_94_V_read,
        ph_rank_0_95_V_read,
        ph_rank_0_96_V_read,
        ph_rank_0_97_V_read,
        ph_rank_0_98_V_read,
        ph_rank_0_99_V_read,
        ph_rank_0_100_V_read,
        ph_rank_0_101_V_read,
        ph_rank_0_102_V_read,
        ph_rank_0_103_V_read,
        ph_rank_0_104_V_read,
        ph_rank_0_105_V_read,
        ph_rank_0_106_V_read,
        ph_rank_0_107_V_read,
        ph_rank_0_108_V_read,
        ph_rank_0_109_V_read,
        ph_rank_0_110_V_read,
        ph_rank_0_111_V_read,
        ph_rank_0_112_V_read,
        ph_rank_0_113_V_read,
        ph_rank_0_114_V_read,
        ph_rank_0_115_V_read,
        ph_rank_0_116_V_read,
        ph_rank_0_117_V_read,
        ph_rank_0_118_V_read,
        ph_rank_0_119_V_read,
        ph_rank_0_120_V_read,
        ph_rank_0_121_V_read,
        ph_rank_1_0_V_read,
        ph_rank_1_1_V_read,
        ph_rank_1_2_V_read,
        ph_rank_1_3_V_read,
        ph_rank_1_4_V_read,
        ph_rank_1_5_V_read,
        ph_rank_1_6_V_read,
        ph_rank_1_7_V_read,
        ph_rank_1_8_V_read,
        ph_rank_1_9_V_read,
        ph_rank_1_10_V_read,
        ph_rank_1_11_V_read,
        ph_rank_1_12_V_read,
        ph_rank_1_13_V_read,
        ph_rank_1_14_V_read,
        ph_rank_1_15_V_read,
        ph_rank_1_16_V_read,
        ph_rank_1_17_V_read,
        ph_rank_1_18_V_read,
        ph_rank_1_19_V_read,
        ph_rank_1_20_V_read,
        ph_rank_1_21_V_read,
        ph_rank_1_22_V_read,
        ph_rank_1_23_V_read,
        ph_rank_1_24_V_read,
        ph_rank_1_25_V_read,
        ph_rank_1_26_V_read,
        ph_rank_1_27_V_read,
        ph_rank_1_28_V_read,
        ph_rank_1_29_V_read,
        ph_rank_1_30_V_read,
        ph_rank_1_31_V_read,
        ph_rank_1_32_V_read,
        ph_rank_1_33_V_read,
        ph_rank_1_34_V_read,
        ph_rank_1_35_V_read,
        ph_rank_1_36_V_read,
        ph_rank_1_37_V_read,
        ph_rank_1_38_V_read,
        ph_rank_1_39_V_read,
        ph_rank_1_40_V_read,
        ph_rank_1_41_V_read,
        ph_rank_1_42_V_read,
        ph_rank_1_43_V_read,
        ph_rank_1_44_V_read,
        ph_rank_1_45_V_read,
        ph_rank_1_46_V_read,
        ph_rank_1_47_V_read,
        ph_rank_1_48_V_read,
        ph_rank_1_49_V_read,
        ph_rank_1_50_V_read,
        ph_rank_1_51_V_read,
        ph_rank_1_52_V_read,
        ph_rank_1_53_V_read,
        ph_rank_1_54_V_read,
        ph_rank_1_55_V_read,
        ph_rank_1_56_V_read,
        ph_rank_1_57_V_read,
        ph_rank_1_58_V_read,
        ph_rank_1_59_V_read,
        ph_rank_1_60_V_read,
        ph_rank_1_61_V_read,
        ph_rank_1_62_V_read,
        ph_rank_1_63_V_read,
        ph_rank_1_64_V_read,
        ph_rank_1_65_V_read,
        ph_rank_1_66_V_read,
        ph_rank_1_67_V_read,
        ph_rank_1_68_V_read,
        ph_rank_1_69_V_read,
        ph_rank_1_70_V_read,
        ph_rank_1_71_V_read,
        ph_rank_1_72_V_read,
        ph_rank_1_73_V_read,
        ph_rank_1_74_V_read,
        ph_rank_1_75_V_read,
        ph_rank_1_76_V_read,
        ph_rank_1_77_V_read,
        ph_rank_1_78_V_read,
        ph_rank_1_79_V_read,
        ph_rank_1_80_V_read,
        ph_rank_1_81_V_read,
        ph_rank_1_82_V_read,
        ph_rank_1_83_V_read,
        ph_rank_1_84_V_read,
        ph_rank_1_85_V_read,
        ph_rank_1_86_V_read,
        ph_rank_1_87_V_read,
        ph_rank_1_88_V_read,
        ph_rank_1_89_V_read,
        ph_rank_1_90_V_read,
        ph_rank_1_91_V_read,
        ph_rank_1_92_V_read,
        ph_rank_1_93_V_read,
        ph_rank_1_94_V_read,
        ph_rank_1_95_V_read,
        ph_rank_1_96_V_read,
        ph_rank_1_97_V_read,
        ph_rank_1_98_V_read,
        ph_rank_1_99_V_read,
        ph_rank_1_100_V_read,
        ph_rank_1_101_V_read,
        ph_rank_1_102_V_read,
        ph_rank_1_103_V_read,
        ph_rank_1_104_V_read,
        ph_rank_1_105_V_read,
        ph_rank_1_106_V_read,
        ph_rank_1_107_V_read,
        ph_rank_1_108_V_read,
        ph_rank_1_109_V_read,
        ph_rank_1_110_V_read,
        ph_rank_1_111_V_read,
        ph_rank_1_112_V_read,
        ph_rank_1_113_V_read,
        ph_rank_1_114_V_read,
        ph_rank_1_115_V_read,
        ph_rank_1_116_V_read,
        ph_rank_1_117_V_read,
        ph_rank_1_118_V_read,
        ph_rank_1_119_V_read,
        ph_rank_1_120_V_read,
        ph_rank_1_121_V_read,
        ph_rank_2_0_V_read,
        ph_rank_2_1_V_read,
        ph_rank_2_2_V_read,
        ph_rank_2_3_V_read,
        ph_rank_2_4_V_read,
        ph_rank_2_5_V_read,
        ph_rank_2_6_V_read,
        ph_rank_2_7_V_read,
        ph_rank_2_8_V_read,
        ph_rank_2_9_V_read,
        ph_rank_2_10_V_read,
        ph_rank_2_11_V_read,
        ph_rank_2_12_V_read,
        ph_rank_2_13_V_read,
        ph_rank_2_14_V_read,
        ph_rank_2_15_V_read,
        ph_rank_2_16_V_read,
        ph_rank_2_17_V_read,
        ph_rank_2_18_V_read,
        ph_rank_2_19_V_read,
        ph_rank_2_20_V_read,
        ph_rank_2_21_V_read,
        ph_rank_2_22_V_read,
        ph_rank_2_23_V_read,
        ph_rank_2_24_V_read,
        ph_rank_2_25_V_read,
        ph_rank_2_26_V_read,
        ph_rank_2_27_V_read,
        ph_rank_2_28_V_read,
        ph_rank_2_29_V_read,
        ph_rank_2_30_V_read,
        ph_rank_2_31_V_read,
        ph_rank_2_32_V_read,
        ph_rank_2_33_V_read,
        ph_rank_2_34_V_read,
        ph_rank_2_35_V_read,
        ph_rank_2_36_V_read,
        ph_rank_2_37_V_read,
        ph_rank_2_38_V_read,
        ph_rank_2_39_V_read,
        ph_rank_2_40_V_read,
        ph_rank_2_41_V_read,
        ph_rank_2_42_V_read,
        ph_rank_2_43_V_read,
        ph_rank_2_44_V_read,
        ph_rank_2_45_V_read,
        ph_rank_2_46_V_read,
        ph_rank_2_47_V_read,
        ph_rank_2_48_V_read,
        ph_rank_2_49_V_read,
        ph_rank_2_50_V_read,
        ph_rank_2_51_V_read,
        ph_rank_2_52_V_read,
        ph_rank_2_53_V_read,
        ph_rank_2_54_V_read,
        ph_rank_2_55_V_read,
        ph_rank_2_56_V_read,
        ph_rank_2_57_V_read,
        ph_rank_2_58_V_read,
        ph_rank_2_59_V_read,
        ph_rank_2_60_V_read,
        ph_rank_2_61_V_read,
        ph_rank_2_62_V_read,
        ph_rank_2_63_V_read,
        ph_rank_2_64_V_read,
        ph_rank_2_65_V_read,
        ph_rank_2_66_V_read,
        ph_rank_2_67_V_read,
        ph_rank_2_68_V_read,
        ph_rank_2_69_V_read,
        ph_rank_2_70_V_read,
        ph_rank_2_71_V_read,
        ph_rank_2_72_V_read,
        ph_rank_2_73_V_read,
        ph_rank_2_74_V_read,
        ph_rank_2_75_V_read,
        ph_rank_2_76_V_read,
        ph_rank_2_77_V_read,
        ph_rank_2_78_V_read,
        ph_rank_2_79_V_read,
        ph_rank_2_80_V_read,
        ph_rank_2_81_V_read,
        ph_rank_2_82_V_read,
        ph_rank_2_83_V_read,
        ph_rank_2_84_V_read,
        ph_rank_2_85_V_read,
        ph_rank_2_86_V_read,
        ph_rank_2_87_V_read,
        ph_rank_2_88_V_read,
        ph_rank_2_89_V_read,
        ph_rank_2_90_V_read,
        ph_rank_2_91_V_read,
        ph_rank_2_92_V_read,
        ph_rank_2_93_V_read,
        ph_rank_2_94_V_read,
        ph_rank_2_95_V_read,
        ph_rank_2_96_V_read,
        ph_rank_2_97_V_read,
        ph_rank_2_98_V_read,
        ph_rank_2_99_V_read,
        ph_rank_2_100_V_read,
        ph_rank_2_101_V_read,
        ph_rank_2_102_V_read,
        ph_rank_2_103_V_read,
        ph_rank_2_104_V_read,
        ph_rank_2_105_V_read,
        ph_rank_2_106_V_read,
        ph_rank_2_107_V_read,
        ph_rank_2_108_V_read,
        ph_rank_2_109_V_read,
        ph_rank_2_110_V_read,
        ph_rank_2_111_V_read,
        ph_rank_2_112_V_read,
        ph_rank_2_113_V_read,
        ph_rank_2_114_V_read,
        ph_rank_2_115_V_read,
        ph_rank_2_116_V_read,
        ph_rank_2_117_V_read,
        ph_rank_2_118_V_read,
        ph_rank_2_119_V_read,
        ph_rank_2_120_V_read,
        ph_rank_2_121_V_read,
        ph_rank_3_0_V_read,
        ph_rank_3_1_V_read,
        ph_rank_3_2_V_read,
        ph_rank_3_3_V_read,
        ph_rank_3_4_V_read,
        ph_rank_3_5_V_read,
        ph_rank_3_6_V_read,
        ph_rank_3_7_V_read,
        ph_rank_3_8_V_read,
        ph_rank_3_9_V_read,
        ph_rank_3_10_V_read,
        ph_rank_3_11_V_read,
        ph_rank_3_12_V_read,
        ph_rank_3_13_V_read,
        ph_rank_3_14_V_read,
        ph_rank_3_15_V_read,
        ph_rank_3_16_V_read,
        ph_rank_3_17_V_read,
        ph_rank_3_18_V_read,
        ph_rank_3_19_V_read,
        ph_rank_3_20_V_read,
        ph_rank_3_21_V_read,
        ph_rank_3_22_V_read,
        ph_rank_3_23_V_read,
        ph_rank_3_24_V_read,
        ph_rank_3_25_V_read,
        ph_rank_3_26_V_read,
        ph_rank_3_27_V_read,
        ph_rank_3_28_V_read,
        ph_rank_3_29_V_read,
        ph_rank_3_30_V_read,
        ph_rank_3_31_V_read,
        ph_rank_3_32_V_read,
        ph_rank_3_33_V_read,
        ph_rank_3_34_V_read,
        ph_rank_3_35_V_read,
        ph_rank_3_36_V_read,
        ph_rank_3_37_V_read,
        ph_rank_3_38_V_read,
        ph_rank_3_39_V_read,
        ph_rank_3_40_V_read,
        ph_rank_3_41_V_read,
        ph_rank_3_42_V_read,
        ph_rank_3_43_V_read,
        ph_rank_3_44_V_read,
        ph_rank_3_45_V_read,
        ph_rank_3_46_V_read,
        ph_rank_3_47_V_read,
        ph_rank_3_48_V_read,
        ph_rank_3_49_V_read,
        ph_rank_3_50_V_read,
        ph_rank_3_51_V_read,
        ph_rank_3_52_V_read,
        ph_rank_3_53_V_read,
        ph_rank_3_54_V_read,
        ph_rank_3_55_V_read,
        ph_rank_3_56_V_read,
        ph_rank_3_57_V_read,
        ph_rank_3_58_V_read,
        ph_rank_3_59_V_read,
        ph_rank_3_60_V_read,
        ph_rank_3_61_V_read,
        ph_rank_3_62_V_read,
        ph_rank_3_63_V_read,
        ph_rank_3_64_V_read,
        ph_rank_3_65_V_read,
        ph_rank_3_66_V_read,
        ph_rank_3_67_V_read,
        ph_rank_3_68_V_read,
        ph_rank_3_69_V_read,
        ph_rank_3_70_V_read,
        ph_rank_3_71_V_read,
        ph_rank_3_72_V_read,
        ph_rank_3_73_V_read,
        ph_rank_3_74_V_read,
        ph_rank_3_75_V_read,
        ph_rank_3_76_V_read,
        ph_rank_3_77_V_read,
        ph_rank_3_78_V_read,
        ph_rank_3_79_V_read,
        ph_rank_3_80_V_read,
        ph_rank_3_81_V_read,
        ph_rank_3_82_V_read,
        ph_rank_3_83_V_read,
        ph_rank_3_84_V_read,
        ph_rank_3_85_V_read,
        ph_rank_3_86_V_read,
        ph_rank_3_87_V_read,
        ph_rank_3_88_V_read,
        ph_rank_3_89_V_read,
        ph_rank_3_90_V_read,
        ph_rank_3_91_V_read,
        ph_rank_3_92_V_read,
        ph_rank_3_93_V_read,
        ph_rank_3_94_V_read,
        ph_rank_3_95_V_read,
        ph_rank_3_96_V_read,
        ph_rank_3_97_V_read,
        ph_rank_3_98_V_read,
        ph_rank_3_99_V_read,
        ph_rank_3_100_V_read,
        ph_rank_3_101_V_read,
        ph_rank_3_102_V_read,
        ph_rank_3_103_V_read,
        ph_rank_3_104_V_read,
        ph_rank_3_105_V_read,
        ph_rank_3_106_V_read,
        ph_rank_3_107_V_read,
        ph_rank_3_108_V_read,
        ph_rank_3_109_V_read,
        ph_rank_3_110_V_read,
        ph_rank_3_111_V_read,
        ph_rank_3_112_V_read,
        ph_rank_3_113_V_read,
        ph_rank_3_114_V_read,
        ph_rank_3_115_V_read,
        ph_rank_3_116_V_read,
        ph_rank_3_117_V_read,
        ph_rank_3_118_V_read,
        ph_rank_3_119_V_read,
        ph_rank_3_120_V_read,
        ph_rank_3_121_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23
);


input   ap_clk;
input   ap_rst;
input  [5:0] ph_rank_0_0_V_read;
input  [5:0] ph_rank_0_1_V_read;
input  [5:0] ph_rank_0_2_V_read;
input  [5:0] ph_rank_0_3_V_read;
input  [5:0] ph_rank_0_4_V_read;
input  [5:0] ph_rank_0_5_V_read;
input  [5:0] ph_rank_0_6_V_read;
input  [5:0] ph_rank_0_7_V_read;
input  [5:0] ph_rank_0_8_V_read;
input  [5:0] ph_rank_0_9_V_read;
input  [5:0] ph_rank_0_10_V_read;
input  [5:0] ph_rank_0_11_V_read;
input  [5:0] ph_rank_0_12_V_read;
input  [5:0] ph_rank_0_13_V_read;
input  [5:0] ph_rank_0_14_V_read;
input  [5:0] ph_rank_0_15_V_read;
input  [5:0] ph_rank_0_16_V_read;
input  [5:0] ph_rank_0_17_V_read;
input  [5:0] ph_rank_0_18_V_read;
input  [5:0] ph_rank_0_19_V_read;
input  [5:0] ph_rank_0_20_V_read;
input  [5:0] ph_rank_0_21_V_read;
input  [5:0] ph_rank_0_22_V_read;
input  [5:0] ph_rank_0_23_V_read;
input  [5:0] ph_rank_0_24_V_read;
input  [5:0] ph_rank_0_25_V_read;
input  [5:0] ph_rank_0_26_V_read;
input  [5:0] ph_rank_0_27_V_read;
input  [5:0] ph_rank_0_28_V_read;
input  [5:0] ph_rank_0_29_V_read;
input  [5:0] ph_rank_0_30_V_read;
input  [5:0] ph_rank_0_31_V_read;
input  [5:0] ph_rank_0_32_V_read;
input  [5:0] ph_rank_0_33_V_read;
input  [5:0] ph_rank_0_34_V_read;
input  [5:0] ph_rank_0_35_V_read;
input  [5:0] ph_rank_0_36_V_read;
input  [5:0] ph_rank_0_37_V_read;
input  [5:0] ph_rank_0_38_V_read;
input  [5:0] ph_rank_0_39_V_read;
input  [5:0] ph_rank_0_40_V_read;
input  [5:0] ph_rank_0_41_V_read;
input  [5:0] ph_rank_0_42_V_read;
input  [5:0] ph_rank_0_43_V_read;
input  [5:0] ph_rank_0_44_V_read;
input  [5:0] ph_rank_0_45_V_read;
input  [5:0] ph_rank_0_46_V_read;
input  [5:0] ph_rank_0_47_V_read;
input  [5:0] ph_rank_0_48_V_read;
input  [5:0] ph_rank_0_49_V_read;
input  [5:0] ph_rank_0_50_V_read;
input  [5:0] ph_rank_0_51_V_read;
input  [5:0] ph_rank_0_52_V_read;
input  [5:0] ph_rank_0_53_V_read;
input  [5:0] ph_rank_0_54_V_read;
input  [5:0] ph_rank_0_55_V_read;
input  [5:0] ph_rank_0_56_V_read;
input  [5:0] ph_rank_0_57_V_read;
input  [5:0] ph_rank_0_58_V_read;
input  [5:0] ph_rank_0_59_V_read;
input  [5:0] ph_rank_0_60_V_read;
input  [5:0] ph_rank_0_61_V_read;
input  [5:0] ph_rank_0_62_V_read;
input  [5:0] ph_rank_0_63_V_read;
input  [5:0] ph_rank_0_64_V_read;
input  [5:0] ph_rank_0_65_V_read;
input  [5:0] ph_rank_0_66_V_read;
input  [5:0] ph_rank_0_67_V_read;
input  [5:0] ph_rank_0_68_V_read;
input  [5:0] ph_rank_0_69_V_read;
input  [5:0] ph_rank_0_70_V_read;
input  [5:0] ph_rank_0_71_V_read;
input  [5:0] ph_rank_0_72_V_read;
input  [5:0] ph_rank_0_73_V_read;
input  [5:0] ph_rank_0_74_V_read;
input  [5:0] ph_rank_0_75_V_read;
input  [5:0] ph_rank_0_76_V_read;
input  [5:0] ph_rank_0_77_V_read;
input  [5:0] ph_rank_0_78_V_read;
input  [5:0] ph_rank_0_79_V_read;
input  [5:0] ph_rank_0_80_V_read;
input  [5:0] ph_rank_0_81_V_read;
input  [5:0] ph_rank_0_82_V_read;
input  [5:0] ph_rank_0_83_V_read;
input  [5:0] ph_rank_0_84_V_read;
input  [5:0] ph_rank_0_85_V_read;
input  [5:0] ph_rank_0_86_V_read;
input  [5:0] ph_rank_0_87_V_read;
input  [5:0] ph_rank_0_88_V_read;
input  [5:0] ph_rank_0_89_V_read;
input  [5:0] ph_rank_0_90_V_read;
input  [5:0] ph_rank_0_91_V_read;
input  [5:0] ph_rank_0_92_V_read;
input  [5:0] ph_rank_0_93_V_read;
input  [5:0] ph_rank_0_94_V_read;
input  [5:0] ph_rank_0_95_V_read;
input  [5:0] ph_rank_0_96_V_read;
input  [5:0] ph_rank_0_97_V_read;
input  [5:0] ph_rank_0_98_V_read;
input  [5:0] ph_rank_0_99_V_read;
input  [5:0] ph_rank_0_100_V_read;
input  [5:0] ph_rank_0_101_V_read;
input  [5:0] ph_rank_0_102_V_read;
input  [5:0] ph_rank_0_103_V_read;
input  [5:0] ph_rank_0_104_V_read;
input  [5:0] ph_rank_0_105_V_read;
input  [5:0] ph_rank_0_106_V_read;
input  [5:0] ph_rank_0_107_V_read;
input  [5:0] ph_rank_0_108_V_read;
input  [5:0] ph_rank_0_109_V_read;
input  [5:0] ph_rank_0_110_V_read;
input  [5:0] ph_rank_0_111_V_read;
input  [5:0] ph_rank_0_112_V_read;
input  [5:0] ph_rank_0_113_V_read;
input  [5:0] ph_rank_0_114_V_read;
input  [5:0] ph_rank_0_115_V_read;
input  [5:0] ph_rank_0_116_V_read;
input  [5:0] ph_rank_0_117_V_read;
input  [5:0] ph_rank_0_118_V_read;
input  [5:0] ph_rank_0_119_V_read;
input  [5:0] ph_rank_0_120_V_read;
input  [5:0] ph_rank_0_121_V_read;
input  [5:0] ph_rank_1_0_V_read;
input  [5:0] ph_rank_1_1_V_read;
input  [5:0] ph_rank_1_2_V_read;
input  [5:0] ph_rank_1_3_V_read;
input  [5:0] ph_rank_1_4_V_read;
input  [5:0] ph_rank_1_5_V_read;
input  [5:0] ph_rank_1_6_V_read;
input  [5:0] ph_rank_1_7_V_read;
input  [5:0] ph_rank_1_8_V_read;
input  [5:0] ph_rank_1_9_V_read;
input  [5:0] ph_rank_1_10_V_read;
input  [5:0] ph_rank_1_11_V_read;
input  [5:0] ph_rank_1_12_V_read;
input  [5:0] ph_rank_1_13_V_read;
input  [5:0] ph_rank_1_14_V_read;
input  [5:0] ph_rank_1_15_V_read;
input  [5:0] ph_rank_1_16_V_read;
input  [5:0] ph_rank_1_17_V_read;
input  [5:0] ph_rank_1_18_V_read;
input  [5:0] ph_rank_1_19_V_read;
input  [5:0] ph_rank_1_20_V_read;
input  [5:0] ph_rank_1_21_V_read;
input  [5:0] ph_rank_1_22_V_read;
input  [5:0] ph_rank_1_23_V_read;
input  [5:0] ph_rank_1_24_V_read;
input  [5:0] ph_rank_1_25_V_read;
input  [5:0] ph_rank_1_26_V_read;
input  [5:0] ph_rank_1_27_V_read;
input  [5:0] ph_rank_1_28_V_read;
input  [5:0] ph_rank_1_29_V_read;
input  [5:0] ph_rank_1_30_V_read;
input  [5:0] ph_rank_1_31_V_read;
input  [5:0] ph_rank_1_32_V_read;
input  [5:0] ph_rank_1_33_V_read;
input  [5:0] ph_rank_1_34_V_read;
input  [5:0] ph_rank_1_35_V_read;
input  [5:0] ph_rank_1_36_V_read;
input  [5:0] ph_rank_1_37_V_read;
input  [5:0] ph_rank_1_38_V_read;
input  [5:0] ph_rank_1_39_V_read;
input  [5:0] ph_rank_1_40_V_read;
input  [5:0] ph_rank_1_41_V_read;
input  [5:0] ph_rank_1_42_V_read;
input  [5:0] ph_rank_1_43_V_read;
input  [5:0] ph_rank_1_44_V_read;
input  [5:0] ph_rank_1_45_V_read;
input  [5:0] ph_rank_1_46_V_read;
input  [5:0] ph_rank_1_47_V_read;
input  [5:0] ph_rank_1_48_V_read;
input  [5:0] ph_rank_1_49_V_read;
input  [5:0] ph_rank_1_50_V_read;
input  [5:0] ph_rank_1_51_V_read;
input  [5:0] ph_rank_1_52_V_read;
input  [5:0] ph_rank_1_53_V_read;
input  [5:0] ph_rank_1_54_V_read;
input  [5:0] ph_rank_1_55_V_read;
input  [5:0] ph_rank_1_56_V_read;
input  [5:0] ph_rank_1_57_V_read;
input  [5:0] ph_rank_1_58_V_read;
input  [5:0] ph_rank_1_59_V_read;
input  [5:0] ph_rank_1_60_V_read;
input  [5:0] ph_rank_1_61_V_read;
input  [5:0] ph_rank_1_62_V_read;
input  [5:0] ph_rank_1_63_V_read;
input  [5:0] ph_rank_1_64_V_read;
input  [5:0] ph_rank_1_65_V_read;
input  [5:0] ph_rank_1_66_V_read;
input  [5:0] ph_rank_1_67_V_read;
input  [5:0] ph_rank_1_68_V_read;
input  [5:0] ph_rank_1_69_V_read;
input  [5:0] ph_rank_1_70_V_read;
input  [5:0] ph_rank_1_71_V_read;
input  [5:0] ph_rank_1_72_V_read;
input  [5:0] ph_rank_1_73_V_read;
input  [5:0] ph_rank_1_74_V_read;
input  [5:0] ph_rank_1_75_V_read;
input  [5:0] ph_rank_1_76_V_read;
input  [5:0] ph_rank_1_77_V_read;
input  [5:0] ph_rank_1_78_V_read;
input  [5:0] ph_rank_1_79_V_read;
input  [5:0] ph_rank_1_80_V_read;
input  [5:0] ph_rank_1_81_V_read;
input  [5:0] ph_rank_1_82_V_read;
input  [5:0] ph_rank_1_83_V_read;
input  [5:0] ph_rank_1_84_V_read;
input  [5:0] ph_rank_1_85_V_read;
input  [5:0] ph_rank_1_86_V_read;
input  [5:0] ph_rank_1_87_V_read;
input  [5:0] ph_rank_1_88_V_read;
input  [5:0] ph_rank_1_89_V_read;
input  [5:0] ph_rank_1_90_V_read;
input  [5:0] ph_rank_1_91_V_read;
input  [5:0] ph_rank_1_92_V_read;
input  [5:0] ph_rank_1_93_V_read;
input  [5:0] ph_rank_1_94_V_read;
input  [5:0] ph_rank_1_95_V_read;
input  [5:0] ph_rank_1_96_V_read;
input  [5:0] ph_rank_1_97_V_read;
input  [5:0] ph_rank_1_98_V_read;
input  [5:0] ph_rank_1_99_V_read;
input  [5:0] ph_rank_1_100_V_read;
input  [5:0] ph_rank_1_101_V_read;
input  [5:0] ph_rank_1_102_V_read;
input  [5:0] ph_rank_1_103_V_read;
input  [5:0] ph_rank_1_104_V_read;
input  [5:0] ph_rank_1_105_V_read;
input  [5:0] ph_rank_1_106_V_read;
input  [5:0] ph_rank_1_107_V_read;
input  [5:0] ph_rank_1_108_V_read;
input  [5:0] ph_rank_1_109_V_read;
input  [5:0] ph_rank_1_110_V_read;
input  [5:0] ph_rank_1_111_V_read;
input  [5:0] ph_rank_1_112_V_read;
input  [5:0] ph_rank_1_113_V_read;
input  [5:0] ph_rank_1_114_V_read;
input  [5:0] ph_rank_1_115_V_read;
input  [5:0] ph_rank_1_116_V_read;
input  [5:0] ph_rank_1_117_V_read;
input  [5:0] ph_rank_1_118_V_read;
input  [5:0] ph_rank_1_119_V_read;
input  [5:0] ph_rank_1_120_V_read;
input  [5:0] ph_rank_1_121_V_read;
input  [5:0] ph_rank_2_0_V_read;
input  [5:0] ph_rank_2_1_V_read;
input  [5:0] ph_rank_2_2_V_read;
input  [5:0] ph_rank_2_3_V_read;
input  [5:0] ph_rank_2_4_V_read;
input  [5:0] ph_rank_2_5_V_read;
input  [5:0] ph_rank_2_6_V_read;
input  [5:0] ph_rank_2_7_V_read;
input  [5:0] ph_rank_2_8_V_read;
input  [5:0] ph_rank_2_9_V_read;
input  [5:0] ph_rank_2_10_V_read;
input  [5:0] ph_rank_2_11_V_read;
input  [5:0] ph_rank_2_12_V_read;
input  [5:0] ph_rank_2_13_V_read;
input  [5:0] ph_rank_2_14_V_read;
input  [5:0] ph_rank_2_15_V_read;
input  [5:0] ph_rank_2_16_V_read;
input  [5:0] ph_rank_2_17_V_read;
input  [5:0] ph_rank_2_18_V_read;
input  [5:0] ph_rank_2_19_V_read;
input  [5:0] ph_rank_2_20_V_read;
input  [5:0] ph_rank_2_21_V_read;
input  [5:0] ph_rank_2_22_V_read;
input  [5:0] ph_rank_2_23_V_read;
input  [5:0] ph_rank_2_24_V_read;
input  [5:0] ph_rank_2_25_V_read;
input  [5:0] ph_rank_2_26_V_read;
input  [5:0] ph_rank_2_27_V_read;
input  [5:0] ph_rank_2_28_V_read;
input  [5:0] ph_rank_2_29_V_read;
input  [5:0] ph_rank_2_30_V_read;
input  [5:0] ph_rank_2_31_V_read;
input  [5:0] ph_rank_2_32_V_read;
input  [5:0] ph_rank_2_33_V_read;
input  [5:0] ph_rank_2_34_V_read;
input  [5:0] ph_rank_2_35_V_read;
input  [5:0] ph_rank_2_36_V_read;
input  [5:0] ph_rank_2_37_V_read;
input  [5:0] ph_rank_2_38_V_read;
input  [5:0] ph_rank_2_39_V_read;
input  [5:0] ph_rank_2_40_V_read;
input  [5:0] ph_rank_2_41_V_read;
input  [5:0] ph_rank_2_42_V_read;
input  [5:0] ph_rank_2_43_V_read;
input  [5:0] ph_rank_2_44_V_read;
input  [5:0] ph_rank_2_45_V_read;
input  [5:0] ph_rank_2_46_V_read;
input  [5:0] ph_rank_2_47_V_read;
input  [5:0] ph_rank_2_48_V_read;
input  [5:0] ph_rank_2_49_V_read;
input  [5:0] ph_rank_2_50_V_read;
input  [5:0] ph_rank_2_51_V_read;
input  [5:0] ph_rank_2_52_V_read;
input  [5:0] ph_rank_2_53_V_read;
input  [5:0] ph_rank_2_54_V_read;
input  [5:0] ph_rank_2_55_V_read;
input  [5:0] ph_rank_2_56_V_read;
input  [5:0] ph_rank_2_57_V_read;
input  [5:0] ph_rank_2_58_V_read;
input  [5:0] ph_rank_2_59_V_read;
input  [5:0] ph_rank_2_60_V_read;
input  [5:0] ph_rank_2_61_V_read;
input  [5:0] ph_rank_2_62_V_read;
input  [5:0] ph_rank_2_63_V_read;
input  [5:0] ph_rank_2_64_V_read;
input  [5:0] ph_rank_2_65_V_read;
input  [5:0] ph_rank_2_66_V_read;
input  [5:0] ph_rank_2_67_V_read;
input  [5:0] ph_rank_2_68_V_read;
input  [5:0] ph_rank_2_69_V_read;
input  [5:0] ph_rank_2_70_V_read;
input  [5:0] ph_rank_2_71_V_read;
input  [5:0] ph_rank_2_72_V_read;
input  [5:0] ph_rank_2_73_V_read;
input  [5:0] ph_rank_2_74_V_read;
input  [5:0] ph_rank_2_75_V_read;
input  [5:0] ph_rank_2_76_V_read;
input  [5:0] ph_rank_2_77_V_read;
input  [5:0] ph_rank_2_78_V_read;
input  [5:0] ph_rank_2_79_V_read;
input  [5:0] ph_rank_2_80_V_read;
input  [5:0] ph_rank_2_81_V_read;
input  [5:0] ph_rank_2_82_V_read;
input  [5:0] ph_rank_2_83_V_read;
input  [5:0] ph_rank_2_84_V_read;
input  [5:0] ph_rank_2_85_V_read;
input  [5:0] ph_rank_2_86_V_read;
input  [5:0] ph_rank_2_87_V_read;
input  [5:0] ph_rank_2_88_V_read;
input  [5:0] ph_rank_2_89_V_read;
input  [5:0] ph_rank_2_90_V_read;
input  [5:0] ph_rank_2_91_V_read;
input  [5:0] ph_rank_2_92_V_read;
input  [5:0] ph_rank_2_93_V_read;
input  [5:0] ph_rank_2_94_V_read;
input  [5:0] ph_rank_2_95_V_read;
input  [5:0] ph_rank_2_96_V_read;
input  [5:0] ph_rank_2_97_V_read;
input  [5:0] ph_rank_2_98_V_read;
input  [5:0] ph_rank_2_99_V_read;
input  [5:0] ph_rank_2_100_V_read;
input  [5:0] ph_rank_2_101_V_read;
input  [5:0] ph_rank_2_102_V_read;
input  [5:0] ph_rank_2_103_V_read;
input  [5:0] ph_rank_2_104_V_read;
input  [5:0] ph_rank_2_105_V_read;
input  [5:0] ph_rank_2_106_V_read;
input  [5:0] ph_rank_2_107_V_read;
input  [5:0] ph_rank_2_108_V_read;
input  [5:0] ph_rank_2_109_V_read;
input  [5:0] ph_rank_2_110_V_read;
input  [5:0] ph_rank_2_111_V_read;
input  [5:0] ph_rank_2_112_V_read;
input  [5:0] ph_rank_2_113_V_read;
input  [5:0] ph_rank_2_114_V_read;
input  [5:0] ph_rank_2_115_V_read;
input  [5:0] ph_rank_2_116_V_read;
input  [5:0] ph_rank_2_117_V_read;
input  [5:0] ph_rank_2_118_V_read;
input  [5:0] ph_rank_2_119_V_read;
input  [5:0] ph_rank_2_120_V_read;
input  [5:0] ph_rank_2_121_V_read;
input  [5:0] ph_rank_3_0_V_read;
input  [5:0] ph_rank_3_1_V_read;
input  [5:0] ph_rank_3_2_V_read;
input  [5:0] ph_rank_3_3_V_read;
input  [5:0] ph_rank_3_4_V_read;
input  [5:0] ph_rank_3_5_V_read;
input  [5:0] ph_rank_3_6_V_read;
input  [5:0] ph_rank_3_7_V_read;
input  [5:0] ph_rank_3_8_V_read;
input  [5:0] ph_rank_3_9_V_read;
input  [5:0] ph_rank_3_10_V_read;
input  [5:0] ph_rank_3_11_V_read;
input  [5:0] ph_rank_3_12_V_read;
input  [5:0] ph_rank_3_13_V_read;
input  [5:0] ph_rank_3_14_V_read;
input  [5:0] ph_rank_3_15_V_read;
input  [5:0] ph_rank_3_16_V_read;
input  [5:0] ph_rank_3_17_V_read;
input  [5:0] ph_rank_3_18_V_read;
input  [5:0] ph_rank_3_19_V_read;
input  [5:0] ph_rank_3_20_V_read;
input  [5:0] ph_rank_3_21_V_read;
input  [5:0] ph_rank_3_22_V_read;
input  [5:0] ph_rank_3_23_V_read;
input  [5:0] ph_rank_3_24_V_read;
input  [5:0] ph_rank_3_25_V_read;
input  [5:0] ph_rank_3_26_V_read;
input  [5:0] ph_rank_3_27_V_read;
input  [5:0] ph_rank_3_28_V_read;
input  [5:0] ph_rank_3_29_V_read;
input  [5:0] ph_rank_3_30_V_read;
input  [5:0] ph_rank_3_31_V_read;
input  [5:0] ph_rank_3_32_V_read;
input  [5:0] ph_rank_3_33_V_read;
input  [5:0] ph_rank_3_34_V_read;
input  [5:0] ph_rank_3_35_V_read;
input  [5:0] ph_rank_3_36_V_read;
input  [5:0] ph_rank_3_37_V_read;
input  [5:0] ph_rank_3_38_V_read;
input  [5:0] ph_rank_3_39_V_read;
input  [5:0] ph_rank_3_40_V_read;
input  [5:0] ph_rank_3_41_V_read;
input  [5:0] ph_rank_3_42_V_read;
input  [5:0] ph_rank_3_43_V_read;
input  [5:0] ph_rank_3_44_V_read;
input  [5:0] ph_rank_3_45_V_read;
input  [5:0] ph_rank_3_46_V_read;
input  [5:0] ph_rank_3_47_V_read;
input  [5:0] ph_rank_3_48_V_read;
input  [5:0] ph_rank_3_49_V_read;
input  [5:0] ph_rank_3_50_V_read;
input  [5:0] ph_rank_3_51_V_read;
input  [5:0] ph_rank_3_52_V_read;
input  [5:0] ph_rank_3_53_V_read;
input  [5:0] ph_rank_3_54_V_read;
input  [5:0] ph_rank_3_55_V_read;
input  [5:0] ph_rank_3_56_V_read;
input  [5:0] ph_rank_3_57_V_read;
input  [5:0] ph_rank_3_58_V_read;
input  [5:0] ph_rank_3_59_V_read;
input  [5:0] ph_rank_3_60_V_read;
input  [5:0] ph_rank_3_61_V_read;
input  [5:0] ph_rank_3_62_V_read;
input  [5:0] ph_rank_3_63_V_read;
input  [5:0] ph_rank_3_64_V_read;
input  [5:0] ph_rank_3_65_V_read;
input  [5:0] ph_rank_3_66_V_read;
input  [5:0] ph_rank_3_67_V_read;
input  [5:0] ph_rank_3_68_V_read;
input  [5:0] ph_rank_3_69_V_read;
input  [5:0] ph_rank_3_70_V_read;
input  [5:0] ph_rank_3_71_V_read;
input  [5:0] ph_rank_3_72_V_read;
input  [5:0] ph_rank_3_73_V_read;
input  [5:0] ph_rank_3_74_V_read;
input  [5:0] ph_rank_3_75_V_read;
input  [5:0] ph_rank_3_76_V_read;
input  [5:0] ph_rank_3_77_V_read;
input  [5:0] ph_rank_3_78_V_read;
input  [5:0] ph_rank_3_79_V_read;
input  [5:0] ph_rank_3_80_V_read;
input  [5:0] ph_rank_3_81_V_read;
input  [5:0] ph_rank_3_82_V_read;
input  [5:0] ph_rank_3_83_V_read;
input  [5:0] ph_rank_3_84_V_read;
input  [5:0] ph_rank_3_85_V_read;
input  [5:0] ph_rank_3_86_V_read;
input  [5:0] ph_rank_3_87_V_read;
input  [5:0] ph_rank_3_88_V_read;
input  [5:0] ph_rank_3_89_V_read;
input  [5:0] ph_rank_3_90_V_read;
input  [5:0] ph_rank_3_91_V_read;
input  [5:0] ph_rank_3_92_V_read;
input  [5:0] ph_rank_3_93_V_read;
input  [5:0] ph_rank_3_94_V_read;
input  [5:0] ph_rank_3_95_V_read;
input  [5:0] ph_rank_3_96_V_read;
input  [5:0] ph_rank_3_97_V_read;
input  [5:0] ph_rank_3_98_V_read;
input  [5:0] ph_rank_3_99_V_read;
input  [5:0] ph_rank_3_100_V_read;
input  [5:0] ph_rank_3_101_V_read;
input  [5:0] ph_rank_3_102_V_read;
input  [5:0] ph_rank_3_103_V_read;
input  [5:0] ph_rank_3_104_V_read;
input  [5:0] ph_rank_3_105_V_read;
input  [5:0] ph_rank_3_106_V_read;
input  [5:0] ph_rank_3_107_V_read;
input  [5:0] ph_rank_3_108_V_read;
input  [5:0] ph_rank_3_109_V_read;
input  [5:0] ph_rank_3_110_V_read;
input  [5:0] ph_rank_3_111_V_read;
input  [5:0] ph_rank_3_112_V_read;
input  [5:0] ph_rank_3_113_V_read;
input  [5:0] ph_rank_3_114_V_read;
input  [5:0] ph_rank_3_115_V_read;
input  [5:0] ph_rank_3_116_V_read;
input  [5:0] ph_rank_3_117_V_read;
input  [5:0] ph_rank_3_118_V_read;
input  [5:0] ph_rank_3_119_V_read;
input  [5:0] ph_rank_3_120_V_read;
input  [5:0] ph_rank_3_121_V_read;
output  [6:0] ap_return_0;
output  [6:0] ap_return_1;
output  [6:0] ap_return_2;
output  [6:0] ap_return_3;
output  [6:0] ap_return_4;
output  [6:0] ap_return_5;
output  [6:0] ap_return_6;
output  [6:0] ap_return_7;
output  [6:0] ap_return_8;
output  [6:0] ap_return_9;
output  [6:0] ap_return_10;
output  [6:0] ap_return_11;
output  [5:0] ap_return_12;
output  [5:0] ap_return_13;
output  [5:0] ap_return_14;
output  [5:0] ap_return_15;
output  [5:0] ap_return_16;
output  [5:0] ap_return_17;
output  [5:0] ap_return_18;
output  [5:0] ap_return_19;
output  [5:0] ap_return_20;
output  [5:0] ap_return_21;
output  [5:0] ap_return_22;
output  [5:0] ap_return_23;

wire   [5:0] grp_sp_best3_fu_3932_ap_return_0;
wire   [5:0] grp_sp_best3_fu_3932_ap_return_1;
wire   [5:0] grp_sp_best3_fu_3932_ap_return_2;
wire   [6:0] grp_sp_best3_fu_3932_ap_return_3;
wire   [6:0] grp_sp_best3_fu_3932_ap_return_4;
wire   [6:0] grp_sp_best3_fu_3932_ap_return_5;
wire   [5:0] grp_sp_best3_fu_4180_ap_return_0;
wire   [5:0] grp_sp_best3_fu_4180_ap_return_1;
wire   [5:0] grp_sp_best3_fu_4180_ap_return_2;
wire   [6:0] grp_sp_best3_fu_4180_ap_return_3;
wire   [6:0] grp_sp_best3_fu_4180_ap_return_4;
wire   [6:0] grp_sp_best3_fu_4180_ap_return_5;
wire   [5:0] grp_sp_best3_fu_4428_ap_return_0;
wire   [5:0] grp_sp_best3_fu_4428_ap_return_1;
wire   [5:0] grp_sp_best3_fu_4428_ap_return_2;
wire   [6:0] grp_sp_best3_fu_4428_ap_return_3;
wire   [6:0] grp_sp_best3_fu_4428_ap_return_4;
wire   [6:0] grp_sp_best3_fu_4428_ap_return_5;
wire   [5:0] grp_sp_best3_fu_4676_ap_return_0;
wire   [5:0] grp_sp_best3_fu_4676_ap_return_1;
wire   [5:0] grp_sp_best3_fu_4676_ap_return_2;
wire   [6:0] grp_sp_best3_fu_4676_ap_return_3;
wire   [6:0] grp_sp_best3_fu_4676_ap_return_4;
wire   [6:0] grp_sp_best3_fu_4676_ap_return_5;

sp_best3 grp_sp_best3_fu_3932(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .rank_ex_0_V_read(ph_rank_0_0_V_read),
    .rank_ex_1_V_read(ph_rank_0_1_V_read),
    .rank_ex_2_V_read(ph_rank_0_2_V_read),
    .rank_ex_3_V_read(ph_rank_0_3_V_read),
    .rank_ex_4_V_read(ph_rank_0_4_V_read),
    .rank_ex_5_V_read(ph_rank_0_5_V_read),
    .rank_ex_6_V_read(ph_rank_0_6_V_read),
    .rank_ex_7_V_read(ph_rank_0_7_V_read),
    .rank_ex_8_V_read(ph_rank_0_8_V_read),
    .rank_ex_9_V_read(ph_rank_0_9_V_read),
    .rank_ex_10_V_read(ph_rank_0_10_V_read),
    .rank_ex_11_V_read(ph_rank_0_11_V_read),
    .rank_ex_12_V_read(ph_rank_0_12_V_read),
    .rank_ex_13_V_read(ph_rank_0_13_V_read),
    .rank_ex_14_V_read(ph_rank_0_14_V_read),
    .rank_ex_15_V_read(ph_rank_0_15_V_read),
    .rank_ex_16_V_read(ph_rank_0_16_V_read),
    .rank_ex_17_V_read(ph_rank_0_17_V_read),
    .rank_ex_18_V_read(ph_rank_0_18_V_read),
    .rank_ex_19_V_read(ph_rank_0_19_V_read),
    .rank_ex_20_V_read(ph_rank_0_20_V_read),
    .rank_ex_21_V_read(ph_rank_0_21_V_read),
    .rank_ex_22_V_read(ph_rank_0_22_V_read),
    .rank_ex_23_V_read(ph_rank_0_23_V_read),
    .rank_ex_24_V_read(ph_rank_0_24_V_read),
    .rank_ex_25_V_read(ph_rank_0_25_V_read),
    .rank_ex_26_V_read(ph_rank_0_26_V_read),
    .rank_ex_27_V_read(ph_rank_0_27_V_read),
    .rank_ex_28_V_read(ph_rank_0_28_V_read),
    .rank_ex_29_V_read(ph_rank_0_29_V_read),
    .rank_ex_30_V_read(ph_rank_0_30_V_read),
    .rank_ex_31_V_read(ph_rank_0_31_V_read),
    .rank_ex_32_V_read(ph_rank_0_32_V_read),
    .rank_ex_33_V_read(ph_rank_0_33_V_read),
    .rank_ex_34_V_read(ph_rank_0_34_V_read),
    .rank_ex_35_V_read(ph_rank_0_35_V_read),
    .rank_ex_36_V_read(ph_rank_0_36_V_read),
    .rank_ex_37_V_read(ph_rank_0_37_V_read),
    .rank_ex_38_V_read(ph_rank_0_38_V_read),
    .rank_ex_39_V_read(ph_rank_0_39_V_read),
    .rank_ex_40_V_read(ph_rank_0_40_V_read),
    .rank_ex_41_V_read(ph_rank_0_41_V_read),
    .rank_ex_42_V_read(ph_rank_0_42_V_read),
    .rank_ex_43_V_read(ph_rank_0_43_V_read),
    .rank_ex_44_V_read(ph_rank_0_44_V_read),
    .rank_ex_45_V_read(ph_rank_0_45_V_read),
    .rank_ex_46_V_read(ph_rank_0_46_V_read),
    .rank_ex_47_V_read(ph_rank_0_47_V_read),
    .rank_ex_48_V_read(ph_rank_0_48_V_read),
    .rank_ex_49_V_read(ph_rank_0_49_V_read),
    .rank_ex_50_V_read(ph_rank_0_50_V_read),
    .rank_ex_51_V_read(ph_rank_0_51_V_read),
    .rank_ex_52_V_read(ph_rank_0_52_V_read),
    .rank_ex_53_V_read(ph_rank_0_53_V_read),
    .rank_ex_54_V_read(ph_rank_0_54_V_read),
    .rank_ex_55_V_read(ph_rank_0_55_V_read),
    .rank_ex_56_V_read(ph_rank_0_56_V_read),
    .rank_ex_57_V_read(ph_rank_0_57_V_read),
    .rank_ex_58_V_read(ph_rank_0_58_V_read),
    .rank_ex_59_V_read(ph_rank_0_59_V_read),
    .rank_ex_60_V_read(ph_rank_0_60_V_read),
    .rank_ex_61_V_read(ph_rank_0_61_V_read),
    .rank_ex_62_V_read(ph_rank_0_62_V_read),
    .rank_ex_63_V_read(ph_rank_0_63_V_read),
    .rank_ex_64_V_read(ph_rank_0_64_V_read),
    .rank_ex_65_V_read(ph_rank_0_65_V_read),
    .rank_ex_66_V_read(ph_rank_0_66_V_read),
    .rank_ex_67_V_read(ph_rank_0_67_V_read),
    .rank_ex_68_V_read(ph_rank_0_68_V_read),
    .rank_ex_69_V_read(ph_rank_0_69_V_read),
    .rank_ex_70_V_read(ph_rank_0_70_V_read),
    .rank_ex_71_V_read(ph_rank_0_71_V_read),
    .rank_ex_72_V_read(ph_rank_0_72_V_read),
    .rank_ex_73_V_read(ph_rank_0_73_V_read),
    .rank_ex_74_V_read(ph_rank_0_74_V_read),
    .rank_ex_75_V_read(ph_rank_0_75_V_read),
    .rank_ex_76_V_read(ph_rank_0_76_V_read),
    .rank_ex_77_V_read(ph_rank_0_77_V_read),
    .rank_ex_78_V_read(ph_rank_0_78_V_read),
    .rank_ex_79_V_read(ph_rank_0_79_V_read),
    .rank_ex_80_V_read(ph_rank_0_80_V_read),
    .rank_ex_81_V_read(ph_rank_0_81_V_read),
    .rank_ex_82_V_read(ph_rank_0_82_V_read),
    .rank_ex_83_V_read(ph_rank_0_83_V_read),
    .rank_ex_84_V_read(ph_rank_0_84_V_read),
    .rank_ex_85_V_read(ph_rank_0_85_V_read),
    .rank_ex_86_V_read(ph_rank_0_86_V_read),
    .rank_ex_87_V_read(ph_rank_0_87_V_read),
    .rank_ex_88_V_read(ph_rank_0_88_V_read),
    .rank_ex_89_V_read(ph_rank_0_89_V_read),
    .rank_ex_90_V_read(ph_rank_0_90_V_read),
    .rank_ex_91_V_read(ph_rank_0_91_V_read),
    .rank_ex_92_V_read(ph_rank_0_92_V_read),
    .rank_ex_93_V_read(ph_rank_0_93_V_read),
    .rank_ex_94_V_read(ph_rank_0_94_V_read),
    .rank_ex_95_V_read(ph_rank_0_95_V_read),
    .rank_ex_96_V_read(ph_rank_0_96_V_read),
    .rank_ex_97_V_read(ph_rank_0_97_V_read),
    .rank_ex_98_V_read(ph_rank_0_98_V_read),
    .rank_ex_99_V_read(ph_rank_0_99_V_read),
    .rank_ex_100_V_read(ph_rank_0_100_V_read),
    .rank_ex_101_V_read(ph_rank_0_101_V_read),
    .rank_ex_102_V_read(ph_rank_0_102_V_read),
    .rank_ex_103_V_read(ph_rank_0_103_V_read),
    .rank_ex_104_V_read(ph_rank_0_104_V_read),
    .rank_ex_105_V_read(ph_rank_0_105_V_read),
    .rank_ex_106_V_read(ph_rank_0_106_V_read),
    .rank_ex_107_V_read(ph_rank_0_107_V_read),
    .rank_ex_108_V_read(ph_rank_0_108_V_read),
    .rank_ex_109_V_read(ph_rank_0_109_V_read),
    .rank_ex_110_V_read(ph_rank_0_110_V_read),
    .rank_ex_111_V_read(ph_rank_0_111_V_read),
    .rank_ex_112_V_read(ph_rank_0_112_V_read),
    .rank_ex_113_V_read(ph_rank_0_113_V_read),
    .rank_ex_114_V_read(ph_rank_0_114_V_read),
    .rank_ex_115_V_read(ph_rank_0_115_V_read),
    .rank_ex_116_V_read(ph_rank_0_116_V_read),
    .rank_ex_117_V_read(ph_rank_0_117_V_read),
    .rank_ex_118_V_read(ph_rank_0_118_V_read),
    .rank_ex_119_V_read(ph_rank_0_119_V_read),
    .rank_ex_120_V_read(ph_rank_0_120_V_read),
    .rank_ex_121_V_read(ph_rank_0_121_V_read),
    .ap_return_0(grp_sp_best3_fu_3932_ap_return_0),
    .ap_return_1(grp_sp_best3_fu_3932_ap_return_1),
    .ap_return_2(grp_sp_best3_fu_3932_ap_return_2),
    .ap_return_3(grp_sp_best3_fu_3932_ap_return_3),
    .ap_return_4(grp_sp_best3_fu_3932_ap_return_4),
    .ap_return_5(grp_sp_best3_fu_3932_ap_return_5)
);

sp_best3 grp_sp_best3_fu_4180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .rank_ex_0_V_read(ph_rank_1_0_V_read),
    .rank_ex_1_V_read(ph_rank_1_1_V_read),
    .rank_ex_2_V_read(ph_rank_1_2_V_read),
    .rank_ex_3_V_read(ph_rank_1_3_V_read),
    .rank_ex_4_V_read(ph_rank_1_4_V_read),
    .rank_ex_5_V_read(ph_rank_1_5_V_read),
    .rank_ex_6_V_read(ph_rank_1_6_V_read),
    .rank_ex_7_V_read(ph_rank_1_7_V_read),
    .rank_ex_8_V_read(ph_rank_1_8_V_read),
    .rank_ex_9_V_read(ph_rank_1_9_V_read),
    .rank_ex_10_V_read(ph_rank_1_10_V_read),
    .rank_ex_11_V_read(ph_rank_1_11_V_read),
    .rank_ex_12_V_read(ph_rank_1_12_V_read),
    .rank_ex_13_V_read(ph_rank_1_13_V_read),
    .rank_ex_14_V_read(ph_rank_1_14_V_read),
    .rank_ex_15_V_read(ph_rank_1_15_V_read),
    .rank_ex_16_V_read(ph_rank_1_16_V_read),
    .rank_ex_17_V_read(ph_rank_1_17_V_read),
    .rank_ex_18_V_read(ph_rank_1_18_V_read),
    .rank_ex_19_V_read(ph_rank_1_19_V_read),
    .rank_ex_20_V_read(ph_rank_1_20_V_read),
    .rank_ex_21_V_read(ph_rank_1_21_V_read),
    .rank_ex_22_V_read(ph_rank_1_22_V_read),
    .rank_ex_23_V_read(ph_rank_1_23_V_read),
    .rank_ex_24_V_read(ph_rank_1_24_V_read),
    .rank_ex_25_V_read(ph_rank_1_25_V_read),
    .rank_ex_26_V_read(ph_rank_1_26_V_read),
    .rank_ex_27_V_read(ph_rank_1_27_V_read),
    .rank_ex_28_V_read(ph_rank_1_28_V_read),
    .rank_ex_29_V_read(ph_rank_1_29_V_read),
    .rank_ex_30_V_read(ph_rank_1_30_V_read),
    .rank_ex_31_V_read(ph_rank_1_31_V_read),
    .rank_ex_32_V_read(ph_rank_1_32_V_read),
    .rank_ex_33_V_read(ph_rank_1_33_V_read),
    .rank_ex_34_V_read(ph_rank_1_34_V_read),
    .rank_ex_35_V_read(ph_rank_1_35_V_read),
    .rank_ex_36_V_read(ph_rank_1_36_V_read),
    .rank_ex_37_V_read(ph_rank_1_37_V_read),
    .rank_ex_38_V_read(ph_rank_1_38_V_read),
    .rank_ex_39_V_read(ph_rank_1_39_V_read),
    .rank_ex_40_V_read(ph_rank_1_40_V_read),
    .rank_ex_41_V_read(ph_rank_1_41_V_read),
    .rank_ex_42_V_read(ph_rank_1_42_V_read),
    .rank_ex_43_V_read(ph_rank_1_43_V_read),
    .rank_ex_44_V_read(ph_rank_1_44_V_read),
    .rank_ex_45_V_read(ph_rank_1_45_V_read),
    .rank_ex_46_V_read(ph_rank_1_46_V_read),
    .rank_ex_47_V_read(ph_rank_1_47_V_read),
    .rank_ex_48_V_read(ph_rank_1_48_V_read),
    .rank_ex_49_V_read(ph_rank_1_49_V_read),
    .rank_ex_50_V_read(ph_rank_1_50_V_read),
    .rank_ex_51_V_read(ph_rank_1_51_V_read),
    .rank_ex_52_V_read(ph_rank_1_52_V_read),
    .rank_ex_53_V_read(ph_rank_1_53_V_read),
    .rank_ex_54_V_read(ph_rank_1_54_V_read),
    .rank_ex_55_V_read(ph_rank_1_55_V_read),
    .rank_ex_56_V_read(ph_rank_1_56_V_read),
    .rank_ex_57_V_read(ph_rank_1_57_V_read),
    .rank_ex_58_V_read(ph_rank_1_58_V_read),
    .rank_ex_59_V_read(ph_rank_1_59_V_read),
    .rank_ex_60_V_read(ph_rank_1_60_V_read),
    .rank_ex_61_V_read(ph_rank_1_61_V_read),
    .rank_ex_62_V_read(ph_rank_1_62_V_read),
    .rank_ex_63_V_read(ph_rank_1_63_V_read),
    .rank_ex_64_V_read(ph_rank_1_64_V_read),
    .rank_ex_65_V_read(ph_rank_1_65_V_read),
    .rank_ex_66_V_read(ph_rank_1_66_V_read),
    .rank_ex_67_V_read(ph_rank_1_67_V_read),
    .rank_ex_68_V_read(ph_rank_1_68_V_read),
    .rank_ex_69_V_read(ph_rank_1_69_V_read),
    .rank_ex_70_V_read(ph_rank_1_70_V_read),
    .rank_ex_71_V_read(ph_rank_1_71_V_read),
    .rank_ex_72_V_read(ph_rank_1_72_V_read),
    .rank_ex_73_V_read(ph_rank_1_73_V_read),
    .rank_ex_74_V_read(ph_rank_1_74_V_read),
    .rank_ex_75_V_read(ph_rank_1_75_V_read),
    .rank_ex_76_V_read(ph_rank_1_76_V_read),
    .rank_ex_77_V_read(ph_rank_1_77_V_read),
    .rank_ex_78_V_read(ph_rank_1_78_V_read),
    .rank_ex_79_V_read(ph_rank_1_79_V_read),
    .rank_ex_80_V_read(ph_rank_1_80_V_read),
    .rank_ex_81_V_read(ph_rank_1_81_V_read),
    .rank_ex_82_V_read(ph_rank_1_82_V_read),
    .rank_ex_83_V_read(ph_rank_1_83_V_read),
    .rank_ex_84_V_read(ph_rank_1_84_V_read),
    .rank_ex_85_V_read(ph_rank_1_85_V_read),
    .rank_ex_86_V_read(ph_rank_1_86_V_read),
    .rank_ex_87_V_read(ph_rank_1_87_V_read),
    .rank_ex_88_V_read(ph_rank_1_88_V_read),
    .rank_ex_89_V_read(ph_rank_1_89_V_read),
    .rank_ex_90_V_read(ph_rank_1_90_V_read),
    .rank_ex_91_V_read(ph_rank_1_91_V_read),
    .rank_ex_92_V_read(ph_rank_1_92_V_read),
    .rank_ex_93_V_read(ph_rank_1_93_V_read),
    .rank_ex_94_V_read(ph_rank_1_94_V_read),
    .rank_ex_95_V_read(ph_rank_1_95_V_read),
    .rank_ex_96_V_read(ph_rank_1_96_V_read),
    .rank_ex_97_V_read(ph_rank_1_97_V_read),
    .rank_ex_98_V_read(ph_rank_1_98_V_read),
    .rank_ex_99_V_read(ph_rank_1_99_V_read),
    .rank_ex_100_V_read(ph_rank_1_100_V_read),
    .rank_ex_101_V_read(ph_rank_1_101_V_read),
    .rank_ex_102_V_read(ph_rank_1_102_V_read),
    .rank_ex_103_V_read(ph_rank_1_103_V_read),
    .rank_ex_104_V_read(ph_rank_1_104_V_read),
    .rank_ex_105_V_read(ph_rank_1_105_V_read),
    .rank_ex_106_V_read(ph_rank_1_106_V_read),
    .rank_ex_107_V_read(ph_rank_1_107_V_read),
    .rank_ex_108_V_read(ph_rank_1_108_V_read),
    .rank_ex_109_V_read(ph_rank_1_109_V_read),
    .rank_ex_110_V_read(ph_rank_1_110_V_read),
    .rank_ex_111_V_read(ph_rank_1_111_V_read),
    .rank_ex_112_V_read(ph_rank_1_112_V_read),
    .rank_ex_113_V_read(ph_rank_1_113_V_read),
    .rank_ex_114_V_read(ph_rank_1_114_V_read),
    .rank_ex_115_V_read(ph_rank_1_115_V_read),
    .rank_ex_116_V_read(ph_rank_1_116_V_read),
    .rank_ex_117_V_read(ph_rank_1_117_V_read),
    .rank_ex_118_V_read(ph_rank_1_118_V_read),
    .rank_ex_119_V_read(ph_rank_1_119_V_read),
    .rank_ex_120_V_read(ph_rank_1_120_V_read),
    .rank_ex_121_V_read(ph_rank_1_121_V_read),
    .ap_return_0(grp_sp_best3_fu_4180_ap_return_0),
    .ap_return_1(grp_sp_best3_fu_4180_ap_return_1),
    .ap_return_2(grp_sp_best3_fu_4180_ap_return_2),
    .ap_return_3(grp_sp_best3_fu_4180_ap_return_3),
    .ap_return_4(grp_sp_best3_fu_4180_ap_return_4),
    .ap_return_5(grp_sp_best3_fu_4180_ap_return_5)
);

sp_best3 grp_sp_best3_fu_4428(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .rank_ex_0_V_read(ph_rank_2_0_V_read),
    .rank_ex_1_V_read(ph_rank_2_1_V_read),
    .rank_ex_2_V_read(ph_rank_2_2_V_read),
    .rank_ex_3_V_read(ph_rank_2_3_V_read),
    .rank_ex_4_V_read(ph_rank_2_4_V_read),
    .rank_ex_5_V_read(ph_rank_2_5_V_read),
    .rank_ex_6_V_read(ph_rank_2_6_V_read),
    .rank_ex_7_V_read(ph_rank_2_7_V_read),
    .rank_ex_8_V_read(ph_rank_2_8_V_read),
    .rank_ex_9_V_read(ph_rank_2_9_V_read),
    .rank_ex_10_V_read(ph_rank_2_10_V_read),
    .rank_ex_11_V_read(ph_rank_2_11_V_read),
    .rank_ex_12_V_read(ph_rank_2_12_V_read),
    .rank_ex_13_V_read(ph_rank_2_13_V_read),
    .rank_ex_14_V_read(ph_rank_2_14_V_read),
    .rank_ex_15_V_read(ph_rank_2_15_V_read),
    .rank_ex_16_V_read(ph_rank_2_16_V_read),
    .rank_ex_17_V_read(ph_rank_2_17_V_read),
    .rank_ex_18_V_read(ph_rank_2_18_V_read),
    .rank_ex_19_V_read(ph_rank_2_19_V_read),
    .rank_ex_20_V_read(ph_rank_2_20_V_read),
    .rank_ex_21_V_read(ph_rank_2_21_V_read),
    .rank_ex_22_V_read(ph_rank_2_22_V_read),
    .rank_ex_23_V_read(ph_rank_2_23_V_read),
    .rank_ex_24_V_read(ph_rank_2_24_V_read),
    .rank_ex_25_V_read(ph_rank_2_25_V_read),
    .rank_ex_26_V_read(ph_rank_2_26_V_read),
    .rank_ex_27_V_read(ph_rank_2_27_V_read),
    .rank_ex_28_V_read(ph_rank_2_28_V_read),
    .rank_ex_29_V_read(ph_rank_2_29_V_read),
    .rank_ex_30_V_read(ph_rank_2_30_V_read),
    .rank_ex_31_V_read(ph_rank_2_31_V_read),
    .rank_ex_32_V_read(ph_rank_2_32_V_read),
    .rank_ex_33_V_read(ph_rank_2_33_V_read),
    .rank_ex_34_V_read(ph_rank_2_34_V_read),
    .rank_ex_35_V_read(ph_rank_2_35_V_read),
    .rank_ex_36_V_read(ph_rank_2_36_V_read),
    .rank_ex_37_V_read(ph_rank_2_37_V_read),
    .rank_ex_38_V_read(ph_rank_2_38_V_read),
    .rank_ex_39_V_read(ph_rank_2_39_V_read),
    .rank_ex_40_V_read(ph_rank_2_40_V_read),
    .rank_ex_41_V_read(ph_rank_2_41_V_read),
    .rank_ex_42_V_read(ph_rank_2_42_V_read),
    .rank_ex_43_V_read(ph_rank_2_43_V_read),
    .rank_ex_44_V_read(ph_rank_2_44_V_read),
    .rank_ex_45_V_read(ph_rank_2_45_V_read),
    .rank_ex_46_V_read(ph_rank_2_46_V_read),
    .rank_ex_47_V_read(ph_rank_2_47_V_read),
    .rank_ex_48_V_read(ph_rank_2_48_V_read),
    .rank_ex_49_V_read(ph_rank_2_49_V_read),
    .rank_ex_50_V_read(ph_rank_2_50_V_read),
    .rank_ex_51_V_read(ph_rank_2_51_V_read),
    .rank_ex_52_V_read(ph_rank_2_52_V_read),
    .rank_ex_53_V_read(ph_rank_2_53_V_read),
    .rank_ex_54_V_read(ph_rank_2_54_V_read),
    .rank_ex_55_V_read(ph_rank_2_55_V_read),
    .rank_ex_56_V_read(ph_rank_2_56_V_read),
    .rank_ex_57_V_read(ph_rank_2_57_V_read),
    .rank_ex_58_V_read(ph_rank_2_58_V_read),
    .rank_ex_59_V_read(ph_rank_2_59_V_read),
    .rank_ex_60_V_read(ph_rank_2_60_V_read),
    .rank_ex_61_V_read(ph_rank_2_61_V_read),
    .rank_ex_62_V_read(ph_rank_2_62_V_read),
    .rank_ex_63_V_read(ph_rank_2_63_V_read),
    .rank_ex_64_V_read(ph_rank_2_64_V_read),
    .rank_ex_65_V_read(ph_rank_2_65_V_read),
    .rank_ex_66_V_read(ph_rank_2_66_V_read),
    .rank_ex_67_V_read(ph_rank_2_67_V_read),
    .rank_ex_68_V_read(ph_rank_2_68_V_read),
    .rank_ex_69_V_read(ph_rank_2_69_V_read),
    .rank_ex_70_V_read(ph_rank_2_70_V_read),
    .rank_ex_71_V_read(ph_rank_2_71_V_read),
    .rank_ex_72_V_read(ph_rank_2_72_V_read),
    .rank_ex_73_V_read(ph_rank_2_73_V_read),
    .rank_ex_74_V_read(ph_rank_2_74_V_read),
    .rank_ex_75_V_read(ph_rank_2_75_V_read),
    .rank_ex_76_V_read(ph_rank_2_76_V_read),
    .rank_ex_77_V_read(ph_rank_2_77_V_read),
    .rank_ex_78_V_read(ph_rank_2_78_V_read),
    .rank_ex_79_V_read(ph_rank_2_79_V_read),
    .rank_ex_80_V_read(ph_rank_2_80_V_read),
    .rank_ex_81_V_read(ph_rank_2_81_V_read),
    .rank_ex_82_V_read(ph_rank_2_82_V_read),
    .rank_ex_83_V_read(ph_rank_2_83_V_read),
    .rank_ex_84_V_read(ph_rank_2_84_V_read),
    .rank_ex_85_V_read(ph_rank_2_85_V_read),
    .rank_ex_86_V_read(ph_rank_2_86_V_read),
    .rank_ex_87_V_read(ph_rank_2_87_V_read),
    .rank_ex_88_V_read(ph_rank_2_88_V_read),
    .rank_ex_89_V_read(ph_rank_2_89_V_read),
    .rank_ex_90_V_read(ph_rank_2_90_V_read),
    .rank_ex_91_V_read(ph_rank_2_91_V_read),
    .rank_ex_92_V_read(ph_rank_2_92_V_read),
    .rank_ex_93_V_read(ph_rank_2_93_V_read),
    .rank_ex_94_V_read(ph_rank_2_94_V_read),
    .rank_ex_95_V_read(ph_rank_2_95_V_read),
    .rank_ex_96_V_read(ph_rank_2_96_V_read),
    .rank_ex_97_V_read(ph_rank_2_97_V_read),
    .rank_ex_98_V_read(ph_rank_2_98_V_read),
    .rank_ex_99_V_read(ph_rank_2_99_V_read),
    .rank_ex_100_V_read(ph_rank_2_100_V_read),
    .rank_ex_101_V_read(ph_rank_2_101_V_read),
    .rank_ex_102_V_read(ph_rank_2_102_V_read),
    .rank_ex_103_V_read(ph_rank_2_103_V_read),
    .rank_ex_104_V_read(ph_rank_2_104_V_read),
    .rank_ex_105_V_read(ph_rank_2_105_V_read),
    .rank_ex_106_V_read(ph_rank_2_106_V_read),
    .rank_ex_107_V_read(ph_rank_2_107_V_read),
    .rank_ex_108_V_read(ph_rank_2_108_V_read),
    .rank_ex_109_V_read(ph_rank_2_109_V_read),
    .rank_ex_110_V_read(ph_rank_2_110_V_read),
    .rank_ex_111_V_read(ph_rank_2_111_V_read),
    .rank_ex_112_V_read(ph_rank_2_112_V_read),
    .rank_ex_113_V_read(ph_rank_2_113_V_read),
    .rank_ex_114_V_read(ph_rank_2_114_V_read),
    .rank_ex_115_V_read(ph_rank_2_115_V_read),
    .rank_ex_116_V_read(ph_rank_2_116_V_read),
    .rank_ex_117_V_read(ph_rank_2_117_V_read),
    .rank_ex_118_V_read(ph_rank_2_118_V_read),
    .rank_ex_119_V_read(ph_rank_2_119_V_read),
    .rank_ex_120_V_read(ph_rank_2_120_V_read),
    .rank_ex_121_V_read(ph_rank_2_121_V_read),
    .ap_return_0(grp_sp_best3_fu_4428_ap_return_0),
    .ap_return_1(grp_sp_best3_fu_4428_ap_return_1),
    .ap_return_2(grp_sp_best3_fu_4428_ap_return_2),
    .ap_return_3(grp_sp_best3_fu_4428_ap_return_3),
    .ap_return_4(grp_sp_best3_fu_4428_ap_return_4),
    .ap_return_5(grp_sp_best3_fu_4428_ap_return_5)
);

sp_best3 grp_sp_best3_fu_4676(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .rank_ex_0_V_read(ph_rank_3_0_V_read),
    .rank_ex_1_V_read(ph_rank_3_1_V_read),
    .rank_ex_2_V_read(ph_rank_3_2_V_read),
    .rank_ex_3_V_read(ph_rank_3_3_V_read),
    .rank_ex_4_V_read(ph_rank_3_4_V_read),
    .rank_ex_5_V_read(ph_rank_3_5_V_read),
    .rank_ex_6_V_read(ph_rank_3_6_V_read),
    .rank_ex_7_V_read(ph_rank_3_7_V_read),
    .rank_ex_8_V_read(ph_rank_3_8_V_read),
    .rank_ex_9_V_read(ph_rank_3_9_V_read),
    .rank_ex_10_V_read(ph_rank_3_10_V_read),
    .rank_ex_11_V_read(ph_rank_3_11_V_read),
    .rank_ex_12_V_read(ph_rank_3_12_V_read),
    .rank_ex_13_V_read(ph_rank_3_13_V_read),
    .rank_ex_14_V_read(ph_rank_3_14_V_read),
    .rank_ex_15_V_read(ph_rank_3_15_V_read),
    .rank_ex_16_V_read(ph_rank_3_16_V_read),
    .rank_ex_17_V_read(ph_rank_3_17_V_read),
    .rank_ex_18_V_read(ph_rank_3_18_V_read),
    .rank_ex_19_V_read(ph_rank_3_19_V_read),
    .rank_ex_20_V_read(ph_rank_3_20_V_read),
    .rank_ex_21_V_read(ph_rank_3_21_V_read),
    .rank_ex_22_V_read(ph_rank_3_22_V_read),
    .rank_ex_23_V_read(ph_rank_3_23_V_read),
    .rank_ex_24_V_read(ph_rank_3_24_V_read),
    .rank_ex_25_V_read(ph_rank_3_25_V_read),
    .rank_ex_26_V_read(ph_rank_3_26_V_read),
    .rank_ex_27_V_read(ph_rank_3_27_V_read),
    .rank_ex_28_V_read(ph_rank_3_28_V_read),
    .rank_ex_29_V_read(ph_rank_3_29_V_read),
    .rank_ex_30_V_read(ph_rank_3_30_V_read),
    .rank_ex_31_V_read(ph_rank_3_31_V_read),
    .rank_ex_32_V_read(ph_rank_3_32_V_read),
    .rank_ex_33_V_read(ph_rank_3_33_V_read),
    .rank_ex_34_V_read(ph_rank_3_34_V_read),
    .rank_ex_35_V_read(ph_rank_3_35_V_read),
    .rank_ex_36_V_read(ph_rank_3_36_V_read),
    .rank_ex_37_V_read(ph_rank_3_37_V_read),
    .rank_ex_38_V_read(ph_rank_3_38_V_read),
    .rank_ex_39_V_read(ph_rank_3_39_V_read),
    .rank_ex_40_V_read(ph_rank_3_40_V_read),
    .rank_ex_41_V_read(ph_rank_3_41_V_read),
    .rank_ex_42_V_read(ph_rank_3_42_V_read),
    .rank_ex_43_V_read(ph_rank_3_43_V_read),
    .rank_ex_44_V_read(ph_rank_3_44_V_read),
    .rank_ex_45_V_read(ph_rank_3_45_V_read),
    .rank_ex_46_V_read(ph_rank_3_46_V_read),
    .rank_ex_47_V_read(ph_rank_3_47_V_read),
    .rank_ex_48_V_read(ph_rank_3_48_V_read),
    .rank_ex_49_V_read(ph_rank_3_49_V_read),
    .rank_ex_50_V_read(ph_rank_3_50_V_read),
    .rank_ex_51_V_read(ph_rank_3_51_V_read),
    .rank_ex_52_V_read(ph_rank_3_52_V_read),
    .rank_ex_53_V_read(ph_rank_3_53_V_read),
    .rank_ex_54_V_read(ph_rank_3_54_V_read),
    .rank_ex_55_V_read(ph_rank_3_55_V_read),
    .rank_ex_56_V_read(ph_rank_3_56_V_read),
    .rank_ex_57_V_read(ph_rank_3_57_V_read),
    .rank_ex_58_V_read(ph_rank_3_58_V_read),
    .rank_ex_59_V_read(ph_rank_3_59_V_read),
    .rank_ex_60_V_read(ph_rank_3_60_V_read),
    .rank_ex_61_V_read(ph_rank_3_61_V_read),
    .rank_ex_62_V_read(ph_rank_3_62_V_read),
    .rank_ex_63_V_read(ph_rank_3_63_V_read),
    .rank_ex_64_V_read(ph_rank_3_64_V_read),
    .rank_ex_65_V_read(ph_rank_3_65_V_read),
    .rank_ex_66_V_read(ph_rank_3_66_V_read),
    .rank_ex_67_V_read(ph_rank_3_67_V_read),
    .rank_ex_68_V_read(ph_rank_3_68_V_read),
    .rank_ex_69_V_read(ph_rank_3_69_V_read),
    .rank_ex_70_V_read(ph_rank_3_70_V_read),
    .rank_ex_71_V_read(ph_rank_3_71_V_read),
    .rank_ex_72_V_read(ph_rank_3_72_V_read),
    .rank_ex_73_V_read(ph_rank_3_73_V_read),
    .rank_ex_74_V_read(ph_rank_3_74_V_read),
    .rank_ex_75_V_read(ph_rank_3_75_V_read),
    .rank_ex_76_V_read(ph_rank_3_76_V_read),
    .rank_ex_77_V_read(ph_rank_3_77_V_read),
    .rank_ex_78_V_read(ph_rank_3_78_V_read),
    .rank_ex_79_V_read(ph_rank_3_79_V_read),
    .rank_ex_80_V_read(ph_rank_3_80_V_read),
    .rank_ex_81_V_read(ph_rank_3_81_V_read),
    .rank_ex_82_V_read(ph_rank_3_82_V_read),
    .rank_ex_83_V_read(ph_rank_3_83_V_read),
    .rank_ex_84_V_read(ph_rank_3_84_V_read),
    .rank_ex_85_V_read(ph_rank_3_85_V_read),
    .rank_ex_86_V_read(ph_rank_3_86_V_read),
    .rank_ex_87_V_read(ph_rank_3_87_V_read),
    .rank_ex_88_V_read(ph_rank_3_88_V_read),
    .rank_ex_89_V_read(ph_rank_3_89_V_read),
    .rank_ex_90_V_read(ph_rank_3_90_V_read),
    .rank_ex_91_V_read(ph_rank_3_91_V_read),
    .rank_ex_92_V_read(ph_rank_3_92_V_read),
    .rank_ex_93_V_read(ph_rank_3_93_V_read),
    .rank_ex_94_V_read(ph_rank_3_94_V_read),
    .rank_ex_95_V_read(ph_rank_3_95_V_read),
    .rank_ex_96_V_read(ph_rank_3_96_V_read),
    .rank_ex_97_V_read(ph_rank_3_97_V_read),
    .rank_ex_98_V_read(ph_rank_3_98_V_read),
    .rank_ex_99_V_read(ph_rank_3_99_V_read),
    .rank_ex_100_V_read(ph_rank_3_100_V_read),
    .rank_ex_101_V_read(ph_rank_3_101_V_read),
    .rank_ex_102_V_read(ph_rank_3_102_V_read),
    .rank_ex_103_V_read(ph_rank_3_103_V_read),
    .rank_ex_104_V_read(ph_rank_3_104_V_read),
    .rank_ex_105_V_read(ph_rank_3_105_V_read),
    .rank_ex_106_V_read(ph_rank_3_106_V_read),
    .rank_ex_107_V_read(ph_rank_3_107_V_read),
    .rank_ex_108_V_read(ph_rank_3_108_V_read),
    .rank_ex_109_V_read(ph_rank_3_109_V_read),
    .rank_ex_110_V_read(ph_rank_3_110_V_read),
    .rank_ex_111_V_read(ph_rank_3_111_V_read),
    .rank_ex_112_V_read(ph_rank_3_112_V_read),
    .rank_ex_113_V_read(ph_rank_3_113_V_read),
    .rank_ex_114_V_read(ph_rank_3_114_V_read),
    .rank_ex_115_V_read(ph_rank_3_115_V_read),
    .rank_ex_116_V_read(ph_rank_3_116_V_read),
    .rank_ex_117_V_read(ph_rank_3_117_V_read),
    .rank_ex_118_V_read(ph_rank_3_118_V_read),
    .rank_ex_119_V_read(ph_rank_3_119_V_read),
    .rank_ex_120_V_read(ph_rank_3_120_V_read),
    .rank_ex_121_V_read(ph_rank_3_121_V_read),
    .ap_return_0(grp_sp_best3_fu_4676_ap_return_0),
    .ap_return_1(grp_sp_best3_fu_4676_ap_return_1),
    .ap_return_2(grp_sp_best3_fu_4676_ap_return_2),
    .ap_return_3(grp_sp_best3_fu_4676_ap_return_3),
    .ap_return_4(grp_sp_best3_fu_4676_ap_return_4),
    .ap_return_5(grp_sp_best3_fu_4676_ap_return_5)
);

assign ap_return_0 = grp_sp_best3_fu_3932_ap_return_3;

assign ap_return_1 = grp_sp_best3_fu_3932_ap_return_4;

assign ap_return_10 = grp_sp_best3_fu_4676_ap_return_4;

assign ap_return_11 = grp_sp_best3_fu_4676_ap_return_5;

assign ap_return_12 = grp_sp_best3_fu_3932_ap_return_0;

assign ap_return_13 = grp_sp_best3_fu_3932_ap_return_1;

assign ap_return_14 = grp_sp_best3_fu_3932_ap_return_2;

assign ap_return_15 = grp_sp_best3_fu_4180_ap_return_0;

assign ap_return_16 = grp_sp_best3_fu_4180_ap_return_1;

assign ap_return_17 = grp_sp_best3_fu_4180_ap_return_2;

assign ap_return_18 = grp_sp_best3_fu_4428_ap_return_0;

assign ap_return_19 = grp_sp_best3_fu_4428_ap_return_1;

assign ap_return_2 = grp_sp_best3_fu_3932_ap_return_5;

assign ap_return_20 = grp_sp_best3_fu_4428_ap_return_2;

assign ap_return_21 = grp_sp_best3_fu_4676_ap_return_0;

assign ap_return_22 = grp_sp_best3_fu_4676_ap_return_1;

assign ap_return_23 = grp_sp_best3_fu_4676_ap_return_2;

assign ap_return_3 = grp_sp_best3_fu_4180_ap_return_3;

assign ap_return_4 = grp_sp_best3_fu_4180_ap_return_4;

assign ap_return_5 = grp_sp_best3_fu_4180_ap_return_5;

assign ap_return_6 = grp_sp_best3_fu_4428_ap_return_3;

assign ap_return_7 = grp_sp_best3_fu_4428_ap_return_4;

assign ap_return_8 = grp_sp_best3_fu_4428_ap_return_5;

assign ap_return_9 = grp_sp_best3_fu_4676_ap_return_3;

endmodule //sp_sort_sector
